const char* themes[]{
    "1: Dwelling",
    "2: Jungle",
    "2: Volcana",
    "3: Olmec",
    "4: Tide Pool",
    "4: Temple",
    "5: Ice Caves",
    "6: Neo Babylon",
    "7: Sunken City",
    "8: Cosmic Ocean",
    "4: City of Gold",
    "4: Duat",
    "4: Abzu",
    "6: Tiamat",
    "7: Eggplant World",
    "7: Hundun",
    "0: Base camp",
};

const char* themes_short[]{
    "Dwelling",
    "Jungle",
    "Volcana",
    "Olmec",
    "Tide Pool",
    "Temple",
    "Ice Caves",
    "Neo Babylon",
    "Sunken City",
    "Cosmic Ocean",
    "City of Gold",
    "Duat",
    "Abzu",
    "Tiamat",
    "Eggplant World",
    "Hundun",
    "Base camp",
};

const char* entity_flags[]{
    "1: Invisible",
    "2: Indestructable/special floor",
    "3: Solid (wall)",
    "4: Passes through objects",
    "5: Passes through everything",
    "6: Take no damage",
    "7: Throwable/Knockbackable",
    "8: Is platform",
    "9: Climbable (as rope/ladder)",
    "10: No gravity",
    "11: Interact with liquid",
    "12: Stunnable",
    "13: Collides walls",
    "14: Interact with semisolids?",
    "15: Can be stomped",
    "16: Power stomps",
    "17: Facing left",
    "18: Pickupable",
    "19: Usable item?",
    "20: Enable button prompt",
    "21: Interact with webs",
    "22: Can be carried through exit",
    "23: Shop item",
    "24: Shop floor (break to aggro)",
    "25: Passes through player",
    "26: Exploded",
    "27: Crushed",
    "28: Pause AI and physics",
    "29: Dead",
    "30: Character",
    "31: Movable",
    "32: Use overlay draw depth",
};

const char* more_flags[]{
    "1: Take damage on collision after throw",
    "2: Revived (HH)",
    "3: Blocks shield",
    "4: Passes through shield",
    "5: Being moved by shield",
    "6: Just spawned?",
    "7: Done spawning?",
    "8: Stuck in something",
    "9: Stuck in something, 1 frame later",
    "10: Pitchers mitt antigravity",
    "11: Swimming",
    "12: Hit ground",
    "13: Hit wall",
    "14: Falling",
    "15: Cursed effect",
    "16: Elixir buff",
    "17: Disable input",
    "18: Shop item held by player",
    "19: Falling platform something",
    "20: Yangs turkey",
    "21: Floor can be decorated",
    "22: Disable collision",
    "23: JumpWhipped to shorthop",
    "24: ",
    "25: ",
    "26: ",
    "27: ",
    "28: ",
    "29: ",
    "30: ",
    "31: ",
    "32: ",
};

const char* entity_type_properties_flags[]{
    "1: Apply solid block beautification",
    "2: Treat as FLOORSTYLED",
    "3: ",
    "4: ",
    "5: Squirts blood on damage",
    "6: Climbable (as wall)",
    "7: ",
    "8: Fireproof",
    "9: Double fire and explosive damage",
    "10: Is on fire/lights on fire",
    "11: Poison immunity",
    "12: Poisons arrows when hit",
    "13: Curse immunity",
    "14: Cursed pot effect (curses you when destroyed closeby)",
    "15: ",
    "16: ",
    "17: ",
    "18: Can be carried through layer doors",
    "19: ",
    "20: ",
    "21: Can spawn monsters on top",
    "22: ",
    "23: Can be cloned",
    "24: Can be bubbled",
    "25: Can be telefragged",
    "26: Disable updates?",
    "27: Kill entity when overlay lost?",
    "28: Unused",
    "29: Unused",
    "30: Unused",
    "31: Unused",
    "32: Unused",
};

const char* level_flags[]{
    "1: Upbeat dwelling intro music played",
    "2: ",
    "3: Running tutorial speedrun",
    "4: Level has pet",
    "5: Level has Tun/shop?",
    "6: Tun killed?",
    "7: Ghost pot level?",
    "8: Dead are restless",
    "9: Bees/Metal clanking/Oppression",
    "10: Angry shopkeeper",
    "11: Angry Tun",
    "12: Angry caveman shopkeeper",
    "13: Angry ghist shopkeeper",
    "14: Angry Yang",
    "15: Angry Tusk",
    "16: Angry Waddler",
    "17: Shop level?",
    "18: Dark level (draw halo)",
    "19: Altar destroyed",
    "20: Allow pause",
    "21: Hide hud, transition",
    "22: Hide hud, camp",
    "23: Have clover",
    "24: Show forgiveness toast",
    "25: ",
    "26: Daily challenge options",
    "27: ",
    "28: ",
    "29: ",
    "30: ",
    "31: ",
    "32: ",
};

const char* journal_flags[]{
    "1: I was a pacifist",
    "2: I was a vegan",
    "3: I was a vegetarian",
    "4: I was a petty criminal",
    "5: I was a wanted criminal",
    "6: I was a crime lord",
    "7: I was a king",
    "8: I was a queen",
    "9: I was a fool",
    "10: I was an eggplant",
    "11: I didn't care for treasure",
    "12: I liked pets",
    "13: I loved pets",
    "14: I took damage",
    "15: I survived death once",
    "16: I slayed Kingu",
    "17: I slayed Osiris",
    "18: I defeated Tiamat",
    "19: I defeated Hundun",
    "20: I became one with the Cosmos",
    "21: I eventually died",
    "22: ",
    "23: ",
    "24: ",
    "25: ",
    "26: ",
    "27: ",
    "28: ",
    "29: ",
    "30: ",
    "31: ",
    "32: ",
};

const char* quest_flags[]{
    "1: Reset",
    "2: Dark level spawned in world",
    "3: Vault spawned in world",
    "4: Next level has shopkeeper outpost (if possible)",
    "5: Shop spawned",
    "6: Shortcut used",
    "7: Seeded mode",
    "8: Daily challenge mode",
    "9: Caveman Shopkeeper aggroed",
    "10: Waddler aggroed",
    "11: Shop bought out",
    "12: Eggplant crown picked up",
    "13: ",
    "14: ",
    "15: ",
    "16: ",
    "17: Udjat eye spawned",
    "18: Black market spawned",
    "19: Drill spawned",
    "20: ",
    "21: ",
    "22: ",
    "23: ",
    "24: ",
    "25: Moon challenge spawned",
    "26: Star challenge spawned",
    "27: Sun challenge spawned",
    "28: ",
    "29: ",
    "30: ",
    "31: ",
    "32: ",
};

const char* presence_flags[]{
    "1: Udjat eye",
    "2: Black market",
    "3: Vlad's castle/drill",
    "4: ",
    "5: ",
    "6: ",
    "7: ",
    "8: ",
    "9: Moon challenge",
    "10: Star challenge",
    "11: Sun challenge",
    "12: ",
    "13: ",
    "14: ",
    "15: ",
    "16: ",
    "17: ",
    "18: ",
    "19: ",
    "20: ",
    "21: ",
    "22: ",
    "23: ",
    "24: ",
    "25: ",
    "26: ",
    "27: ",
    "28: ",
    "29: ",
    "30: ",
    "31: ",
    "32: ",
};

const char* illumination_flags[]{
    // this is actually two 8bit flags as they have different behaviors
    "1: Disable light1",
    "2: Enable light2",
    "3: Enable light3",
    "4: Enable light4",
    "5: ",
    "6: ",
    "7: Modulate brightness_multiplier",
    "8: ",
    // type_flags 1-8:
    "9: Follow camera",
    "10: Follow entity",
    "11: Static, Rectangle, Full brightness",
    "12: unused",
    "13: unused",
    "14: unused",
    "15: unused",
    "16: unused",
};

const char* special_visibility_flags[]{
    "1: Crust embedded items shown",
    "2: Crust embedded items shown (level transition)",
    "3: ",
    "4: ",
    "5: ",
    "6: ",
    "7: ",
    "8: ",
    "9: Compass door markers shown",
    "10: Compass door markers shown (level transition)",
    "11: ",
    "12: ",
    "13: ",
    "14: ",
    "15: ",
    "16: ",
    "17: Special compass door markers shown",
    "18: Special compass door markers shown (level transition)",
    "19: ",
    "20: ",
    "21: ",
    "22: ",
    "23: ",
    "24: ",
    "25: In back layer",
    "26: ",
    "27: ",
    "28: ",
    "29: ",
    "30: ",
    "31: ",
    "32: ",
};

const char* basecamp_dialogue_win_flags[]{
    "1: Ana Spelunky saved",
    "2: Margaret Tunnel saved",
    "3: Colin Northward saved",
    "4: Roffy D. Sloth saved",
    "5: Alto Singh saved",
    "6: Liz Mutton saved",
    "7: Nekka The Eagle saved",
    "8: LISE project saved",
    "9: Coco Von Diamonds saved",
    "10: Manfred Tunnel saved",
    "11: Little Jay saved",
    "12: Tina Flan saved",
    "13: Valerie Crump saved",
    "14: Au saved",
    "15: Demi Von Diamonds saved",
    "16: Pilot saved",
    "17: Princess Airyn saved",
    "18: Dirk Yamaoka saved",
    "19: Tiamat win",
    "20: Hundun win",
    "21: ",
    "22: ",
    "23: ",
    "24: ",
    "25: ",
    "26: ",
    "27: ",
    "28: ",
    "29: ",
    "30: ",
    "31: ",
    "32: ",
};

const char* places_flags[]{
    "Dwelling",
    "Jungle",
    "Volcana",
    "Olmec's Lair",
    "Tide Pool",
    "Abzu",
    "Temple of Anubis",
    "The City of Gold",
    "Duat",
    "Ice Caves",
    "Neo Babylon",
    "Tiamat's Throne",
    "Sunken City",
    "Eggplant World",
    "Hundun's Hideaway",
    "Cosmic Ocean",
};

const char* people_flags[]{
    "Ana Spelunky",
    "Margaret Tunnel",
    "Colin Northward",
    "Roffy D. Sloth",
    "Alto Singh",
    "Liz Mutton",
    "Nekka the Eagle",
    "LISE Project",
    "Coco Von Diamonds",
    "Manfred Tunnel",
    "Little Jay",
    "Tina Flan",
    "Valerie Crump",
    "Au",
    "Demi Von Diamonds",
    "Pilot",
    "Princess Airyn",
    "Dirk Yamaoka",
    "Guy Spelunky",
    "Classic Guy",
    "Terra Tunnel",
    "Hired Hand",
    "Eggplant Child",
    "Shopkeeper",
    "Tun",
    "Yang",
    "Madame Tusk",
    "Tusk's Bodyguard",
    "Waddler",
    "Caveman Shopkeeper",
    "Ghist Shopkeeper",
    "Van Horsing",
    "Parsley",
    "Parsnip",
    "Parmesan",
    "Sparrow",
    "Beg",
    "Eggplant King",
};

const char* bestiary_flags[]{
    "Snake",
    "Spider",
    "Bat",
    "Caveman",
    "Skeleton",
    "Horned Lizard",
    "Cave Mole",
    "Quillback",
    "Mantrap",
    "Tiki man",
    "Witch Doctor",
    "Mosquito",
    "Monkey",
    "Hang Spider",
    "Giant Spider",
    "Magmar",
    "Robot",
    "Fire Bug",
    "Imp",
    "Lavamander",
    "Vampire",
    "Vlad",
    "Olmec",
    "Jiangshi",
    "Jiangshi Assassin",
    "Flying Fish",
    "Octopy",
    "Hermit Crab",
    "Pangxie",
    "Great Humphead",
    "Kingu",
    "Crocman",
    "Cobra",
    "Mummy",
    "Sorceress",
    "Cat Mummy",
    "Necromancer",
    "Anubis",
    "Ammit",
    "Apep",
    "Anubis II",
    "Osiris",
    "UFO",
    "Alien",
    "Yeti",
    "Yeti King",
    "Yeti Queen",
    "Lahamu",
    "Proto Shopkeeper",
    "Olmite",
    "Lamassu",
    "Tiamat",
    "Tadpole",
    "Frog",
    "Fire Frog",
    "Goliath Frog",
    "Grub",
    "Giant Fly",
    "Hundun",
    "Eggplant Minister",
    "Eggplup",
    "Celestial Jelly",
    "Scorpion",
    "Bee",
    "Queen Bee",
    "Scarab",
    "Golden Monkey",
    "Leprechaun",
    "Monty",
    "Percy",
    "Poochi",
    "Ghist",
    "Ghost",
    "Cave Turkey",
    "Rock Dog",
    "Axolotl",
    "Qilin",
    "Mech Rider",
};

const char* items_flags[]{
    "Rope Pile",
    "Bomb Bag",
    "Bomb Box",
    "Paste",
    "Spectacles",
    "Climbing Gloves",
    "Pitcher's Mitt",
    "Spring Shoes",
    "Spike Shoes",
    "Compass",
    "Alien Compass",
    "Parachute",
    "Udjat Eye",
    "Kapala",
    "Hedjet",
    "Crown",
    "Eggplant Crown",
    "The True Crown",
    "Ankh",
    "Tablet of Destiny",
    "Skeleton Key",
    "Royal Jelly",
    "Cape",
    "Vlad's Cape",
    "Jetpack",
    "Telepack",
    "Hoverpack",
    "Powerpack",
    "Webgun",
    "Shotgun",
    "Freeze Ray",
    "Clone Gun",
    "Crossbow",
    "Camera",
    "Teleporter",
    "Mattock",
    "Boomerang",
    "Machete",
    "Excalibur",
    "Broken Sword",
    "Plasma Cannon",
    "Scepter",
    "Hou Yi's Bow",
    "Arrow of Light",
    "Wooden Shield",
    "Metal Shield",
    "Idol",
    "The Tusk Idol",
    "Curse Pot",
    "Ushabti",
    "Eggplant",
    "Cooked Turkey",
    "Elixir",
    "Four-Leaf Clover",
};

const char* traps_flags[]{
    "Spikes",
    "Arrow Trap",
    "Totem Trap",
    "Log Trap",
    "Spear Trap",
    "Thorny Vine",
    "Bear Trap",
    "Powder Box",
    "Falling Platform",
    "Spikeball",
    "Lion Trap",
    "Giant Clam",
    "Sliding Wall",
    "Crush Trap",
    "Giant Crush Trap",
    "Boulder",
    "Spring Trap",
    "Landmine",
    "Laser Trap",
    "Spark Trap",
    "Frog Trap",
    "Sticky Trap",
    "Bone Drop",
    "Egg Sac",
};

const char* shortcut_flags[]{
    "None",
    "Met Terra",
    "1-4: $2,000",
    "1-4: Bomb",
    "1-4: $10,000 (Unlocked)",
    "3-1: Rope",
    "3-1: Weapon",
    "3-1: Mount (Unlocked)",
    "5-1: $50,000",
    "5-1: Hired Hand",
    "5-1: Golden Key (Unlocked)",
};

/*const char *empty_flags[]{
    "1: ",
"2: ",
"3: ",
"4: ",
"5: ",
"6: ",
"7: ",
"8: ",
"9: ",
"10: ",
"11: ",
"12: ",
"13: ",
"14: ",
"15: ",
"16: ",
    "17: ",
"18: ",
"19: ",
"20: ",
"21: ",
"22: ",
"23: ",
"24: ",
"25: ",
"26: ",
"27: ",
"28: ",
"29: ",
"30: ",
"31: ",
"32: ",};*/

const char* button_flags[]{
    "Jp",
    "Wp",
    "Bm",
    "Rp",
    "Rn",
    "Dr",
};
const char* direction_flags[]{
    "Left",
    "Down",
    "Up",
    "Right",
};

const char* liquid_pool_names[]{
    "Water",
    "Coarse Water",
    "Lava",
    "Coarse Lava",
    "Stagnant Lava",
};

const char* mask_names[]{
    "Player",
    "Mount",
    "Monster",
    "Item",
    "Explosion",
    "Rope",
    "FX",
    "ActiveFloor",
    "Floor",
    "Decoration",
    "Background",
    "Shadow",
    "Logical",
    "Water",
    "Lava",
};

const char* char_states[]{
    "Flailing",
    "Standing",
    "Sitting",
    "???",
    "Hanging",
    "Ducking",
    "Climbing",
    "Pushing",
    "Jumping",
    "Falling",
    "Dropping",
    "???",
    "Attacking",
    "???",
    "???",
    "???",
    "???",
    "Throwing",
    "Stunned",
    "Entering",
    "Loading",
    "Exiting",
    "Dying",
};

const char* screen_names[]{
    "Logo",
    "Intro",
    "Prologue",
    "Title",
    "Menu",
    "Options",
    "Player Profile",
    "Leaderboard",
    "Seed Input",
    "Character Select",
    "Team Select",
    "Camp",
    "Level",
    "Transition",
    "Death",
    "Spaceship",
    "Win",
    "Credits",
    "Scores",
    "Constellation",
    "Recap",
    "Arena Menu",
    "Arena Stages",
    "Arena Items",
    "Arena Select",
    "Arena Intro",
    "Arena Level",
    "Arena Score",
    "Online Loading",
    "Online Lobby",
};

const char* pause_types[]{
    "1: Menu",
    "2: Fade (janky camera, default)",
    "4: Cutscene",
    "8: ?",
    "16: ?",
    "32: Ankh (smooth camera, janky audio)",
    "Freeze on PRE_UPDATE", // this is not a real state.pause flag, it's only used by ui.cpp for magic
};

const char* levelgen_flags[]{
    "1: Should generate path",
    "2: Can spawn vault",
    "3: Can spawn shops",
    "4: Can have outpost?",
    "5: Should spawn hard floor decorations",
    "6: Apply ambient occlusion",
    "7: Should spawn behind-floor and below-floorstyled decorations",
    "8: unknown",
};

const char* levelgen_flags2[]{
    "1: Spawns background decorations on ground (ceiling if false)",
    "2: Spawns fake ladder/chain midbg?",
    "3: Spawn entrance door background (Ignored in 7-1 to 7-2 transition)",
    "4: Procedural backlayer door midbg indicator related",
    "5: Spawn backlayer border/background",
    "6: Should spawn procedural backlayers",
    "7: Should spawn backlayer torches",
    "8: Has ghost",
};

const char* levelgen_flags3[]{
    "1: Can spawn angry NPCs",
    "2: Can echo",
    "3: Can spawn Dead are Restless",
    "4: Can spawn procedural skeletons",
    "5: Can have quests?",
    "6: Can spawn player coffins",
    "7: unknown",
    "8: unknown",
};
