#include "entity_casting_lua.hpp"

namespace NEntityCasting
{
void register_usertypes(sol::state& lua, ScriptImpl* script)
{
    lua.create_named_table("TYPE_MAP");

    // lua["TYPE_MAP"][1] = "as_floordeco";  // FLOOR_BORDERTILE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][2] = "as_floordeco";  // FLOOR_BORDERTILE_METAL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][3] = "as_floordeco";  // FLOOR_BORDERTILE_OCTOPUS (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][4] = "as_floordeco";  // FLOOR_GENERIC (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][5] = "as_floordeco";  // FLOOR_SURFACE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][6] = "as_floordeco";  // FLOOR_SURFACE_HIDDEN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][7] = "as_floordeco";  // FLOOR_BASECAMP_SINGLEBED (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][8] = "as_floordeco";  // FLOOR_BASECAMP_DININGTABLE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][9] = "as_floordeco";  // FLOOR_BASECAMP_LONGTABLE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][10] = "as_floordeco";  // FLOOR_JUNGLE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][11] = "as_floordeco";  // FLOOR_TUNNEL_CURRENT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][12] = "as_floordeco";  // FLOOR_TUNNEL_NEXT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][13] = "as_floordeco";  // FLOOR_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][14] = "as_floordeco";  // FLOOR_PAGODA_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][15] = "as_floordeco";  // FLOOR_LADDER (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][16] = "as_floordeco";  // FLOOR_LADDER_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][17] = "as_floordeco";  // FLOOR_VINE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][18] = "as_floordeco";  // FLOOR_VINE_TREE_TOP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][19] = "as_floordeco";  // FLOOR_GROWABLE_VINE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][20] = "as_floordeco";  // FLOOR_CLIMBING_POLE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][21] = "as_floordeco";  // FLOOR_GROWABLE_CLIMBING_POLE (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][22] = "as_door"; // FLOOR_DOOR_ENTRANCE
    // lua["TYPE_MAP"][23] = "as_exitdoor";  // FLOOR_DOOR_EXIT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][24] = "as_mainexit";  // FLOOR_DOOR_MAIN_EXIT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][25] = "as_exitdoor";  // FLOOR_DOOR_STARTING_EXIT (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][26] = "as_door"; // FLOOR_DOOR_LAYER
    lua["TYPE_MAP"][27] = "as_door"; // FLOOR_DOOR_LAYER_DROP_HELD
    lua["TYPE_MAP"][28] = "as_door"; // FLOOR_DOOR_GHISTSHOP
    // lua["TYPE_MAP"][29] = "as_lockeddoor";  // FLOOR_DOOR_LOCKED (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][30] = "as_lockeddoor";  // FLOOR_DOOR_LOCKED_PEN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][31] = "as_cityofgolddoor";  // FLOOR_DOOR_COG (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][32] = "as_door"; // FLOOR_DOOR_MOAI_STATUE
    // lua["TYPE_MAP"][33] = "as_eggshipdoor";  // FLOOR_DOOR_EGGSHIP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][34] = "as_eggshipdoor";  // FLOOR_DOOR_EGGSHIP_ATREZZO (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][35] = "as_eggshipdoor";  // FLOOR_DOOR_EGGSHIP_ROOM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][36] = "as_exitdoor";  // FLOOR_DOOR_EGGPLANT_WORLD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][37] = "as_floordeco";  // FLOOR_DOOR_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][38] = "as_floordeco";  // FLOOR_SPIKES (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][39] = "as_floordeco";  // FLOOR_SPIKES_UPSIDEDOWN (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][40] = "as_arrowtrap"; // FLOOR_ARROW_TRAP
    lua["TYPE_MAP"][41] = "as_arrowtrap"; // FLOOR_POISONED_ARROW_TRAP
    // lua["TYPE_MAP"][42] = "as_totemtrap";  // FLOOR_TOTEM_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][43] = "as_floordeco";  // FLOOR_JUNGLE_SPEAR_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][44] = "as_totemtrap";  // FLOOR_LION_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][45] = "as_lasertrap";  // FLOOR_LASER_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][46] = "as_sparktrap";  // FLOOR_SPARK_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][47] = "as_altar";  // FLOOR_ALTAR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][48] = "as_floordeco";  // FLOOR_IDOL_BLOCK (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][49] = "as_floordeco";  // FLOOR_IDOL_TRAP_CEILING (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][50] = "as_floordeco";  // FLOOR_STORAGE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][51] = "as_floordeco";  // FLOOR_TREE_BASE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][52] = "as_floordeco";  // FLOOR_TREE_TRUNK (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][53] = "as_floordeco";  // FLOOR_TREE_TOP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][54] = "as_floordeco";  // FLOOR_TREE_BRANCH (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][55] = "as_floordeco";  // FLOOR_MUSHROOM_BASE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][56] = "as_floordeco";  // FLOOR_MUSHROOM_TRUNK (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][57] = "as_floordeco";  // FLOOR_MUSHROOM_TOP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][58] = "as_floordeco";  // FLOOR_MUSHROOM_HAT_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][59] = "as_floordeco";  // FLOOR_THORN_VINE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][60] = "as_spikeballtrap";  // FLOOR_SPIKEBALL_CEILING (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][61] = "as_floordeco";  // FLOOR_CHAINANDBLOCKS_CEILING (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][62] = "as_floordeco";  // FLOOR_CHAINANDBLOCKS_CHAIN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][63] = "as_floordeco";  // FLOOR_CHAIN_CEILING (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][64] = "as_conveyorbelt";  // FLOOR_CONVEYORBELT_LEFT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][65] = "as_conveyorbelt";  // FLOOR_CONVEYORBELT_RIGHT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][66] = "as_generator";  // FLOOR_FACTORY_GENERATOR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][67] = "as_slidingwallceiling";  // FLOOR_SLIDINGWALL_CEILING (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][68] = "as_quicksand";  // FLOOR_QUICKSAND (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][69] = "as_floordeco";  // FLOOR_EXCALIBUR_STONE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][70] = "as_floordeco";  // FLOOR_DUSTWALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][71] = "as_altar";  // FLOOR_DUAT_ALTAR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][72] = "as_floordeco";  // FLOOR_ICE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][73] = "as_floordeco";  // FLOOR_SPRING_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][74] = "as_altar";  // FLOOR_EGGPLANT_ALTAR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][75] = "as_floordeco";  // FLOOR_MOAI_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][76] = "as_generator";  // FLOOR_SHOPKEEPER_GENERATOR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][77] = "as_generator";  // FLOOR_SUNCHALLENGE_GENERATOR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][78] = "as_pipe";  // FLOOR_PIPE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][79] = "as_bigspear";  // FLOOR_BIGSPEAR_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][80] = "as_stickytrap";  // FLOOR_STICKYTRAP_CEILING (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][81] = "as_mother";  // FLOOR_MOTHER_STATUE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][82] = "as_floordeco";  // FLOOR_MOTHER_STATUE_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][83] = "as_floordeco";  // FLOOR_GIANTFROG_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][84] = "as_teleportingfloor";  // FLOOR_TELEPORTINGBORDER (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][85] = "as_forcefield";  // FLOOR_FORCEFIELD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][86] = "as_forcefield";  // FLOOR_DICE_FORCEFIELD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][87] = "as_forcefield";  // FLOOR_CHALLENGE_ENTRANCE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][88] = "as_forcefield";  // FLOOR_CHALLENGE_WAITROOM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][89] = "as_timedforcefield";  // FLOOR_TIMED_FORCEFIELD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][90] = "as_floordeco";  // FLOOR_FORCEFIELD_TOP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][91] = "as_horizontalff";  // FLOOR_HORIZONTAL_FORCEFIELD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][92] = "as_floordeco";  // FLOOR_HORIZONTAL_FORCEFIELD_TOP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][93] = "as_floordeco";  // FLOOR_PEN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][94] = "as_floordeco";  // FLOOR_TOMB (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][95] = "as_floordeco";  // FLOOR_YAMA_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][96] = "as_floordeco";  // FLOOR_EMPRESS_GRAVE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][97] = "as_floordeco";  // FLOOR_PALACE_TABLE_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][98] = "as_floordeco";  // FLOOR_PALACE_TRAY_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][99] = "as_floordeco";  // FLOOR_PALACE_CHANDELIER_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][100] = "as_floordeco";  // FLOOR_PALACE_BOOKCASE_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][101] = "as_tentacle";  // FLOOR_TENTACLE_BOTTOM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][102] = "as_poledeco";  // FLOORSTYLED_MINEWOOD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][103] = "as_floordeco";  // FLOORSTYLED_STONE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][104] = "as_floordeco";  // FLOORSTYLED_TEMPLE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][105] = "as_poledeco";  // FLOORSTYLED_PAGODA (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][106] = "as_floordeco";  // FLOORSTYLED_BABYLON (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][107] = "as_floordeco";  // FLOORSTYLED_SUNKEN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][108] = "as_floordeco";  // FLOORSTYLED_BEEHIVE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][109] = "as_floordeco";  // FLOORSTYLED_VLAD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][110] = "as_floordeco";  // FLOORSTYLED_COG (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][111] = "as_floordeco";  // FLOORSTYLED_MOTHERSHIP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][112] = "as_floordeco";  // FLOORSTYLED_DUAT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][113] = "as_floordeco";  // FLOORSTYLED_PALACE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][114] = "as_floordeco";  // FLOORSTYLED_GUTS (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][190] = "as_floordeco";  // EMBED_GOLD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][191] = "as_floordeco";  // EMBED_GOLD_BIG (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][194] = "as_player";            // CHAR_ANA_SPELUNKY
    lua["TYPE_MAP"][195] = "as_player";            // CHAR_MARGARET_TUNNEL
    lua["TYPE_MAP"][196] = "as_player";            // CHAR_COLIN_NORTHWARD
    lua["TYPE_MAP"][197] = "as_player";            // CHAR_ROFFY_D_SLOTH
    lua["TYPE_MAP"][198] = "as_player";            // CHAR_BANDA
    lua["TYPE_MAP"][199] = "as_player";            // CHAR_GREEN_GIRL
    lua["TYPE_MAP"][200] = "as_player";            // CHAR_AMAZON
    lua["TYPE_MAP"][201] = "as_player";            // CHAR_LISE_SYSTEM
    lua["TYPE_MAP"][202] = "as_player";            // CHAR_COCO_VON_DIAMONDS
    lua["TYPE_MAP"][203] = "as_player";            // CHAR_MANFRED_TUNNEL
    lua["TYPE_MAP"][204] = "as_player";            // CHAR_OTAKU
    lua["TYPE_MAP"][205] = "as_player";            // CHAR_TINA_FLAN
    lua["TYPE_MAP"][206] = "as_player";            // CHAR_VALERIE_CRUMP
    lua["TYPE_MAP"][207] = "as_player";            // CHAR_AU
    lua["TYPE_MAP"][208] = "as_player";            // CHAR_DEMI_VON_DIAMONDS
    lua["TYPE_MAP"][209] = "as_player";            // CHAR_PILOT
    lua["TYPE_MAP"][210] = "as_player";            // CHAR_PRINCESS_AIRYN
    lua["TYPE_MAP"][211] = "as_player";            // CHAR_DIRK_YAMAOKA
    lua["TYPE_MAP"][212] = "as_player";            // CHAR_GUY_SPELUNKY
    lua["TYPE_MAP"][213] = "as_player";            // CHAR_CLASSIC_GUY
    lua["TYPE_MAP"][215] = "as_player";            // CHAR_HIREDHAND
    lua["TYPE_MAP"][216] = "as_player";            // CHAR_EGGPLANT_CHILD
    lua["TYPE_MAP"][219] = "as_pet";               // MONS_PET_TUTORIAL
    lua["TYPE_MAP"][220] = "as_monster";           // MONS_SNAKE
    lua["TYPE_MAP"][221] = "as_spider";            // MONS_SPIDER
    lua["TYPE_MAP"][222] = "as_hangspider";        // MONS_HANGSPIDER
    lua["TYPE_MAP"][223] = "as_spider";            // MONS_GIANTSPIDER
    lua["TYPE_MAP"][224] = "as_monster";           // MONS_BAT
    lua["TYPE_MAP"][225] = "as_caveman";           // MONS_CAVEMAN
    lua["TYPE_MAP"][226] = "as_cavemanshopkeeper"; // MONS_CAVEMAN_SHOPKEEPER
    lua["TYPE_MAP"][227] = "as_skeleton";          // MONS_SKELETON
    lua["TYPE_MAP"][228] = "as_skeleton";          // MONS_REDSKELETON
    lua["TYPE_MAP"][229] = "as_scorpion";          // MONS_SCORPION
    lua["TYPE_MAP"][230] = "as_hornedlizard";      // MONS_HORNEDLIZARD
    lua["TYPE_MAP"][231] = "as_mole";              // MONS_MOLE
    lua["TYPE_MAP"][232] = "as_quillback";         // MONS_CAVEMAN_BOSS
    lua["TYPE_MAP"][233] = "as_mantrap";           // MONS_MANTRAP
    lua["TYPE_MAP"][234] = "as_caveman";           // MONS_TIKIMAN
    lua["TYPE_MAP"][235] = "as_witchdoctor";       // MONS_WITCHDOCTOR
    lua["TYPE_MAP"][236] = "as_witchdoctorskull";  // MONS_WITCHDOCTORSKULL
    lua["TYPE_MAP"][237] = "as_mosquito";          // MONS_MOSQUITO
    lua["TYPE_MAP"][238] = "as_monkey";            // MONS_MONKEY
    lua["TYPE_MAP"][239] = "as_magmaman";          // MONS_MAGMAMAN
    lua["TYPE_MAP"][240] = "as_robot";             // MONS_ROBOT
    lua["TYPE_MAP"][241] = "as_firebug";           // MONS_FIREBUG
    lua["TYPE_MAP"][242] = "as_firebugunchained";  // MONS_FIREBUG_UNCHAINED
    lua["TYPE_MAP"][243] = "as_imp";               // MONS_IMP
    lua["TYPE_MAP"][244] = "as_lavamander";        // MONS_LAVAMANDER
    lua["TYPE_MAP"][245] = "as_vampire";           // MONS_VAMPIRE
    lua["TYPE_MAP"][246] = "as_vlad";              // MONS_VLAD
    lua["TYPE_MAP"][247] = "as_crocman";           // MONS_CROCMAN
    lua["TYPE_MAP"][248] = "as_cobra";             // MONS_COBRA
    lua["TYPE_MAP"][249] = "as_mummy";             // MONS_MUMMY
    lua["TYPE_MAP"][250] = "as_sorceress";         // MONS_SORCERESS
    lua["TYPE_MAP"][251] = "as_catmummy";          // MONS_CATMUMMY
    lua["TYPE_MAP"][252] = "as_necromancer";       // MONS_NECROMANCER
    lua["TYPE_MAP"][253] = "as_anubis";            // MONS_ANUBIS
    lua["TYPE_MAP"][254] = "as_apephead";          // MONS_APEP_HEAD
    // lua["TYPE_MAP"][255] = "as_apepbody";  // MONS_APEP_BODY (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][256] = "as_apeppart";         // MONS_APEP_TAIL
    lua["TYPE_MAP"][257] = "as_osirishead";       // MONS_OSIRIS_HEAD
    lua["TYPE_MAP"][258] = "as_osirishand";       // MONS_OSIRIS_HAND
    lua["TYPE_MAP"][259] = "as_anubistwo";        // MONS_ANUBIS2
    lua["TYPE_MAP"][260] = "as_jiangshi";         // MONS_JIANGSHI
    lua["TYPE_MAP"][261] = "as_jiangshi";         // MONS_FEMALE_JIANGSHI
    lua["TYPE_MAP"][262] = "as_fish";             // MONS_FISH
    lua["TYPE_MAP"][263] = "as_octopus";          // MONS_OCTOPUS
    lua["TYPE_MAP"][264] = "as_hermitcrab";       // MONS_HERMITCRAB
    lua["TYPE_MAP"][265] = "as_giantfish";        // MONS_GIANTFISH
    lua["TYPE_MAP"][266] = "as_ufo";              // MONS_UFO
    lua["TYPE_MAP"][267] = "as_alien";            // MONS_ALIEN
    lua["TYPE_MAP"][268] = "as_yeti";             // MONS_YETI
    lua["TYPE_MAP"][269] = "as_yetiking";         // MONS_YETIKING
    lua["TYPE_MAP"][270] = "as_yetiqueen";        // MONS_YETIQUEEN
    lua["TYPE_MAP"][271] = "as_lahamu";           // MONS_ALIENQUEEN
    lua["TYPE_MAP"][272] = "as_protoshopkeeper";  // MONS_PROTOSHOPKEEPER
    lua["TYPE_MAP"][273] = "as_shopkeeperclone";  // MONS_SHOPKEEPERCLONE
    lua["TYPE_MAP"][274] = "as_lamassu";          // MONS_LAMASSU
    lua["TYPE_MAP"][275] = "as_olmite";           // MONS_OLMITE_HELMET
    lua["TYPE_MAP"][276] = "as_olmite";           // MONS_OLMITE_BODYARMORED
    lua["TYPE_MAP"][277] = "as_olmite";           // MONS_OLMITE_NAKED
    lua["TYPE_MAP"][278] = "as_bee";              // MONS_BEE
    lua["TYPE_MAP"][279] = "as_bee";              // MONS_QUEENBEE
    lua["TYPE_MAP"][280] = "as_ammit";            // MONS_AMMIT
    lua["TYPE_MAP"][281] = "as_kingu";            // MONS_KINGU
    lua["TYPE_MAP"][282] = "as_tiamat";           // MONS_TIAMAT
    lua["TYPE_MAP"][283] = "as_frog";             // MONS_FROG
    lua["TYPE_MAP"][284] = "as_firefrog";         // MONS_FIREFROG
    lua["TYPE_MAP"][285] = "as_giantfrog";        // MONS_GIANTFROG
    lua["TYPE_MAP"][286] = "as_grub";             // MONS_GRUB
    lua["TYPE_MAP"][287] = "as_tadpole";          // MONS_TADPOLE
    lua["TYPE_MAP"][288] = "as_giantfly";         // MONS_GIANTFLY
    lua["TYPE_MAP"][289] = "as_jumpdog";          // MONS_JUMPDOG
    lua["TYPE_MAP"][290] = "as_eggplantminister"; // MONS_EGGPLANT_MINISTER
    lua["TYPE_MAP"][291] = "as_yama";             // MONS_YAMA
    lua["TYPE_MAP"][292] = "as_hundun";           // MONS_HUNDUN
    lua["TYPE_MAP"][293] = "as_hundunhead";       // MONS_HUNDUN_BIRDHEAD
    lua["TYPE_MAP"][294] = "as_hundunhead";       // MONS_HUNDUN_SNAKEHEAD
    lua["TYPE_MAP"][295] = "as_scarab";           // MONS_SCARAB
    lua["TYPE_MAP"][296] = "as_shopkeeper";       // MONS_SHOPKEEPER
    lua["TYPE_MAP"][297] = "as_tun";              // MONS_MERCHANT
    lua["TYPE_MAP"][298] = "as_yang";             // MONS_YANG
    lua["TYPE_MAP"][299] = "as_monster";          // MONS_MARLA_TUNNEL
    lua["TYPE_MAP"][300] = "as_forestsister";     // MONS_SISTER_PARSLEY
    lua["TYPE_MAP"][301] = "as_forestsister";     // MONS_SISTER_PARSNIP
    lua["TYPE_MAP"][302] = "as_forestsister";     // MONS_SISTER_PARMESAN
    lua["TYPE_MAP"][303] = "as_vanhorsing";       // MONS_OLD_HUNTER
    lua["TYPE_MAP"][304] = "as_sparrow";          // MONS_THIEF
    lua["TYPE_MAP"][305] = "as_madametusk";       // MONS_MADAMETUSK
    lua["TYPE_MAP"][306] = "as_bodyguard";        // MONS_BODYGUARD
    lua["TYPE_MAP"][307] = "as_beg";              // MONS_HUNDUNS_SERVANT
    lua["TYPE_MAP"][308] = "as_waddler";          // MONS_STORAGEGUY
    lua["TYPE_MAP"][309] = "as_goldmonkey";       // MONS_GOLDMONKEY
    lua["TYPE_MAP"][310] = "as_leprechaun";       // MONS_LEPRECHAUN
    lua["TYPE_MAP"][311] = "as_crabman";          // MONS_CRABMAN
    lua["TYPE_MAP"][312] = "as_megajellyfish";    // MONS_MEGAJELLYFISH
    lua["TYPE_MAP"][313] = "as_megajellyfish";    // MONS_MEGAJELLYFISH_BACKGROUND
    lua["TYPE_MAP"][314] = "as_ghist";            // MONS_GHIST
    lua["TYPE_MAP"][315] = "as_ghistshopkeeper";  // MONS_GHIST_SHOPKEEPER
    lua["TYPE_MAP"][317] = "as_ghost";            // MONS_GHOST
    lua["TYPE_MAP"][318] = "as_ghost";            // MONS_GHOST_MEDIUM_SAD
    lua["TYPE_MAP"][319] = "as_ghost";            // MONS_GHOST_MEDIUM_HAPPY
    lua["TYPE_MAP"][320] = "as_ghost";            // MONS_GHOST_SMALL_ANGRY
    lua["TYPE_MAP"][321] = "as_ghost";            // MONS_GHOST_SMALL_SAD
    lua["TYPE_MAP"][322] = "as_ghost";            // MONS_GHOST_SMALL_SURPRISED
    lua["TYPE_MAP"][323] = "as_ghost";            // MONS_GHOST_SMALL_HAPPY
    lua["TYPE_MAP"][326] = "as_pet";              // MONS_PET_DOG
    lua["TYPE_MAP"][327] = "as_pet";              // MONS_PET_CAT
    lua["TYPE_MAP"][328] = "as_pet";              // MONS_PET_HAMSTER
    lua["TYPE_MAP"][331] = "as_monster";          // MONS_CRITTERDUNGBEETLE
    lua["TYPE_MAP"][332] = "as_critterbutterfly"; // MONS_CRITTERBUTTERFLY
    lua["TYPE_MAP"][333] = "as_crittersnail";     // MONS_CRITTERSNAIL
    lua["TYPE_MAP"][334] = "as_critterfish";      // MONS_CRITTERFISH
    lua["TYPE_MAP"][335] = "as_monster";          // MONS_CRITTERANCHOVY
    lua["TYPE_MAP"][336] = "as_crittercrab";      // MONS_CRITTERCRAB
    lua["TYPE_MAP"][337] = "as_critterlocust";    // MONS_CRITTERLOCUST
    lua["TYPE_MAP"][338] = "as_critterpenguin";   // MONS_CRITTERPENGUIN
    lua["TYPE_MAP"][339] = "as_critterfirefly";   // MONS_CRITTERFIREFLY
    lua["TYPE_MAP"][340] = "as_critterdrone";     // MONS_CRITTERDRONE
    lua["TYPE_MAP"][341] = "as_critterslime";     // MONS_CRITTERSLIME
    lua["TYPE_MAP"][345] = "as_movable";          // ITEM_WHIP
    // lua["TYPE_MAP"][346] = "as_flamesize";  // ITEM_WHIP_FLAME (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][347] = "as_bomb";    // ITEM_BOMB
    lua["TYPE_MAP"][348] = "as_bomb";    // ITEM_PASTEBOMB
    lua["TYPE_MAP"][349] = "as_movable"; // ITEM_ROPE
    // lua["TYPE_MAP"][350] = "as_climbablerope";  // ITEM_CLIMBABLE_ROPE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][351] = "as_climbablerope";  // ITEM_UNROLLED_ROPE (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][352] = "as_movable"; // ITEM_BLOOD
    lua["TYPE_MAP"][353] = "as_movable"; // ITEM_EGGSHIP
    lua["TYPE_MAP"][354] = "as_movable"; // ITEM_PARENTSSHIP
    lua["TYPE_MAP"][355] = "as_movable"; // ITEM_OLMECSHIP
    // lua["TYPE_MAP"][356] = "as_idol";  // ITEM_IDOL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][357] = "as_idol";  // ITEM_MADAMETUSK_IDOL (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][358] = "as_movable"; // ITEM_MADAMETUSK_IDOLNOTE
    lua["TYPE_MAP"][359] = "as_movable"; // ITEM_HOLDTHEIDOL
    // lua["TYPE_MAP"][360] = "as_spear";  // ITEM_TOTEM_SPEAR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][361] = "as_junglespearcosmetic";  // ITEM_JUNGLE_SPEAR_COSMETIC (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][362] = "as_movable"; // ITEM_JUNGLE_SPEAR_DAMAGING
    // lua["TYPE_MAP"][363] = "as_spear";  // ITEM_LION_SPEAR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][364] = "as_spear";  // ITEM_BIG_SPEAR (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][365] = "as_movable"; // ITEM_ROCK
    lua["TYPE_MAP"][366] = "as_movable"; // ITEM_WEB
    // lua["TYPE_MAP"][367] = "as_webshot";  // ITEM_WEBSHOT (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][368] = "as_movable"; // ITEM_GIANTSPIDER_WEBSHOT
    // lua["TYPE_MAP"][369] = "as_webstrand";  // ITEM_HANGSTRAND (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][370] = "as_webanchor";  // ITEM_HANGANCHOR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][371] = "as_arrow";  // ITEM_WOODEN_ARROW (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][372] = "as_movable"; // ITEM_BROKEN_ARROW
    // lua["TYPE_MAP"][373] = "as_arrow";  // ITEM_METAL_ARROW (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][374] = "as_lightarrow";  // ITEM_LIGHT_ARROW (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][375] = "as_lightshot";  // ITEM_PLASMACANNON_SHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][376] = "as_sceptershot";  // ITEM_SCEPTER_ANUBISSHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][377] = "as_specialshot";  // ITEM_SCEPTER_ANUBISSPECIALSHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][378] = "as_sceptershot";  // ITEM_SCEPTER_PLAYERSHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][379] = "as_soundshot";  // ITEM_UFO_LASER_SHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][380] = "as_soundshot";  // ITEM_LAMASSU_LASER_SHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][381] = "as_lightshot";  // ITEM_SORCERESS_DAGGER_SHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][382] = "as_lightshot";  // ITEM_LASERTRAP_SHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][383] = "as_spark";  // ITEM_SPARK (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][384] = "as_tiamatshot";  // ITEM_TIAMAT_SHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][385] = "as_fireball";  // ITEM_FIREBALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][386] = "as_fireball";  // ITEM_HUNDUN_FIREBALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][387] = "as_flame";  // ITEM_FLAMETHROWER_FIREBALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][388] = "as_leaf";  // ITEM_LEAF (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][389] = "as_movable"; // ITEM_ACIDSPIT
    lua["TYPE_MAP"][390] = "as_movable"; // ITEM_INKSPIT
    lua["TYPE_MAP"][391] = "as_movable"; // ITEM_ACIDBUBBLE
    // lua["TYPE_MAP"][392] = "as_acidbubble";  // ITEM_CRABMAN_ACIDBUBBLE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][393] = "as_claw";  // ITEM_CRABMAN_CLAW (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][394] = "as_stretchchain";  // ITEM_CRABMAN_CLAWCHAIN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][395] = "as_chestinside";  // ITEM_CHEST (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][396] = "as_movable"; // ITEM_VAULTCHEST
    // lua["TYPE_MAP"][397] = "as_treasure";  // ITEM_ENDINGTREASURE_TIAMAT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][398] = "as_hundunchest";  // ITEM_ENDINGTREASURE_HUNDUN (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][399] = "as_movable";   // ITEM_KEY
    lua["TYPE_MAP"][400] = "as_movable";   // ITEM_LOCKEDCHEST
    lua["TYPE_MAP"][401] = "as_movable";   // ITEM_LOCKEDCHEST_KEY
    lua["TYPE_MAP"][402] = "as_container"; // ITEM_CRATE
    lua["TYPE_MAP"][403] = "as_container"; // ITEM_DMCRATE
    lua["TYPE_MAP"][404] = "as_movable";   // ITEM_TUTORIAL_MONSTER_SIGN
    lua["TYPE_MAP"][405] = "as_movable";   // ITEM_CONSTRUCTION_SIGN
    lua["TYPE_MAP"][406] = "as_movable";   // ITEM_SHORTCUT_SIGN
    lua["TYPE_MAP"][407] = "as_movable";   // ITEM_SPEEDRUN_SIGN
    lua["TYPE_MAP"][408] = "as_movable";   // ITEM_BASECAMP_TUTORIAL_SIGN
    // lua["TYPE_MAP"][409] = "as_boombox";  // ITEM_BOOMBOX (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][410] = "as_tv";  // ITEM_TV (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][411] = "as_telescope";  // ITEM_TELESCOPE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][412] = "as_walltorch";  // ITEM_WALLTORCH (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][413] = "as_flamesize";  // ITEM_WALLTORCHFLAME (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][414] = "as_walltorch";  // ITEM_LITWALLTORCH (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][415] = "as_walltorch";  // ITEM_AUTOWALLTORCH (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][416] = "as_torch";  // ITEM_TORCH (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][417] = "as_torchflame";  // ITEM_TORCHFLAME (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][418] = "as_torch";  // ITEM_LAMP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][419] = "as_lampflame";  // ITEM_LAMPFLAME (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][420] = "as_torch";  // ITEM_REDLANTERN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][421] = "as_lightemitter";  // ITEM_REDLANTERNFLAME (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][422] = "as_container"; // ITEM_PRESENT
    lua["TYPE_MAP"][423] = "as_container"; // ITEM_GHIST_PRESENT
    // lua["TYPE_MAP"][424] = "as_unknownpointergroup";  // ITEM_BULLET (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][425] = "as_timedshot";  // ITEM_FREEZERAYSHOT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][426] = "as_clonegunshot";  // ITEM_CLONEGUNSHOT (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][427] = "as_movable"; // ITEM_ICECAGE
    lua["TYPE_MAP"][428] = "as_movable"; // ITEM_BROKEN_MATTOCK
    // lua["TYPE_MAP"][429] = "as_punishball";  // ITEM_PUNISHBALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][430] = "as_stretchchain";  // ITEM_PUNISHCHAIN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][431] = "as_chain";  // ITEM_CHAIN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][432] = "as_chain";  // ITEM_CHAIN_LASTPIECE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][433] = "as_chain";  // ITEM_SLIDINGWALL_CHAIN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][434] = "as_chain";  // ITEM_SLIDINGWALL_CHAIN_LASTPIECE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][435] = "as_coffin";  // ITEM_COFFIN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][436] = "as_fly";  // ITEM_FLY (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][437] = "as_olmeccannon";  // ITEM_OLMECCANNON_BOMBS (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][438] = "as_olmeccannon";  // ITEM_OLMECCANNON_UFO (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][439] = "as_landmine";  // ITEM_LANDMINE (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][440] = "as_movable"; // ITEM_CURSING_CLOUD
    // lua["TYPE_MAP"][441] = "as_udjatsocket";  // ITEM_UDJAT_SOCKET (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][442] = "as_ushabti";  // ITEM_USHABTI (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][443] = "as_movable"; // ITEM_TURKEY_NECK
    // lua["TYPE_MAP"][444] = "as_honey";  // ITEM_HONEY (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][445] = "as_giantclamtop";  // ITEM_GIANTCLAM_TOP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][446] = "as_playerghost";  // ITEM_PLAYERGHOST (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][447] = "as_ghostbreath";  // ITEM_PLAYERGHOST_BREATH (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][448] = "as_movable"; // ITEM_DIE
    lua["TYPE_MAP"][449] = "as_movable"; // ITEM_DICE_BET
    lua["TYPE_MAP"][450] = "as_movable"; // ITEM_DICE_PRIZE_DISPENSER
    // lua["TYPE_MAP"][451] = "as_laserbeam";  // ITEM_LASERBEAM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][452] = "as_laserbeam";  // ITEM_HORIZONTALLASERBEAM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][453] = "as_coffin";  // ITEM_ANUBIS_COFFIN (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][454] = "as_movable"; // ITEM_SPIKES
    // lua["TYPE_MAP"][455] = "as_treasurehook";  // ITEM_EGGSHIP_HOOK (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][456] = "as_axolotlshot";  // ITEM_AXOLOTL_BUBBLESHOT (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][457] = "as_movable"; // ITEM_POTOFGOLD
    // lua["TYPE_MAP"][458] = "as_chain";  // ITEM_STICKYTRAP_PIECE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][459] = "as_chain";  // ITEM_STICKYTRAP_LASTPIECE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][460] = "as_trappart";  // ITEM_STICKYTRAP_BALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][461] = "as_skulldroptrap";  // ITEM_SKULLDROPTRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][462] = "as_frozenliquid";  // ITEM_FROZEN_LIQUID (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][463] = "as_container"; // ITEM_ALIVE_EMBEDDED_ON_ICE
    lua["TYPE_MAP"][464] = "as_movable";   // ITEM_DEPLOYED_PARACHUTE
    // lua["TYPE_MAP"][465] = "as_switch";  // ITEM_SLIDINGWALL_SWITCH (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][466] = "as_switch";  // ITEM_SLIDINGWALL_SWITCH_REWARD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][467] = "as_flyhead";  // ITEM_GIANTFLY_HEAD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][468] = "as_lightemitter";  // ITEM_PALACE_CANDLE_FLAME (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][469] = "as_snaptrap";  // ITEM_SNAP_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][470] = "as_empress";  // ITEM_EMPRESS_GRAVE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][471] = "as_itemtentacle";  // ITEM_TENTACLE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][472] = "as_chain";  // ITEM_TENTACLE_PIECE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][473] = "as_chain";  // ITEM_TENTACLE_LAST_PIECE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][474] = "as_miniship";  // ITEM_MINIGAME_SHIP (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][475] = "as_movable"; // ITEM_MINIGAME_UFO
    // lua["TYPE_MAP"][476] = "as_miniasteroid";  // ITEM_MINIGAME_ASTEROID_BG (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][477] = "as_miniasteroid";  // ITEM_MINIGAME_ASTEROID (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][478] = "as_miniasteroid";  // ITEM_MINIGAME_BROKEN_ASTEROID (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][480] = "as_pot";  // ITEM_POT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][481] = "as_cursedpot";  // ITEM_CURSEDPOT (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][482] = "as_movable"; // ITEM_SKULL
    lua["TYPE_MAP"][483] = "as_movable"; // ITEM_BONES
    // lua["TYPE_MAP"][484] = "as_cookfire";  // ITEM_COOKFIRE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][485] = "as_lightemitter";  // ITEM_LAVAPOT (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][486] = "as_movable"; // ITEM_SCRAP
    lua["TYPE_MAP"][487] = "as_movable"; // ITEM_EGGPLANT
    lua["TYPE_MAP"][488] = "as_movable"; // ITEM_ICESPIRE
    lua["TYPE_MAP"][489] = "as_movable"; // ITEM_PALACE_CANDLE
    lua["TYPE_MAP"][490] = "as_movable"; // ITEM_SKULLDROPTRAP_SKULL
    // lua["TYPE_MAP"][491] = "as_orb";  // ITEM_FLOATING_ORB (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][492] = "as_eggsac";  // ITEM_EGGSAC (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][495] = "as_goldbar";  // ITEM_GOLDBAR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][496] = "as_goldbar";  // ITEM_GOLDBARS (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][497] = "as_movable"; // ITEM_DIAMOND
    lua["TYPE_MAP"][498] = "as_movable"; // ITEM_EMERALD
    lua["TYPE_MAP"][499] = "as_movable"; // ITEM_SAPPHIRE
    lua["TYPE_MAP"][500] = "as_movable"; // ITEM_RUBY
    lua["TYPE_MAP"][501] = "as_movable"; // ITEM_NUGGET
    // lua["TYPE_MAP"][502] = "as_coin";  // ITEM_GOLDCOIN (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][503] = "as_movable"; // ITEM_EMERALD_SMALL
    lua["TYPE_MAP"][504] = "as_movable"; // ITEM_SAPPHIRE_SMALL
    lua["TYPE_MAP"][505] = "as_movable"; // ITEM_RUBY_SMALL
    lua["TYPE_MAP"][506] = "as_movable"; // ITEM_NUGGET_SMALL
    // lua["TYPE_MAP"][509] = "as_rollingitem";  // ITEM_PICKUP_TORNJOURNALPAGE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][510] = "as_rollingitem";  // ITEM_PICKUP_JOURNAL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][511] = "as_rollingitem";  // ITEM_PICKUP_ROPE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][512] = "as_rollingitem";  // ITEM_PICKUP_ROPEPILE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][513] = "as_rollingitem";  // ITEM_PICKUP_BOMBBAG (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][514] = "as_rollingitem";  // ITEM_PICKUP_BOMBBOX (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][515] = "as_rollingitem";  // ITEM_PICKUP_ROYALJELLY (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][516] = "as_rollingitem";  // ITEM_PICKUP_COOKEDTURKEY (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][517] = "as_rollingitem";  // ITEM_PICKUP_GIANTFOOD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][518] = "as_rollingitem";  // ITEM_PICKUP_ELIXIR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][519] = "as_rollingitem";  // ITEM_PICKUP_CLOVER (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][520] = "as_rollingitem";  // ITEM_PICKUP_SEEDEDRUNSUNLOCKER (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][522] = "as_rollingitem";  // ITEM_PICKUP_SPECTACLES (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][523] = "as_rollingitem";  // ITEM_PICKUP_CLIMBINGGLOVES (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][524] = "as_rollingitem";  // ITEM_PICKUP_PITCHERSMITT (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][525] = "as_rollingitem";  // ITEM_PICKUP_SPRINGSHOES (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][526] = "as_rollingitem";  // ITEM_PICKUP_SPIKESHOES (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][527] = "as_rollingitem";  // ITEM_PICKUP_PASTE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][528] = "as_rollingitem";  // ITEM_PICKUP_COMPASS (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][529] = "as_rollingitem";  // ITEM_PICKUP_SPECIALCOMPASS (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][530] = "as_rollingitem";  // ITEM_PICKUP_PARACHUTE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][531] = "as_rollingitem";  // ITEM_PICKUP_UDJATEYE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][532] = "as_rollingitem";  // ITEM_PICKUP_KAPALA (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][533] = "as_rollingitem";  // ITEM_PICKUP_HEDJET (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][534] = "as_rollingitem";  // ITEM_PICKUP_CROWN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][535] = "as_rollingitem";  // ITEM_PICKUP_EGGPLANTCROWN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][536] = "as_rollingitem";  // ITEM_PICKUP_TRUECROWN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][537] = "as_rollingitem";  // ITEM_PICKUP_ANKH (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][538] = "as_rollingitem";  // ITEM_PICKUP_TABLETOFDESTINY (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][539] = "as_rollingitem";  // ITEM_PICKUP_SKELETON_KEY (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][541] = "as_playerbag";  // ITEM_PICKUP_PLAYERBAG (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][543] = "as_movable";        // ITEM_POWERUP_PASTE
    lua["TYPE_MAP"][544] = "as_movable";        // ITEM_POWERUP_CLIMBING_GLOVES
    lua["TYPE_MAP"][545] = "as_movable";        // ITEM_POWERUP_SPIKE_SHOES
    lua["TYPE_MAP"][546] = "as_movable";        // ITEM_POWERUP_SPRING_SHOES
    lua["TYPE_MAP"][547] = "as_kapala_powerup"; // ITEM_POWERUP_KAPALA
    lua["TYPE_MAP"][548] = "as_movable";        // ITEM_POWERUP_SPECTACLES
    lua["TYPE_MAP"][549] = "as_movable";        // ITEM_POWERUP_PITCHERSMITT
    lua["TYPE_MAP"][550] = "as_movable";        // ITEM_POWERUP_UDJATEYE
    // lua["TYPE_MAP"][551] = "as_parachutepowerup";  // ITEM_POWERUP_PARACHUTE (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][552] = "as_movable"; // ITEM_POWERUP_COMPASS
    lua["TYPE_MAP"][553] = "as_movable"; // ITEM_POWERUP_SPECIALCOMPASS
    lua["TYPE_MAP"][554] = "as_movable"; // ITEM_POWERUP_HEDJET
    lua["TYPE_MAP"][555] = "as_movable"; // ITEM_POWERUP_CROWN
    lua["TYPE_MAP"][556] = "as_movable"; // ITEM_POWERUP_EGGPLANTCROWN
    // lua["TYPE_MAP"][557] = "as_truecrownpowerup";  // ITEM_POWERUP_TRUECROWN (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][558] = "as_ankhpowerup";  // ITEM_POWERUP_ANKH (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][559] = "as_movable"; // ITEM_POWERUP_TABLETOFDESTINY
    lua["TYPE_MAP"][560] = "as_movable"; // ITEM_POWERUP_SKELETON_KEY
    // lua["TYPE_MAP"][562] = "as_yellowcape";  // ITEM_CAPE (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][563] = "as_vlads_cape"; // ITEM_VLADS_CAPE
    lua["TYPE_MAP"][564] = "as_movable";    // ITEM_PURCHASABLE_CAPE
    lua["TYPE_MAP"][565] = "as_jetpack";    // ITEM_JETPACK
    lua["TYPE_MAP"][566] = "as_jetpack";    // ITEM_JETPACK_MECH
    lua["TYPE_MAP"][567] = "as_movable";    // ITEM_PURCHASABLE_JETPACK
    lua["TYPE_MAP"][568] = "as_backpack";   // ITEM_TELEPORTER_BACKPACK
    lua["TYPE_MAP"][569] = "as_movable";    // ITEM_PURCHASABLE_TELEPORTER_BACKPACK
    lua["TYPE_MAP"][570] = "as_hoverpack";  // ITEM_HOVERPACK
    lua["TYPE_MAP"][571] = "as_movable";    // ITEM_PURCHASABLE_HOVERPACK
    lua["TYPE_MAP"][572] = "as_backpack";   // ITEM_POWERPACK
    lua["TYPE_MAP"][573] = "as_movable";    // ITEM_PURCHASABLE_POWERPACK
    // lua["TYPE_MAP"][574] = "as_webgun";  // ITEM_WEBGUN (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][575] = "as_gun";     // ITEM_SHOTGUN
    lua["TYPE_MAP"][576] = "as_gun";     // ITEM_FREEZERAY
    lua["TYPE_MAP"][577] = "as_movable"; // ITEM_CROSSBOW
    lua["TYPE_MAP"][578] = "as_gun";     // ITEM_CAMERA
    // lua["TYPE_MAP"][579] = "as_teleporter";  // ITEM_TELEPORTER (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][580] = "as_mattock"; // ITEM_MATTOCK
    // lua["TYPE_MAP"][581] = "as_boomerang";  // ITEM_BOOMERANG (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][582] = "as_movable"; // ITEM_MACHETE
    // lua["TYPE_MAP"][583] = "as_excalibur";  // ITEM_EXCALIBUR (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][584] = "as_movable"; // ITEM_BROKENEXCALIBUR
    lua["TYPE_MAP"][585] = "as_gun";     // ITEM_PLASMACANNON
    lua["TYPE_MAP"][586] = "as_gun";     // ITEM_SCEPTER
    lua["TYPE_MAP"][587] = "as_gun";     // ITEM_CLONEGUN
    lua["TYPE_MAP"][588] = "as_movable"; // ITEM_HOUYIBOW
    // lua["TYPE_MAP"][589] = "as_shield";  // ITEM_WOODEN_SHIELD (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][590] = "as_shield";  // ITEM_METAL_SHIELD (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][594] = "as_movable"; // ACTIVEFLOOR_EGGSHIPPLATFORM
    lua["TYPE_MAP"][595] = "as_movable"; // ACTIVEFLOOR_EGGSHIPBLOCKER
    // lua["TYPE_MAP"][596] = "as_woodenlog";  // ACTIVEFLOOR_WOODENLOG_TRAP (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][597] = "as_boulder";  // ACTIVEFLOOR_BOULDER (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][598] = "as_pushblock";  // ACTIVEFLOOR_PUSHBLOCK (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][599] = "as_boneblock";  // ACTIVEFLOOR_BONEBLOCK (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][600] = "as_movable"; // ACTIVEFLOOR_BUSHBLOCK
    // lua["TYPE_MAP"][601] = "as_pushblock";  // ACTIVEFLOOR_POWDERKEG (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][602] = "as_chainedpushblock";  // ACTIVEFLOOR_CHAINEDPUSHBLOCK (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][603] = "as_movable"; // ACTIVEFLOOR_METALARROWPLATFORM
    // lua["TYPE_MAP"][604] = "as_lightarrowplatform";  // ACTIVEFLOOR_LIGHTARROWPLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][605] = "as_fallingplatform";  // ACTIVEFLOOR_FALLING_PLATFORM (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][606] = "as_trappart";  // ACTIVEFLOOR_CHAINED_SPIKEBALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][607] = "as_unchainedspikeball";  // ACTIVEFLOOR_UNCHAINED_SPIKEBALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][608] = "as_drill";  // ACTIVEFLOOR_DRILL (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][609] = "as_crushtrap"; // ACTIVEFLOOR_CRUSH_TRAP
    lua["TYPE_MAP"][610] = "as_crushtrap"; // ACTIVEFLOOR_CRUSH_TRAP_LARGE
    lua["TYPE_MAP"][611] = "as_olmec";     // ACTIVEFLOOR_OLMEC
    // lua["TYPE_MAP"][612] = "as_timedpowderkeg";  // ACTIVEFLOOR_TIMEDPOWDERKEG (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][613] = "as_trappart";  // ACTIVEFLOOR_SLIDINGWALL (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][614] = "as_thinice";  // ACTIVEFLOOR_THINICE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][615] = "as_elevator";  // ACTIVEFLOOR_ELEVATOR (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][616] = "as_clambase";  // ACTIVEFLOOR_GIANTCLAM_BASE (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][617] = "as_movable"; // ACTIVEFLOOR_KINGU_PLATFORM
    lua["TYPE_MAP"][618] = "as_movable"; // ACTIVEFLOOR_TIAMAT_PLATFORM
    lua["TYPE_MAP"][619] = "as_movable"; // ACTIVEFLOOR_TIAMAT_SHOULDERPLATFORM
    lua["TYPE_MAP"][620] = "as_movable"; // ACTIVEFLOOR_BUBBLE_PLATFORM
    lua["TYPE_MAP"][621] = "as_movable"; // ACTIVEFLOOR_CRUSHING_ELEVATOR
    lua["TYPE_MAP"][622] = "as_movable"; // ACTIVEFLOOR_SHIELD
    // lua["TYPE_MAP"][623] = "as_regenblock";  // ACTIVEFLOOR_REGENERATINGBLOCK (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][626] = "as_movable"; // FX_EGGSHIP_SHELL
    lua["TYPE_MAP"][627] = "as_movable"; // FX_EGGSHIP_DOOR
    lua["TYPE_MAP"][628] = "as_movable"; // FX_EGGSHIP_CENTERJETFLAME
    lua["TYPE_MAP"][629] = "as_movable"; // FX_EGGSHIP_JETFLAME
    lua["TYPE_MAP"][630] = "as_movable"; // FX_EGGSHIP_SHADOW
    lua["TYPE_MAP"][631] = "as_movable"; // FX_SHADOW
    lua["TYPE_MAP"][632] = "as_movable"; // FX_TORNJOURNALPAGE
    lua["TYPE_MAP"][633] = "as_movable"; // FX_MAIN_EXIT_DOOR
    lua["TYPE_MAP"][634] = "as_movable"; // FX_BIRDIES
    lua["TYPE_MAP"][635] = "as_movable"; // FX_EXPLOSION
    lua["TYPE_MAP"][636] = "as_movable"; // FX_POWEREDEXPLOSION
    lua["TYPE_MAP"][637] = "as_movable"; // FX_MODERNEXPLOSION
    lua["TYPE_MAP"][638] = "as_movable"; // FX_OUROBORO_OCCLUDER
    lua["TYPE_MAP"][639] = "as_movable"; // FX_OUROBORO_HEAD
    lua["TYPE_MAP"][640] = "as_movable"; // FX_OUROBORO_TAIL
    lua["TYPE_MAP"][641] = "as_movable"; // FX_OUROBORO_TEXT
    lua["TYPE_MAP"][642] = "as_movable"; // FX_OUROBORO_TRAIL
    lua["TYPE_MAP"][643] = "as_movable"; // ITEM_RUBBLE
    lua["TYPE_MAP"][644] = "as_movable"; // FX_COMPASS
    lua["TYPE_MAP"][645] = "as_movable"; // FX_SPECIALCOMPASS
    lua["TYPE_MAP"][646] = "as_movable"; // FX_PLAYERINDICATOR
    lua["TYPE_MAP"][647] = "as_movable"; // FX_PLAYERINDICATORPORTRAIT
    lua["TYPE_MAP"][648] = "as_movable"; // FX_SALEICON
    lua["TYPE_MAP"][649] = "as_movable"; // FX_SALEDIALOG_CONTAINER
    lua["TYPE_MAP"][650] = "as_movable"; // FX_SALEDIALOG_TITLE
    lua["TYPE_MAP"][651] = "as_movable"; // FX_SALEDIALOG_VALUE
    lua["TYPE_MAP"][652] = "as_movable"; // FX_SALEDIALOG_ICON
    lua["TYPE_MAP"][653] = "as_movable"; // FX_PICKUPEFFECT
    lua["TYPE_MAP"][654] = "as_movable"; // FX_SHOTGUNBLAST
    lua["TYPE_MAP"][655] = "as_movable"; // FX_JETPACKFLAME
    // lua["TYPE_MAP"][656] = "as_flame";  // FX_SMALLFLAME (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][657] = "as_movable"; // FX_SPRINGTRAP_RING
    lua["TYPE_MAP"][658] = "as_movable"; // FX_WITCHDOCTOR_HINT
    lua["TYPE_MAP"][659] = "as_movable"; // FX_NECROMANCER_ANKH
    // lua["TYPE_MAP"][660] = "as_lightemitter";  // FX_TELEPORTSHADOW (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][661] = "as_movable";       // FX_CINEMATIC_BLACKBAR
    lua["TYPE_MAP"][662] = "as_olmec_floater"; // FX_OLMECPART_FLOATER
    lua["TYPE_MAP"][663] = "as_movable";       // FX_OLMECPART_LARGE
    lua["TYPE_MAP"][664] = "as_movable";       // FX_OLMECPART_MEDIUM
    lua["TYPE_MAP"][665] = "as_movable";       // FX_OLMECPART_SMALL
    lua["TYPE_MAP"][666] = "as_movable";       // FX_OLMECPART_SMALLEST
    lua["TYPE_MAP"][667] = "as_movable";       // FX_WEBBEDEFFECT
    lua["TYPE_MAP"][668] = "as_movable";       // FX_BUTTON
    lua["TYPE_MAP"][669] = "as_movable";       // FX_BUTTON_DIALOG
    lua["TYPE_MAP"][670] = "as_movable";       // FX_SLEEP_BUBBLE
    lua["TYPE_MAP"][671] = "as_movable";       // FX_INK_BLINDNESS
    lua["TYPE_MAP"][672] = "as_movable";       // FX_INK_SPLAT
    lua["TYPE_MAP"][673] = "as_movable";       // FX_LAVA_BUBBLE
    // lua["TYPE_MAP"][674] = "as_lavaglow";  // FX_LAVA_GLOW (NOT IMPLEMENTED YET)
    lua["TYPE_MAP"][675] = "as_movable"; // FX_UNDERWATER_BUBBLE
    lua["TYPE_MAP"][676] = "as_movable"; // FX_WATER_DROP
    lua["TYPE_MAP"][677] = "as_movable"; // FX_WATER_SPLASH
    lua["TYPE_MAP"][678] = "as_movable"; // FX_WATER_SURFACE
    lua["TYPE_MAP"][679] = "as_movable"; // FX_APEP_FIRE
    lua["TYPE_MAP"][680] = "as_movable"; // FX_APEP_MOUTHPIECE
    lua["TYPE_MAP"][681] = "as_movable"; // FX_DRILL_TURNING
    lua["TYPE_MAP"][682] = "as_movable"; // FX_LEADER_FLAG
    lua["TYPE_MAP"][683] = "as_movable"; // FX_KINGU_HEAD
    lua["TYPE_MAP"][684] = "as_movable"; // FX_KINGU_SHADOW
    lua["TYPE_MAP"][685] = "as_movable"; // FX_KINGU_PLATFORM
    lua["TYPE_MAP"][686] = "as_movable"; // FX_KINGU_LIMB
    lua["TYPE_MAP"][687] = "as_movable"; // FX_KINGU_SLIDING
    lua["TYPE_MAP"][688] = "as_movable"; // FX_ALIENQUEEN_EYEBALL
    lua["TYPE_MAP"][689] = "as_movable"; // FX_ALIENQUEEN_EYE
    lua["TYPE_MAP"][690] = "as_movable"; // FX_ALIENBLAST_RETICULE_INTERNAL
    lua["TYPE_MAP"][691] = "as_movable"; // FX_ALIENBLAST_RETICULE_EXTERNAL
    lua["TYPE_MAP"][692] = "as_movable"; // FX_ALIENBLAST
    lua["TYPE_MAP"][693] = "as_movable"; // FX_SPARK
    lua["TYPE_MAP"][694] = "as_movable"; // FX_SPARK_SMALL
    lua["TYPE_MAP"][695] = "as_movable"; // FX_TIAMAT_THRONE
    lua["TYPE_MAP"][696] = "as_movable"; // FX_TIAMAT_WAIST
    lua["TYPE_MAP"][697] = "as_movable"; // FX_TIAMAT_TAIL
    lua["TYPE_MAP"][698] = "as_movable"; // FX_TIAMAT_TAIL_DECO1
    lua["TYPE_MAP"][699] = "as_movable"; // FX_TIAMAT_TAIL_DECO2
    lua["TYPE_MAP"][700] = "as_movable"; // FX_TIAMAT_TAIL_DECO3
    lua["TYPE_MAP"][701] = "as_movable"; // FX_TIAMAT_TORSO
    lua["TYPE_MAP"][702] = "as_movable"; // FX_TIAMAT_ARM_LEFT1
    lua["TYPE_MAP"][703] = "as_movable"; // FX_TIAMAT_ARM_LEFT2
    lua["TYPE_MAP"][704] = "as_movable"; // FX_TIAMAT_ARM_LEFT3
    lua["TYPE_MAP"][705] = "as_movable"; // FX_TIAMAT_ARM_RIGHT1
    lua["TYPE_MAP"][706] = "as_movable"; // FX_TIAMAT_ARM_RIGHT2
    lua["TYPE_MAP"][707] = "as_movable"; // FX_TIAMAT_NECK
    lua["TYPE_MAP"][708] = "as_movable"; // FX_TIAMAT_HEAD
    lua["TYPE_MAP"][709] = "as_movable"; // FX_DIEINDICATOR
    lua["TYPE_MAP"][710] = "as_movable"; // FX_STORAGE_INDICATOR
    lua["TYPE_MAP"][711] = "as_movable"; // FX_LASERBEAM
    lua["TYPE_MAP"][712] = "as_movable"; // FX_HORIZONTALLASERBEAM
    lua["TYPE_MAP"][713] = "as_movable"; // FX_VAT_BUBBLE
    lua["TYPE_MAP"][714] = "as_movable"; // FX_CRUSHINGELEVATOR_FILL
    lua["TYPE_MAP"][715] = "as_movable"; // FX_CRUSHINGELEVATOR_DECO
    lua["TYPE_MAP"][716] = "as_movable"; // FX_HUNDUN_LIMB_THIGH
    lua["TYPE_MAP"][717] = "as_movable"; // FX_HUNDUN_LIMB_CALF
    lua["TYPE_MAP"][718] = "as_movable"; // FX_HUNDUN_LIMB_FOOT
    lua["TYPE_MAP"][719] = "as_movable"; // FX_HUNDUN_EGG_CRACK
    lua["TYPE_MAP"][720] = "as_movable"; // FX_HUNDUN_NECK_PIECE
    lua["TYPE_MAP"][721] = "as_movable"; // FX_HUNDUN_WING
    lua["TYPE_MAP"][722] = "as_movable"; // FX_HUNDUN_EYELID
    lua["TYPE_MAP"][723] = "as_movable"; // FX_HUNDUN_EYEBALL
    lua["TYPE_MAP"][724] = "as_movable"; // FX_HUNDUN_EYE
    lua["TYPE_MAP"][725] = "as_movable"; // FX_PORTAL
    lua["TYPE_MAP"][726] = "as_movable"; // FX_MEGAJELLYFISH_CROWN
    lua["TYPE_MAP"][727] = "as_movable"; // FX_MEGAJELLYFISH_EYE
    lua["TYPE_MAP"][728] = "as_movable"; // FX_MEGAJELLYFISH_STAR
    lua["TYPE_MAP"][729] = "as_movable"; // FX_MEGAJELLYFISH_FLIPPER
    lua["TYPE_MAP"][730] = "as_movable"; // FX_MEGAJELLYFISH_BOTTOM
    lua["TYPE_MAP"][731] = "as_movable"; // FX_MEGAJELLYFISH_TAIL
    lua["TYPE_MAP"][732] = "as_movable"; // FX_MEGAJELLYFISH_TAIL_BG
    lua["TYPE_MAP"][733] = "as_movable"; // FX_ANUBIS_SPECIAL_SHOT_RETICULE
    lua["TYPE_MAP"][734] = "as_movable"; // FX_MECH_COLLAR
    lua["TYPE_MAP"][735] = "as_movable"; // FX_QUICKSAND_DUST
    lua["TYPE_MAP"][736] = "as_movable"; // FX_QUICKSAND_RUBBLE
    lua["TYPE_MAP"][737] = "as_movable"; // FX_SORCERESS_ATTACK
    lua["TYPE_MAP"][738] = "as_movable"; // FX_LAMASSU_ATTACK
    lua["TYPE_MAP"][739] = "as_movable"; // FX_CRITTERFIREFLY_LIGHT
    lua["TYPE_MAP"][740] = "as_movable"; // FX_AXOLOTL_HEAD_ENTERING_DOOR
    lua["TYPE_MAP"][741] = "as_movable"; // FX_BASECAMP_COUCH_ARM
    lua["TYPE_MAP"][742] = "as_movable"; // FX_EMPRESS
    lua["TYPE_MAP"][743] = "as_movable"; // FX_EGGSHIP_HOOK_CHAIN
    lua["TYPE_MAP"][744] = "as_movable"; // FX_MINIGAME_SHIP_DOOR
    lua["TYPE_MAP"][745] = "as_movable"; // FX_MINIGAME_SHIP_CENTERJETFLAME
    lua["TYPE_MAP"][746] = "as_movable"; // FX_MINIGAME_SHIP_JETFLAME
    lua["TYPE_MAP"][748] = "as_movable"; // FX_ANKH_ROTATINGSPARK
    lua["TYPE_MAP"][749] = "as_movable"; // FX_ANKH_FALLINGSPARK
    lua["TYPE_MAP"][750] = "as_movable"; // FX_ANKH_BACKGLOW
    lua["TYPE_MAP"][751] = "as_movable"; // FX_ANKH_FRONTGLOW
    lua["TYPE_MAP"][752] = "as_movable"; // FX_ANKH_LIGHTBEAM
    lua["TYPE_MAP"][753] = "as_movable"; // FX_ANKH_BROKENPIECE
    lua["TYPE_MAP"][897] = "as_mount";   // MOUNT_TURKEY
    lua["TYPE_MAP"][898] = "as_rockdog"; // MOUNT_ROCKDOG
    lua["TYPE_MAP"][899] = "as_axolotl"; // MOUNT_AXOLOTL
    lua["TYPE_MAP"][900] = "as_mech";    // MOUNT_MECH
    lua["TYPE_MAP"][901] = "as_qilin";   // MOUNT_QILIN
    lua["TYPE_MAP"][903] = "as_mount";   // MOUNT_BASECAMP_CHAIR
    lua["TYPE_MAP"][904] = "as_mount";   // MOUNT_BASECAMP_COUCH
    // lua["TYPE_MAP"][907] = "as_liquid";  // LIQUID_WATER (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][908] = "as_liquid";  // LIQUID_COARSE_WATER (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][909] = "as_entity";  // LIQUID_IMPOSTOR_LAKE (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][910] = "as_lava";  // LIQUID_LAVA (NOT IMPLEMENTED YET)
    // lua["TYPE_MAP"][911] = "as_lava";  // LIQUID_STAGNANT_LAVA (NOT IMPLEMENTED YET)
}
} // namespace NEntityCasting
