#include "entity_casting_lua.hpp"

#include <sol/sol.hpp> // for table_proxy, proxy_key_t, state, state_view
#include <tuple>       // for get
#include <type_traits> // for move

namespace NEntityCasting
{
void register_usertypes(sol::state& lua)
{
    lua.create_named_table("TYPE_MAP");

    // THIS LIST IS AUTO GENERATED
    // To recreate it, run the entity_casting.py script
    // It will dump the list to stdout, and overwrite docs/entities-hierarchy.md

    lua["TYPE_MAP"][1] = lua["Entity"]["as_floor"];                 // FLOOR_BORDERTILE
    lua["TYPE_MAP"][2] = lua["Entity"]["as_floor"];                 // FLOOR_BORDERTILE_METAL
    lua["TYPE_MAP"][3] = lua["Entity"]["as_floor"];                 // FLOOR_BORDERTILE_OCTOPUS
    lua["TYPE_MAP"][4] = lua["Entity"]["as_floor"];                 // FLOOR_GENERIC
    lua["TYPE_MAP"][5] = lua["Entity"]["as_floor"];                 // FLOOR_SURFACE
    lua["TYPE_MAP"][6] = lua["Entity"]["as_floor"];                 // FLOOR_SURFACE_HIDDEN
    lua["TYPE_MAP"][7] = lua["Entity"]["as_floor"];                 // FLOOR_BASECAMP_SINGLEBED
    lua["TYPE_MAP"][8] = lua["Entity"]["as_floor"];                 // FLOOR_BASECAMP_DININGTABLE
    lua["TYPE_MAP"][9] = lua["Entity"]["as_floor"];                 // FLOOR_BASECAMP_LONGTABLE
    lua["TYPE_MAP"][10] = lua["Entity"]["as_floor"];                // FLOOR_JUNGLE
    lua["TYPE_MAP"][11] = lua["Entity"]["as_floor"];                // FLOOR_TUNNEL_CURRENT
    lua["TYPE_MAP"][12] = lua["Entity"]["as_floor"];                // FLOOR_TUNNEL_NEXT
    lua["TYPE_MAP"][13] = lua["Entity"]["as_floor"];                // FLOOR_PLATFORM
    lua["TYPE_MAP"][14] = lua["Entity"]["as_floor"];                // FLOOR_PAGODA_PLATFORM
    lua["TYPE_MAP"][15] = lua["Entity"]["as_floor"];                // FLOOR_LADDER
    lua["TYPE_MAP"][16] = lua["Entity"]["as_floor"];                // FLOOR_LADDER_PLATFORM
    lua["TYPE_MAP"][17] = lua["Entity"]["as_floor"];                // FLOOR_VINE
    lua["TYPE_MAP"][18] = lua["Entity"]["as_floor"];                // FLOOR_VINE_TREE_TOP
    lua["TYPE_MAP"][19] = lua["Entity"]["as_floor"];                // FLOOR_GROWABLE_VINE
    lua["TYPE_MAP"][20] = lua["Entity"]["as_floor"];                // FLOOR_CLIMBING_POLE
    lua["TYPE_MAP"][21] = lua["Entity"]["as_floor"];                // FLOOR_GROWABLE_CLIMBING_POLE
    lua["TYPE_MAP"][22] = lua["Entity"]["as_door"];                 // FLOOR_DOOR_ENTRANCE
    lua["TYPE_MAP"][23] = lua["Entity"]["as_exitdoor"];             // FLOOR_DOOR_EXIT
    lua["TYPE_MAP"][24] = lua["Entity"]["as_mainexit"];             // FLOOR_DOOR_MAIN_EXIT
    lua["TYPE_MAP"][25] = lua["Entity"]["as_exitdoor"];             // FLOOR_DOOR_STARTING_EXIT
    lua["TYPE_MAP"][26] = lua["Entity"]["as_door"];                 // FLOOR_DOOR_LAYER
    lua["TYPE_MAP"][27] = lua["Entity"]["as_door"];                 // FLOOR_DOOR_LAYER_DROP_HELD
    lua["TYPE_MAP"][28] = lua["Entity"]["as_door"];                 // FLOOR_DOOR_GHISTSHOP
    lua["TYPE_MAP"][29] = lua["Entity"]["as_lockeddoor"];           // FLOOR_DOOR_LOCKED
    lua["TYPE_MAP"][30] = lua["Entity"]["as_lockeddoor"];           // FLOOR_DOOR_LOCKED_PEN
    lua["TYPE_MAP"][31] = lua["Entity"]["as_cityofgolddoor"];       // FLOOR_DOOR_COG
    lua["TYPE_MAP"][32] = lua["Entity"]["as_door"];                 // FLOOR_DOOR_MOAI_STATUE
    lua["TYPE_MAP"][33] = lua["Entity"]["as_eggshipdoors"];         // FLOOR_DOOR_EGGSHIP
    lua["TYPE_MAP"][34] = lua["Entity"]["as_eggshipdoor"];          // FLOOR_DOOR_EGGSHIP_ATREZZO
    lua["TYPE_MAP"][35] = lua["Entity"]["as_eggshipdoor"];          // FLOOR_DOOR_EGGSHIP_ROOM
    lua["TYPE_MAP"][36] = lua["Entity"]["as_decorateddoor"];        // FLOOR_DOOR_EGGPLANT_WORLD
    lua["TYPE_MAP"][37] = lua["Entity"]["as_floor"];                // FLOOR_DOOR_PLATFORM
    lua["TYPE_MAP"][38] = lua["Entity"]["as_floor"];                // FLOOR_SPIKES
    lua["TYPE_MAP"][39] = lua["Entity"]["as_floor"];                // FLOOR_SPIKES_UPSIDEDOWN
    lua["TYPE_MAP"][40] = lua["Entity"]["as_arrowtrap"];            // FLOOR_ARROW_TRAP
    lua["TYPE_MAP"][41] = lua["Entity"]["as_arrowtrap"];            // FLOOR_POISONED_ARROW_TRAP
    lua["TYPE_MAP"][42] = lua["Entity"]["as_totemtrap"];            // FLOOR_TOTEM_TRAP
    lua["TYPE_MAP"][43] = lua["Entity"]["as_junglespeartrap"];      // FLOOR_JUNGLE_SPEAR_TRAP
    lua["TYPE_MAP"][44] = lua["Entity"]["as_totemtrap"];            // FLOOR_LION_TRAP
    lua["TYPE_MAP"][45] = lua["Entity"]["as_lasertrap"];            // FLOOR_LASER_TRAP
    lua["TYPE_MAP"][46] = lua["Entity"]["as_sparktrap"];            // FLOOR_SPARK_TRAP
    lua["TYPE_MAP"][47] = lua["Entity"]["as_altar"];                // FLOOR_ALTAR
    lua["TYPE_MAP"][48] = lua["Entity"]["as_floor"];                // FLOOR_IDOL_BLOCK
    lua["TYPE_MAP"][49] = lua["Entity"]["as_floor"];                // FLOOR_IDOL_TRAP_CEILING
    lua["TYPE_MAP"][50] = lua["Entity"]["as_floor"];                // FLOOR_STORAGE
    lua["TYPE_MAP"][51] = lua["Entity"]["as_floor"];                // FLOOR_TREE_BASE
    lua["TYPE_MAP"][52] = lua["Entity"]["as_floor"];                // FLOOR_TREE_TRUNK
    lua["TYPE_MAP"][53] = lua["Entity"]["as_floor"];                // FLOOR_TREE_TOP
    lua["TYPE_MAP"][54] = lua["Entity"]["as_floor"];                // FLOOR_TREE_BRANCH
    lua["TYPE_MAP"][55] = lua["Entity"]["as_floor"];                // FLOOR_MUSHROOM_BASE
    lua["TYPE_MAP"][56] = lua["Entity"]["as_floor"];                // FLOOR_MUSHROOM_TRUNK
    lua["TYPE_MAP"][57] = lua["Entity"]["as_floor"];                // FLOOR_MUSHROOM_TOP
    lua["TYPE_MAP"][58] = lua["Entity"]["as_floor"];                // FLOOR_MUSHROOM_HAT_PLATFORM
    lua["TYPE_MAP"][59] = lua["Entity"]["as_floor"];                // FLOOR_THORN_VINE
    lua["TYPE_MAP"][60] = lua["Entity"]["as_spikeballtrap"];        // FLOOR_SPIKEBALL_CEILING
    lua["TYPE_MAP"][61] = lua["Entity"]["as_floor"];                // FLOOR_CHAINANDBLOCKS_CEILING
    lua["TYPE_MAP"][62] = lua["Entity"]["as_floor"];                // FLOOR_CHAINANDBLOCKS_CHAIN
    lua["TYPE_MAP"][63] = lua["Entity"]["as_floor"];                // FLOOR_CHAIN_CEILING
    lua["TYPE_MAP"][64] = lua["Entity"]["as_conveyorbelt"];         // FLOOR_CONVEYORBELT_LEFT
    lua["TYPE_MAP"][65] = lua["Entity"]["as_conveyorbelt"];         // FLOOR_CONVEYORBELT_RIGHT
    lua["TYPE_MAP"][66] = lua["Entity"]["as_generator"];            // FLOOR_FACTORY_GENERATOR
    lua["TYPE_MAP"][67] = lua["Entity"]["as_slidingwallceiling"];   // FLOOR_SLIDINGWALL_CEILING
    lua["TYPE_MAP"][68] = lua["Entity"]["as_quicksand"];            // FLOOR_QUICKSAND
    lua["TYPE_MAP"][69] = lua["Entity"]["as_floor"];                // FLOOR_EXCALIBUR_STONE
    lua["TYPE_MAP"][70] = lua["Entity"]["as_floor"];                // FLOOR_DUSTWALL
    lua["TYPE_MAP"][71] = lua["Entity"]["as_altar"];                // FLOOR_DUAT_ALTAR
    lua["TYPE_MAP"][72] = lua["Entity"]["as_floor"];                // FLOOR_ICE
    lua["TYPE_MAP"][73] = lua["Entity"]["as_floor"];                // FLOOR_SPRING_TRAP
    lua["TYPE_MAP"][74] = lua["Entity"]["as_altar"];                // FLOOR_EGGPLANT_ALTAR
    lua["TYPE_MAP"][75] = lua["Entity"]["as_floor"];                // FLOOR_MOAI_PLATFORM
    lua["TYPE_MAP"][76] = lua["Entity"]["as_generator"];            // FLOOR_SHOPKEEPER_GENERATOR
    lua["TYPE_MAP"][77] = lua["Entity"]["as_generator"];            // FLOOR_SUNCHALLENGE_GENERATOR
    lua["TYPE_MAP"][78] = lua["Entity"]["as_pipe"];                 // FLOOR_PIPE
    lua["TYPE_MAP"][79] = lua["Entity"]["as_bigspeartrap"];         // FLOOR_BIGSPEAR_TRAP
    lua["TYPE_MAP"][80] = lua["Entity"]["as_stickytrap"];           // FLOOR_STICKYTRAP_CEILING
    lua["TYPE_MAP"][81] = lua["Entity"]["as_motherstatue"];         // FLOOR_MOTHER_STATUE
    lua["TYPE_MAP"][82] = lua["Entity"]["as_floor"];                // FLOOR_MOTHER_STATUE_PLATFORM
    lua["TYPE_MAP"][83] = lua["Entity"]["as_floor"];                // FLOOR_GIANTFROG_PLATFORM
    lua["TYPE_MAP"][84] = lua["Entity"]["as_teleportingborder"];    // FLOOR_TELEPORTINGBORDER
    lua["TYPE_MAP"][85] = lua["Entity"]["as_forcefield"];           // FLOOR_FORCEFIELD
    lua["TYPE_MAP"][86] = lua["Entity"]["as_forcefield"];           // FLOOR_DICE_FORCEFIELD
    lua["TYPE_MAP"][87] = lua["Entity"]["as_forcefield"];           // FLOOR_CHALLENGE_ENTRANCE
    lua["TYPE_MAP"][88] = lua["Entity"]["as_forcefield"];           // FLOOR_CHALLENGE_WAITROOM
    lua["TYPE_MAP"][89] = lua["Entity"]["as_timedforcefield"];      // FLOOR_TIMED_FORCEFIELD
    lua["TYPE_MAP"][90] = lua["Entity"]["as_floor"];                // FLOOR_FORCEFIELD_TOP
    lua["TYPE_MAP"][91] = lua["Entity"]["as_horizontalforcefield"]; // FLOOR_HORIZONTAL_FORCEFIELD
    lua["TYPE_MAP"][92] = lua["Entity"]["as_floor"];                // FLOOR_HORIZONTAL_FORCEFIELD_TOP
    lua["TYPE_MAP"][93] = lua["Entity"]["as_floor"];                // FLOOR_PEN
    lua["TYPE_MAP"][94] = lua["Entity"]["as_floor"];                // FLOOR_TOMB
    lua["TYPE_MAP"][95] = lua["Entity"]["as_floor"];                // FLOOR_YAMA_PLATFORM
    lua["TYPE_MAP"][96] = lua["Entity"]["as_floor"];                // FLOOR_EMPRESS_GRAVE
    lua["TYPE_MAP"][97] = lua["Entity"]["as_floor"];                // FLOOR_PALACE_TABLE_PLATFORM
    lua["TYPE_MAP"][98] = lua["Entity"]["as_floor"];                // FLOOR_PALACE_TRAY_PLATFORM
    lua["TYPE_MAP"][99] = lua["Entity"]["as_floor"];                // FLOOR_PALACE_CHANDELIER_PLATFORM
    lua["TYPE_MAP"][100] = lua["Entity"]["as_floor"];               // FLOOR_PALACE_BOOKCASE_PLATFORM
    lua["TYPE_MAP"][101] = lua["Entity"]["as_tentaclebottom"];      // FLOOR_TENTACLE_BOTTOM
    lua["TYPE_MAP"][102] = lua["Entity"]["as_poledeco"];            // FLOORSTYLED_MINEWOOD
    lua["TYPE_MAP"][103] = lua["Entity"]["as_floor"];               // FLOORSTYLED_STONE
    lua["TYPE_MAP"][104] = lua["Entity"]["as_floor"];               // FLOORSTYLED_TEMPLE
    lua["TYPE_MAP"][105] = lua["Entity"]["as_poledeco"];            // FLOORSTYLED_PAGODA
    lua["TYPE_MAP"][106] = lua["Entity"]["as_floor"];               // FLOORSTYLED_BABYLON
    lua["TYPE_MAP"][107] = lua["Entity"]["as_floor"];               // FLOORSTYLED_SUNKEN
    lua["TYPE_MAP"][108] = lua["Entity"]["as_floor"];               // FLOORSTYLED_BEEHIVE
    lua["TYPE_MAP"][109] = lua["Entity"]["as_floor"];               // FLOORSTYLED_VLAD
    lua["TYPE_MAP"][110] = lua["Entity"]["as_floor"];               // FLOORSTYLED_COG
    lua["TYPE_MAP"][111] = lua["Entity"]["as_floor"];               // FLOORSTYLED_MOTHERSHIP
    lua["TYPE_MAP"][112] = lua["Entity"]["as_floor"];               // FLOORSTYLED_DUAT
    lua["TYPE_MAP"][113] = lua["Entity"]["as_floor"];               // FLOORSTYLED_PALACE
    lua["TYPE_MAP"][114] = lua["Entity"]["as_floor"];               // FLOORSTYLED_GUTS
    // lua["TYPE_MAP"][115] = lua["Entity"]["as_entity"];  // DECORATION_BORDER (plain entity)
    // lua["TYPE_MAP"][116] = lua["Entity"]["as_entity"];  // DECORATION_GENERIC (plain entity)
    // lua["TYPE_MAP"][117] = lua["Entity"]["as_entity"];  // DECORATION_SURFACE (plain entity)
    // lua["TYPE_MAP"][118] = lua["Entity"]["as_entity"];  // DECORATION_SURFACE_COVER (plain entity)
    // lua["TYPE_MAP"][119] = lua["Entity"]["as_entity"];  // DECORATION_JUNGLE (plain entity)
    // lua["TYPE_MAP"][120] = lua["Entity"]["as_entity"];  // DECORATION_MINEWOOD (plain entity)
    // lua["TYPE_MAP"][121] = lua["Entity"]["as_entity"];  // DECORATION_BONEBLOCK (plain entity)
    // lua["TYPE_MAP"][122] = lua["Entity"]["as_entity"];  // DECORATION_BUSHBLOCK (plain entity)
    // lua["TYPE_MAP"][123] = lua["Entity"]["as_entity"];  // DECORATION_STONE (plain entity)
    // lua["TYPE_MAP"][124] = lua["Entity"]["as_entity"];  // DECORATION_TEMPLE (plain entity)
    // lua["TYPE_MAP"][125] = lua["Entity"]["as_entity"];  // DECORATION_PAGODA (plain entity)
    // lua["TYPE_MAP"][126] = lua["Entity"]["as_entity"];  // DECORATION_SUNKEN (plain entity)
    // lua["TYPE_MAP"][127] = lua["Entity"]["as_entity"];  // DECORATION_BABYLON (plain entity)
    // lua["TYPE_MAP"][128] = lua["Entity"]["as_entity"];  // DECORATION_BG_TRANSITIONCOVER (plain entity)
    // lua["TYPE_MAP"][129] = lua["Entity"]["as_entity"];  // DECORATION_MINEWOOD_POLE (plain entity)
    // lua["TYPE_MAP"][130] = lua["Entity"]["as_entity"];  // DECORATION_PAGODA_POLE (plain entity)
    lua["TYPE_MAP"][131] = lua["Entity"]["as_crossbeam"]; // DECORATION_CROSS_BEAM
    // lua["TYPE_MAP"][132] = lua["Entity"]["as_entity"];  // DECORATION_HANGING_HIDE (plain entity)
    // lua["TYPE_MAP"][133] = lua["Entity"]["as_entity"];  // DECORATION_HANGING_SEAWEED (plain entity)
    // lua["TYPE_MAP"][134] = lua["Entity"]["as_entity"];  // DECORATION_HANGING_BANNER (plain entity)
    // lua["TYPE_MAP"][135] = lua["Entity"]["as_entity"];  // DECORATION_HANGING_WIRES (plain entity)
    // lua["TYPE_MAP"][136] = lua["Entity"]["as_entity"];  // DECORATION_DWELLINGBUSH (plain entity)
    // lua["TYPE_MAP"][137] = lua["Entity"]["as_entity"];  // DECORATION_JUNGLEBUSH (plain entity)
    // lua["TYPE_MAP"][138] = lua["Entity"]["as_entity"];  // DECORATION_BABYLONBUSH (plain entity)
    // lua["TYPE_MAP"][139] = lua["Entity"]["as_entity"];  // DECORATION_TIDEPOOLBUSH (plain entity)
    // lua["TYPE_MAP"][140] = lua["Entity"]["as_entity"];  // DECORATION_JUNGLE_FLOWER (plain entity)
    // lua["TYPE_MAP"][141] = lua["Entity"]["as_entity"];  // DECORATION_BABYLON_FLOWER (plain entity)
    // lua["TYPE_MAP"][142] = lua["Entity"]["as_entity"];  // DECORATION_TIDEPOOL_CORAL (plain entity)
    // lua["TYPE_MAP"][143] = lua["Entity"]["as_entity"];  // DECORATION_JUNGLE_HANGING_FLOWER (plain entity)
    // lua["TYPE_MAP"][144] = lua["Entity"]["as_entity"];  // DECORATION_BABYLON_HANGING_FLOWER (plain entity)
    // lua["TYPE_MAP"][145] = lua["Entity"]["as_entity"];  // DECORATION_BABYLON_NEON_SIGN (plain entity)
    // lua["TYPE_MAP"][146] = lua["Entity"]["as_entity"];  // DECORATION_BRANCH (plain entity)
    // lua["TYPE_MAP"][147] = lua["Entity"]["as_entity"];  // DECORATION_SPIKES_BLOOD (plain entity)
    // lua["TYPE_MAP"][148] = lua["Entity"]["as_entity"];  // DECORATION_SHOPFORE (plain entity)
    // lua["TYPE_MAP"][149] = lua["Entity"]["as_entity"];  // DECORATION_SHOPSIGN (plain entity)
    // lua["TYPE_MAP"][150] = lua["Entity"]["as_entity"];  // DECORATION_SHOPSIGNICON (plain entity)
    // lua["TYPE_MAP"][151] = lua["Entity"]["as_entity"];  // DECORATION_BASECAMPSIGN (plain entity)
    // lua["TYPE_MAP"][152] = lua["Entity"]["as_entity"];  // DECORATION_BASECAMPDOGSIGN (plain entity)
    // lua["TYPE_MAP"][153] = lua["Entity"]["as_entity"];  // DECORATION_TREE (plain entity)
    // lua["TYPE_MAP"][154] = lua["Entity"]["as_entity"];  // DECORATION_TREETRUNK_CLIMBINGHINT (plain entity)
    // lua["TYPE_MAP"][155] = lua["Entity"]["as_entity"];  // DECORATION_TREETRUNK_TOPFRONT (plain entity)
    // lua["TYPE_MAP"][156] = lua["Entity"]["as_entity"];  // DECORATION_TREETRUNK_TOPBACK (plain entity)
    // lua["TYPE_MAP"][157] = lua["Entity"]["as_entity"];  // DECORATION_TREETRUNK_BROKEN (plain entity)
    // lua["TYPE_MAP"][158] = lua["Entity"]["as_entity"];  // DECORATION_TREE_VINE_TOP (plain entity)
    // lua["TYPE_MAP"][159] = lua["Entity"]["as_entity"];  // DECORATION_TREE_VINE (plain entity)
    // lua["TYPE_MAP"][160] = lua["Entity"]["as_entity"];  // DECORATION_MUSHROOM_HAT (plain entity)
    // lua["TYPE_MAP"][161] = lua["Entity"]["as_entity"];  // DECORATION_THORN_VINE (plain entity)
    // lua["TYPE_MAP"][162] = lua["Entity"]["as_entity"];  // DECORATION_BEEHIVE (plain entity)
    lua["TYPE_MAP"][163] = lua["Entity"]["as_movable"]; // DECORATION_CHAINANDBLOCKS_CHAINDECORATION
    // lua["TYPE_MAP"][164] = lua["Entity"]["as_entity"];  // DECORATION_CONVEYORBELT_RAILING (plain entity)
    // lua["TYPE_MAP"][165] = lua["Entity"]["as_entity"];  // DECORATION_VLAD (plain entity)
    // lua["TYPE_MAP"][166] = lua["Entity"]["as_entity"];  // DECORATION_KELP (plain entity)
    lua["TYPE_MAP"][167] = lua["Entity"]["as_movable"]; // DECORATION_SLIDINGWALL_CHAINDECORATION
    // lua["TYPE_MAP"][168] = lua["Entity"]["as_entity"];  // DECORATION_TEMPLE_SAND (plain entity)
    // lua["TYPE_MAP"][169] = lua["Entity"]["as_entity"];  // DECORATION_COG (plain entity)
    // lua["TYPE_MAP"][170] = lua["Entity"]["as_entity"];  // DECORATION_MOTHERSHIP (plain entity)
    // lua["TYPE_MAP"][171] = lua["Entity"]["as_entity"];  // DECORATION_DUAT (plain entity)
    // lua["TYPE_MAP"][172] = lua["Entity"]["as_entity"];  // DECORATION_DUAT_SAND (plain entity)
    // lua["TYPE_MAP"][173] = lua["Entity"]["as_entity"];  // DECORATION_DUAT_DARKSAND (plain entity)
    lua["TYPE_MAP"][174] = lua["Entity"]["as_destructiblebg"]; // DECORATION_DUAT_DESTRUCTIBLE_BG
    // lua["TYPE_MAP"][175] = lua["Entity"]["as_entity"];  // DECORATION_PALACE (plain entity)
    lua["TYPE_MAP"][176] = lua["Entity"]["as_palacesign"]; // DECORATION_PALACE_SIGN
    // lua["TYPE_MAP"][177] = lua["Entity"]["as_entity"];  // DECORATION_PALACE_CHANDELIER (plain entity)
    // lua["TYPE_MAP"][178] = lua["Entity"]["as_entity"];  // DECORATION_PALACE_PORTRAIT (plain entity)
    // lua["TYPE_MAP"][179] = lua["Entity"]["as_entity"];  // DECORATION_GUTS (plain entity)
    // lua["TYPE_MAP"][180] = lua["Entity"]["as_entity"];  // DECORATION_EGGPLANT_ALTAR (plain entity)
    // lua["TYPE_MAP"][181] = lua["Entity"]["as_entity"];  // DECORATION_MOTHER_STATUE_HAND (plain entity)
    // lua["TYPE_MAP"][182] = lua["Entity"]["as_entity"];  // DECORATION_PIPE (plain entity)
    // lua["TYPE_MAP"][183] = lua["Entity"]["as_entity"];  // DECORATION_SUNKEN_BRIDGE (plain entity)
    // lua["TYPE_MAP"][184] = lua["Entity"]["as_entity"];  // DECORATION_TOMB (plain entity)
    // lua["TYPE_MAP"][185] = lua["Entity"]["as_entity"];  // DECORATION_LARGETOMB (plain entity)
    lua["TYPE_MAP"][186] = lua["Entity"]["as_decoregeneratingblock"]; // DECORATION_REGENERATING_SMALL_BLOCK
    lua["TYPE_MAP"][187] = lua["Entity"]["as_decoregeneratingblock"]; // DECORATION_REGENERATING_BORDER
    // lua["TYPE_MAP"][188] = lua["Entity"]["as_entity"];  // DECORATION_SKULLDROP_TRAP (plain entity)
    // lua["TYPE_MAP"][189] = lua["Entity"]["as_entity"];  // DECORATION_POTOFGOLD_RAINBOW (plain entity)
    lua["TYPE_MAP"][190] = lua["Entity"]["as_floor"];                  // EMBED_GOLD
    lua["TYPE_MAP"][191] = lua["Entity"]["as_floor"];                  // EMBED_GOLD_BIG
    lua["TYPE_MAP"][194] = lua["Entity"]["as_player"];                 // CHAR_ANA_SPELUNKY
    lua["TYPE_MAP"][195] = lua["Entity"]["as_player"];                 // CHAR_MARGARET_TUNNEL
    lua["TYPE_MAP"][196] = lua["Entity"]["as_player"];                 // CHAR_COLIN_NORTHWARD
    lua["TYPE_MAP"][197] = lua["Entity"]["as_player"];                 // CHAR_ROFFY_D_SLOTH
    lua["TYPE_MAP"][198] = lua["Entity"]["as_player"];                 // CHAR_BANDA
    lua["TYPE_MAP"][199] = lua["Entity"]["as_player"];                 // CHAR_GREEN_GIRL
    lua["TYPE_MAP"][200] = lua["Entity"]["as_player"];                 // CHAR_AMAZON
    lua["TYPE_MAP"][201] = lua["Entity"]["as_player"];                 // CHAR_LISE_SYSTEM
    lua["TYPE_MAP"][202] = lua["Entity"]["as_player"];                 // CHAR_COCO_VON_DIAMONDS
    lua["TYPE_MAP"][203] = lua["Entity"]["as_player"];                 // CHAR_MANFRED_TUNNEL
    lua["TYPE_MAP"][204] = lua["Entity"]["as_player"];                 // CHAR_OTAKU
    lua["TYPE_MAP"][205] = lua["Entity"]["as_player"];                 // CHAR_TINA_FLAN
    lua["TYPE_MAP"][206] = lua["Entity"]["as_player"];                 // CHAR_VALERIE_CRUMP
    lua["TYPE_MAP"][207] = lua["Entity"]["as_player"];                 // CHAR_AU
    lua["TYPE_MAP"][208] = lua["Entity"]["as_player"];                 // CHAR_DEMI_VON_DIAMONDS
    lua["TYPE_MAP"][209] = lua["Entity"]["as_player"];                 // CHAR_PILOT
    lua["TYPE_MAP"][210] = lua["Entity"]["as_player"];                 // CHAR_PRINCESS_AIRYN
    lua["TYPE_MAP"][211] = lua["Entity"]["as_player"];                 // CHAR_DIRK_YAMAOKA
    lua["TYPE_MAP"][212] = lua["Entity"]["as_player"];                 // CHAR_GUY_SPELUNKY
    lua["TYPE_MAP"][213] = lua["Entity"]["as_player"];                 // CHAR_CLASSIC_GUY
    lua["TYPE_MAP"][215] = lua["Entity"]["as_player"];                 // CHAR_HIREDHAND
    lua["TYPE_MAP"][216] = lua["Entity"]["as_player"];                 // CHAR_EGGPLANT_CHILD
    lua["TYPE_MAP"][219] = lua["Entity"]["as_pet"];                    // MONS_PET_TUTORIAL
    lua["TYPE_MAP"][220] = lua["Entity"]["as_monster"];                // MONS_SNAKE
    lua["TYPE_MAP"][221] = lua["Entity"]["as_spider"];                 // MONS_SPIDER
    lua["TYPE_MAP"][222] = lua["Entity"]["as_hangspider"];             // MONS_HANGSPIDER
    lua["TYPE_MAP"][223] = lua["Entity"]["as_spider"];                 // MONS_GIANTSPIDER
    lua["TYPE_MAP"][224] = lua["Entity"]["as_bat"];                    // MONS_BAT
    lua["TYPE_MAP"][225] = lua["Entity"]["as_caveman"];                // MONS_CAVEMAN
    lua["TYPE_MAP"][226] = lua["Entity"]["as_cavemanshopkeeper"];      // MONS_CAVEMAN_SHOPKEEPER
    lua["TYPE_MAP"][227] = lua["Entity"]["as_skeleton"];               // MONS_SKELETON
    lua["TYPE_MAP"][228] = lua["Entity"]["as_skeleton"];               // MONS_REDSKELETON
    lua["TYPE_MAP"][229] = lua["Entity"]["as_scorpion"];               // MONS_SCORPION
    lua["TYPE_MAP"][230] = lua["Entity"]["as_hornedlizard"];           // MONS_HORNEDLIZARD
    lua["TYPE_MAP"][231] = lua["Entity"]["as_mole"];                   // MONS_MOLE
    lua["TYPE_MAP"][232] = lua["Entity"]["as_quillback"];              // MONS_CAVEMAN_BOSS
    lua["TYPE_MAP"][233] = lua["Entity"]["as_mantrap"];                // MONS_MANTRAP
    lua["TYPE_MAP"][234] = lua["Entity"]["as_walkingmonster"];         // MONS_TIKIMAN
    lua["TYPE_MAP"][235] = lua["Entity"]["as_witchdoctor"];            // MONS_WITCHDOCTOR
    lua["TYPE_MAP"][236] = lua["Entity"]["as_witchdoctorskull"];       // MONS_WITCHDOCTORSKULL
    lua["TYPE_MAP"][237] = lua["Entity"]["as_mosquito"];               // MONS_MOSQUITO
    lua["TYPE_MAP"][238] = lua["Entity"]["as_monkey"];                 // MONS_MONKEY
    lua["TYPE_MAP"][239] = lua["Entity"]["as_magmaman"];               // MONS_MAGMAMAN
    lua["TYPE_MAP"][240] = lua["Entity"]["as_robot"];                  // MONS_ROBOT
    lua["TYPE_MAP"][241] = lua["Entity"]["as_firebug"];                // MONS_FIREBUG
    lua["TYPE_MAP"][242] = lua["Entity"]["as_firebugunchained"];       // MONS_FIREBUG_UNCHAINED
    lua["TYPE_MAP"][243] = lua["Entity"]["as_imp"];                    // MONS_IMP
    lua["TYPE_MAP"][244] = lua["Entity"]["as_lavamander"];             // MONS_LAVAMANDER
    lua["TYPE_MAP"][245] = lua["Entity"]["as_vampire"];                // MONS_VAMPIRE
    lua["TYPE_MAP"][246] = lua["Entity"]["as_vlad"];                   // MONS_VLAD
    lua["TYPE_MAP"][247] = lua["Entity"]["as_crocman"];                // MONS_CROCMAN
    lua["TYPE_MAP"][248] = lua["Entity"]["as_cobra"];                  // MONS_COBRA
    lua["TYPE_MAP"][249] = lua["Entity"]["as_mummy"];                  // MONS_MUMMY
    lua["TYPE_MAP"][250] = lua["Entity"]["as_sorceress"];              // MONS_SORCERESS
    lua["TYPE_MAP"][251] = lua["Entity"]["as_catmummy"];               // MONS_CATMUMMY
    lua["TYPE_MAP"][252] = lua["Entity"]["as_necromancer"];            // MONS_NECROMANCER
    lua["TYPE_MAP"][253] = lua["Entity"]["as_anubis"];                 // MONS_ANUBIS
    lua["TYPE_MAP"][254] = lua["Entity"]["as_apephead"];               // MONS_APEP_HEAD
    lua["TYPE_MAP"][255] = lua["Entity"]["as_apeppart"];               // MONS_APEP_BODY
    lua["TYPE_MAP"][256] = lua["Entity"]["as_apeppart"];               // MONS_APEP_TAIL
    lua["TYPE_MAP"][257] = lua["Entity"]["as_osirishead"];             // MONS_OSIRIS_HEAD
    lua["TYPE_MAP"][258] = lua["Entity"]["as_osirishand"];             // MONS_OSIRIS_HAND
    lua["TYPE_MAP"][259] = lua["Entity"]["as_anubis"];                 // MONS_ANUBIS2
    lua["TYPE_MAP"][260] = lua["Entity"]["as_jiangshi"];               // MONS_JIANGSHI
    lua["TYPE_MAP"][261] = lua["Entity"]["as_jiangshi"];               // MONS_FEMALE_JIANGSHI
    lua["TYPE_MAP"][262] = lua["Entity"]["as_fish"];                   // MONS_FISH
    lua["TYPE_MAP"][263] = lua["Entity"]["as_octopus"];                // MONS_OCTOPUS
    lua["TYPE_MAP"][264] = lua["Entity"]["as_hermitcrab"];             // MONS_HERMITCRAB
    lua["TYPE_MAP"][265] = lua["Entity"]["as_giantfish"];              // MONS_GIANTFISH
    lua["TYPE_MAP"][266] = lua["Entity"]["as_ufo"];                    // MONS_UFO
    lua["TYPE_MAP"][267] = lua["Entity"]["as_alien"];                  // MONS_ALIEN
    lua["TYPE_MAP"][268] = lua["Entity"]["as_walkingmonster"];         // MONS_YETI
    lua["TYPE_MAP"][269] = lua["Entity"]["as_yetiking"];               // MONS_YETIKING
    lua["TYPE_MAP"][270] = lua["Entity"]["as_yetiqueen"];              // MONS_YETIQUEEN
    lua["TYPE_MAP"][271] = lua["Entity"]["as_lahamu"];                 // MONS_ALIENQUEEN
    lua["TYPE_MAP"][272] = lua["Entity"]["as_protoshopkeeper"];        // MONS_PROTOSHOPKEEPER
    lua["TYPE_MAP"][273] = lua["Entity"]["as_npc"];                    // MONS_SHOPKEEPERCLONE
    lua["TYPE_MAP"][274] = lua["Entity"]["as_lamassu"];                // MONS_LAMASSU
    lua["TYPE_MAP"][275] = lua["Entity"]["as_olmite"];                 // MONS_OLMITE_HELMET
    lua["TYPE_MAP"][276] = lua["Entity"]["as_olmite"];                 // MONS_OLMITE_BODYARMORED
    lua["TYPE_MAP"][277] = lua["Entity"]["as_olmite"];                 // MONS_OLMITE_NAKED
    lua["TYPE_MAP"][278] = lua["Entity"]["as_bee"];                    // MONS_BEE
    lua["TYPE_MAP"][279] = lua["Entity"]["as_bee"];                    // MONS_QUEENBEE
    lua["TYPE_MAP"][280] = lua["Entity"]["as_ammit"];                  // MONS_AMMIT
    lua["TYPE_MAP"][281] = lua["Entity"]["as_kingu"];                  // MONS_KINGU
    lua["TYPE_MAP"][282] = lua["Entity"]["as_tiamat"];                 // MONS_TIAMAT
    lua["TYPE_MAP"][283] = lua["Entity"]["as_frog"];                   // MONS_FROG
    lua["TYPE_MAP"][284] = lua["Entity"]["as_firefrog"];               // MONS_FIREFROG
    lua["TYPE_MAP"][285] = lua["Entity"]["as_giantfrog"];              // MONS_GIANTFROG
    lua["TYPE_MAP"][286] = lua["Entity"]["as_grub"];                   // MONS_GRUB
    lua["TYPE_MAP"][287] = lua["Entity"]["as_tadpole"];                // MONS_TADPOLE
    lua["TYPE_MAP"][288] = lua["Entity"]["as_giantfly"];               // MONS_GIANTFLY
    lua["TYPE_MAP"][289] = lua["Entity"]["as_jumpdog"];                // MONS_JUMPDOG
    lua["TYPE_MAP"][290] = lua["Entity"]["as_eggplantminister"];       // MONS_EGGPLANT_MINISTER
    lua["TYPE_MAP"][291] = lua["Entity"]["as_yama"];                   // MONS_YAMA
    lua["TYPE_MAP"][292] = lua["Entity"]["as_hundun"];                 // MONS_HUNDUN
    lua["TYPE_MAP"][293] = lua["Entity"]["as_hundunhead"];             // MONS_HUNDUN_BIRDHEAD
    lua["TYPE_MAP"][294] = lua["Entity"]["as_hundunhead"];             // MONS_HUNDUN_SNAKEHEAD
    lua["TYPE_MAP"][295] = lua["Entity"]["as_scarab"];                 // MONS_SCARAB
    lua["TYPE_MAP"][296] = lua["Entity"]["as_shopkeeper"];             // MONS_SHOPKEEPER
    lua["TYPE_MAP"][297] = lua["Entity"]["as_tun"];                    // MONS_MERCHANT
    lua["TYPE_MAP"][298] = lua["Entity"]["as_yang"];                   // MONS_YANG
    lua["TYPE_MAP"][299] = lua["Entity"]["as_terra"];                  // MONS_MARLA_TUNNEL
    lua["TYPE_MAP"][300] = lua["Entity"]["as_forestsister"];           // MONS_SISTER_PARSLEY
    lua["TYPE_MAP"][301] = lua["Entity"]["as_forestsister"];           // MONS_SISTER_PARSNIP
    lua["TYPE_MAP"][302] = lua["Entity"]["as_forestsister"];           // MONS_SISTER_PARMESAN
    lua["TYPE_MAP"][303] = lua["Entity"]["as_vanhorsing"];             // MONS_OLD_HUNTER
    lua["TYPE_MAP"][304] = lua["Entity"]["as_npc"];                    // MONS_THIEF
    lua["TYPE_MAP"][305] = lua["Entity"]["as_roomowner"];              // MONS_MADAMETUSK
    lua["TYPE_MAP"][306] = lua["Entity"]["as_bodyguard"];              // MONS_BODYGUARD
    lua["TYPE_MAP"][307] = lua["Entity"]["as_beg"];                    // MONS_HUNDUNS_SERVANT
    lua["TYPE_MAP"][308] = lua["Entity"]["as_waddler"];                // MONS_STORAGEGUY
    lua["TYPE_MAP"][309] = lua["Entity"]["as_goldmonkey"];             // MONS_GOLDMONKEY
    lua["TYPE_MAP"][310] = lua["Entity"]["as_leprechaun"];             // MONS_LEPRECHAUN
    lua["TYPE_MAP"][311] = lua["Entity"]["as_crabman"];                // MONS_CRABMAN
    lua["TYPE_MAP"][312] = lua["Entity"]["as_megajellyfish"];          // MONS_MEGAJELLYFISH
    lua["TYPE_MAP"][313] = lua["Entity"]["as_megajellyfish"];          // MONS_MEGAJELLYFISH_BACKGROUND
    lua["TYPE_MAP"][314] = lua["Entity"]["as_ghist"];                  // MONS_GHIST
    lua["TYPE_MAP"][315] = lua["Entity"]["as_ghist"];                  // MONS_GHIST_SHOPKEEPER
    lua["TYPE_MAP"][317] = lua["Entity"]["as_ghost"];                  // MONS_GHOST
    lua["TYPE_MAP"][318] = lua["Entity"]["as_ghost"];                  // MONS_GHOST_MEDIUM_SAD
    lua["TYPE_MAP"][319] = lua["Entity"]["as_ghost"];                  // MONS_GHOST_MEDIUM_HAPPY
    lua["TYPE_MAP"][320] = lua["Entity"]["as_ghost"];                  // MONS_GHOST_SMALL_ANGRY
    lua["TYPE_MAP"][321] = lua["Entity"]["as_ghost"];                  // MONS_GHOST_SMALL_SAD
    lua["TYPE_MAP"][322] = lua["Entity"]["as_ghost"];                  // MONS_GHOST_SMALL_SURPRISED
    lua["TYPE_MAP"][323] = lua["Entity"]["as_ghost"];                  // MONS_GHOST_SMALL_HAPPY
    lua["TYPE_MAP"][326] = lua["Entity"]["as_pet"];                    // MONS_PET_DOG
    lua["TYPE_MAP"][327] = lua["Entity"]["as_pet"];                    // MONS_PET_CAT
    lua["TYPE_MAP"][328] = lua["Entity"]["as_pet"];                    // MONS_PET_HAMSTER
    lua["TYPE_MAP"][331] = lua["Entity"]["as_critterbeetle"];          // MONS_CRITTERDUNGBEETLE
    lua["TYPE_MAP"][332] = lua["Entity"]["as_critterbutterfly"];       // MONS_CRITTERBUTTERFLY
    lua["TYPE_MAP"][333] = lua["Entity"]["as_crittersnail"];           // MONS_CRITTERSNAIL
    lua["TYPE_MAP"][334] = lua["Entity"]["as_critterfish"];            // MONS_CRITTERFISH
    lua["TYPE_MAP"][335] = lua["Entity"]["as_critter"];                // MONS_CRITTERANCHOVY
    lua["TYPE_MAP"][336] = lua["Entity"]["as_crittercrab"];            // MONS_CRITTERCRAB
    lua["TYPE_MAP"][337] = lua["Entity"]["as_critterlocust"];          // MONS_CRITTERLOCUST
    lua["TYPE_MAP"][338] = lua["Entity"]["as_critterpenguin"];         // MONS_CRITTERPENGUIN
    lua["TYPE_MAP"][339] = lua["Entity"]["as_critterfirefly"];         // MONS_CRITTERFIREFLY
    lua["TYPE_MAP"][340] = lua["Entity"]["as_critterdrone"];           // MONS_CRITTERDRONE
    lua["TYPE_MAP"][341] = lua["Entity"]["as_critterslime"];           // MONS_CRITTERSLIME
    lua["TYPE_MAP"][345] = lua["Entity"]["as_movable"];                // ITEM_WHIP
    lua["TYPE_MAP"][346] = lua["Entity"]["as_flamesize"];              // ITEM_WHIP_FLAME
    lua["TYPE_MAP"][347] = lua["Entity"]["as_bomb"];                   // ITEM_BOMB
    lua["TYPE_MAP"][348] = lua["Entity"]["as_bomb"];                   // ITEM_PASTEBOMB
    lua["TYPE_MAP"][349] = lua["Entity"]["as_movable"];                // ITEM_ROPE
    lua["TYPE_MAP"][350] = lua["Entity"]["as_climbablerope"];          // ITEM_CLIMBABLE_ROPE
    lua["TYPE_MAP"][351] = lua["Entity"]["as_climbablerope"];          // ITEM_UNROLLED_ROPE
    lua["TYPE_MAP"][352] = lua["Entity"]["as_movable"];                // ITEM_BLOOD
    lua["TYPE_MAP"][353] = lua["Entity"]["as_olmecship"];              // ITEM_EGGSHIP
    lua["TYPE_MAP"][354] = lua["Entity"]["as_olmecship"];              // ITEM_PARENTSSHIP
    lua["TYPE_MAP"][355] = lua["Entity"]["as_olmecship"];              // ITEM_OLMECSHIP
    lua["TYPE_MAP"][356] = lua["Entity"]["as_idol"];                   // ITEM_IDOL
    lua["TYPE_MAP"][357] = lua["Entity"]["as_idol"];                   // ITEM_MADAMETUSK_IDOL
    lua["TYPE_MAP"][358] = lua["Entity"]["as_movable"];                // ITEM_MADAMETUSK_IDOLNOTE
    lua["TYPE_MAP"][359] = lua["Entity"]["as_movable"];                // ITEM_HOLDTHEIDOL
    lua["TYPE_MAP"][360] = lua["Entity"]["as_spear"];                  // ITEM_TOTEM_SPEAR
    lua["TYPE_MAP"][361] = lua["Entity"]["as_junglespearcosmetic"];    // ITEM_JUNGLE_SPEAR_COSMETIC
    lua["TYPE_MAP"][362] = lua["Entity"]["as_movable"];                // ITEM_JUNGLE_SPEAR_DAMAGING
    lua["TYPE_MAP"][363] = lua["Entity"]["as_spear"];                  // ITEM_LION_SPEAR
    lua["TYPE_MAP"][364] = lua["Entity"]["as_spear"];                  // ITEM_BIG_SPEAR
    lua["TYPE_MAP"][365] = lua["Entity"]["as_purchasable"];            // ITEM_ROCK
    lua["TYPE_MAP"][366] = lua["Entity"]["as_web"];                    // ITEM_WEB
    lua["TYPE_MAP"][367] = lua["Entity"]["as_webshot"];                // ITEM_WEBSHOT
    lua["TYPE_MAP"][368] = lua["Entity"]["as_projectile"];             // ITEM_GIANTSPIDER_WEBSHOT
    lua["TYPE_MAP"][369] = lua["Entity"]["as_hangstrand"];             // ITEM_HANGSTRAND
    lua["TYPE_MAP"][370] = lua["Entity"]["as_hanganchor"];             // ITEM_HANGANCHOR
    lua["TYPE_MAP"][371] = lua["Entity"]["as_arrow"];                  // ITEM_WOODEN_ARROW
    lua["TYPE_MAP"][372] = lua["Entity"]["as_movable"];                // ITEM_BROKEN_ARROW
    lua["TYPE_MAP"][373] = lua["Entity"]["as_arrow"];                  // ITEM_METAL_ARROW
    lua["TYPE_MAP"][374] = lua["Entity"]["as_lightarrow"];             // ITEM_LIGHT_ARROW
    lua["TYPE_MAP"][375] = lua["Entity"]["as_lightshot"];              // ITEM_PLASMACANNON_SHOT
    lua["TYPE_MAP"][376] = lua["Entity"]["as_sceptershot"];            // ITEM_SCEPTER_ANUBISSHOT
    lua["TYPE_MAP"][377] = lua["Entity"]["as_specialshot"];            // ITEM_SCEPTER_ANUBISSPECIALSHOT
    lua["TYPE_MAP"][378] = lua["Entity"]["as_sceptershot"];            // ITEM_SCEPTER_PLAYERSHOT
    lua["TYPE_MAP"][379] = lua["Entity"]["as_soundshot"];              // ITEM_UFO_LASER_SHOT
    lua["TYPE_MAP"][380] = lua["Entity"]["as_soundshot"];              // ITEM_LAMASSU_LASER_SHOT
    lua["TYPE_MAP"][381] = lua["Entity"]["as_lightshot"];              // ITEM_SORCERESS_DAGGER_SHOT
    lua["TYPE_MAP"][382] = lua["Entity"]["as_lightshot"];              // ITEM_LASERTRAP_SHOT
    lua["TYPE_MAP"][383] = lua["Entity"]["as_spark"];                  // ITEM_SPARK
    lua["TYPE_MAP"][384] = lua["Entity"]["as_tiamatshot"];             // ITEM_TIAMAT_SHOT
    lua["TYPE_MAP"][385] = lua["Entity"]["as_fireball"];               // ITEM_FIREBALL
    lua["TYPE_MAP"][386] = lua["Entity"]["as_fireball"];               // ITEM_HUNDUN_FIREBALL
    lua["TYPE_MAP"][387] = lua["Entity"]["as_flame"];                  // ITEM_FLAMETHROWER_FIREBALL
    lua["TYPE_MAP"][388] = lua["Entity"]["as_leaf"];                   // ITEM_LEAF
    lua["TYPE_MAP"][389] = lua["Entity"]["as_movable"];                // ITEM_ACIDSPIT
    lua["TYPE_MAP"][390] = lua["Entity"]["as_movable"];                // ITEM_INKSPIT
    lua["TYPE_MAP"][391] = lua["Entity"]["as_movable"];                // ITEM_ACIDBUBBLE
    lua["TYPE_MAP"][392] = lua["Entity"]["as_acidbubble"];             // ITEM_CRABMAN_ACIDBUBBLE
    lua["TYPE_MAP"][393] = lua["Entity"]["as_claw"];                   // ITEM_CRABMAN_CLAW
    lua["TYPE_MAP"][394] = lua["Entity"]["as_stretchchain"];           // ITEM_CRABMAN_CLAWCHAIN
    lua["TYPE_MAP"][395] = lua["Entity"]["as_chest"];                  // ITEM_CHEST
    lua["TYPE_MAP"][396] = lua["Entity"]["as_movable"];                // ITEM_VAULTCHEST
    lua["TYPE_MAP"][397] = lua["Entity"]["as_treasure"];               // ITEM_ENDINGTREASURE_TIAMAT
    lua["TYPE_MAP"][398] = lua["Entity"]["as_hundunchest"];            // ITEM_ENDINGTREASURE_HUNDUN
    lua["TYPE_MAP"][399] = lua["Entity"]["as_movable"];                // ITEM_KEY
    lua["TYPE_MAP"][400] = lua["Entity"]["as_movable"];                // ITEM_LOCKEDCHEST
    lua["TYPE_MAP"][401] = lua["Entity"]["as_movable"];                // ITEM_LOCKEDCHEST_KEY
    lua["TYPE_MAP"][402] = lua["Entity"]["as_container"];              // ITEM_CRATE
    lua["TYPE_MAP"][403] = lua["Entity"]["as_container"];              // ITEM_DMCRATE
    lua["TYPE_MAP"][404] = lua["Entity"]["as_movable"];                // ITEM_TUTORIAL_MONSTER_SIGN
    lua["TYPE_MAP"][405] = lua["Entity"]["as_movable"];                // ITEM_CONSTRUCTION_SIGN
    lua["TYPE_MAP"][406] = lua["Entity"]["as_movable"];                // ITEM_SHORTCUT_SIGN
    lua["TYPE_MAP"][407] = lua["Entity"]["as_movable"];                // ITEM_SPEEDRUN_SIGN
    lua["TYPE_MAP"][408] = lua["Entity"]["as_movable"];                // ITEM_BASECAMP_TUTORIAL_SIGN
    lua["TYPE_MAP"][409] = lua["Entity"]["as_boombox"];                // ITEM_BOOMBOX
    lua["TYPE_MAP"][410] = lua["Entity"]["as_tv"];                     // ITEM_TV
    lua["TYPE_MAP"][411] = lua["Entity"]["as_telescope"];              // ITEM_TELESCOPE
    lua["TYPE_MAP"][412] = lua["Entity"]["as_walltorch"];              // ITEM_WALLTORCH
    lua["TYPE_MAP"][413] = lua["Entity"]["as_flamesize"];              // ITEM_WALLTORCHFLAME
    lua["TYPE_MAP"][414] = lua["Entity"]["as_walltorch"];              // ITEM_LITWALLTORCH
    lua["TYPE_MAP"][415] = lua["Entity"]["as_walltorch"];              // ITEM_AUTOWALLTORCH
    lua["TYPE_MAP"][416] = lua["Entity"]["as_torch"];                  // ITEM_TORCH
    lua["TYPE_MAP"][417] = lua["Entity"]["as_torchflame"];             // ITEM_TORCHFLAME
    lua["TYPE_MAP"][418] = lua["Entity"]["as_torch"];                  // ITEM_LAMP
    lua["TYPE_MAP"][419] = lua["Entity"]["as_lampflame"];              // ITEM_LAMPFLAME
    lua["TYPE_MAP"][420] = lua["Entity"]["as_torch"];                  // ITEM_REDLANTERN
    lua["TYPE_MAP"][421] = lua["Entity"]["as_lightemitter"];           // ITEM_REDLANTERNFLAME
    lua["TYPE_MAP"][422] = lua["Entity"]["as_present"];                // ITEM_PRESENT
    lua["TYPE_MAP"][423] = lua["Entity"]["as_present"];                // ITEM_GHIST_PRESENT
    lua["TYPE_MAP"][424] = lua["Entity"]["as_bullet"];                 // ITEM_BULLET
    lua["TYPE_MAP"][425] = lua["Entity"]["as_timedshot"];              // ITEM_FREEZERAYSHOT
    lua["TYPE_MAP"][426] = lua["Entity"]["as_clonegunshot"];           // ITEM_CLONEGUNSHOT
    lua["TYPE_MAP"][427] = lua["Entity"]["as_movable"];                // ITEM_ICECAGE
    lua["TYPE_MAP"][428] = lua["Entity"]["as_movable"];                // ITEM_BROKEN_MATTOCK
    lua["TYPE_MAP"][429] = lua["Entity"]["as_punishball"];             // ITEM_PUNISHBALL
    lua["TYPE_MAP"][430] = lua["Entity"]["as_stretchchain"];           // ITEM_PUNISHCHAIN
    lua["TYPE_MAP"][431] = lua["Entity"]["as_chain"];                  // ITEM_CHAIN
    lua["TYPE_MAP"][432] = lua["Entity"]["as_chain"];                  // ITEM_CHAIN_LASTPIECE
    lua["TYPE_MAP"][433] = lua["Entity"]["as_chain"];                  // ITEM_SLIDINGWALL_CHAIN
    lua["TYPE_MAP"][434] = lua["Entity"]["as_chain"];                  // ITEM_SLIDINGWALL_CHAIN_LASTPIECE
    lua["TYPE_MAP"][435] = lua["Entity"]["as_coffin"];                 // ITEM_COFFIN
    lua["TYPE_MAP"][436] = lua["Entity"]["as_fly"];                    // ITEM_FLY
    lua["TYPE_MAP"][437] = lua["Entity"]["as_olmeccannon"];            // ITEM_OLMECCANNON_BOMBS
    lua["TYPE_MAP"][438] = lua["Entity"]["as_olmeccannon"];            // ITEM_OLMECCANNON_UFO
    lua["TYPE_MAP"][439] = lua["Entity"]["as_landmine"];               // ITEM_LANDMINE
    lua["TYPE_MAP"][440] = lua["Entity"]["as_movable"];                // ITEM_CURSING_CLOUD
    lua["TYPE_MAP"][441] = lua["Entity"]["as_udjatsocket"];            // ITEM_UDJAT_SOCKET
    lua["TYPE_MAP"][442] = lua["Entity"]["as_ushabti"];                // ITEM_USHABTI
    lua["TYPE_MAP"][443] = lua["Entity"]["as_movable"];                // ITEM_TURKEY_NECK
    lua["TYPE_MAP"][444] = lua["Entity"]["as_honey"];                  // ITEM_HONEY
    lua["TYPE_MAP"][445] = lua["Entity"]["as_giantclamtop"];           // ITEM_GIANTCLAM_TOP
    lua["TYPE_MAP"][446] = lua["Entity"]["as_playerghost"];            // ITEM_PLAYERGHOST
    lua["TYPE_MAP"][447] = lua["Entity"]["as_ghostbreath"];            // ITEM_PLAYERGHOST_BREATH
    lua["TYPE_MAP"][448] = lua["Entity"]["as_movable"];                // ITEM_DIE
    lua["TYPE_MAP"][449] = lua["Entity"]["as_movable"];                // ITEM_DICE_BET
    lua["TYPE_MAP"][450] = lua["Entity"]["as_prizedispenser"];         // ITEM_DICE_PRIZE_DISPENSER
    lua["TYPE_MAP"][451] = lua["Entity"]["as_laserbeam"];              // ITEM_LASERBEAM
    lua["TYPE_MAP"][452] = lua["Entity"]["as_laserbeam"];              // ITEM_HORIZONTALLASERBEAM
    lua["TYPE_MAP"][453] = lua["Entity"]["as_coffin"];                 // ITEM_ANUBIS_COFFIN
    lua["TYPE_MAP"][454] = lua["Entity"]["as_movable"];                // ITEM_SPIKES
    lua["TYPE_MAP"][455] = lua["Entity"]["as_treasurehook"];           // ITEM_EGGSHIP_HOOK
    lua["TYPE_MAP"][456] = lua["Entity"]["as_axolotlshot"];            // ITEM_AXOLOTL_BUBBLESHOT
    lua["TYPE_MAP"][457] = lua["Entity"]["as_movable"];                // ITEM_POTOFGOLD
    lua["TYPE_MAP"][458] = lua["Entity"]["as_chain"];                  // ITEM_STICKYTRAP_PIECE
    lua["TYPE_MAP"][459] = lua["Entity"]["as_chain"];                  // ITEM_STICKYTRAP_LASTPIECE
    lua["TYPE_MAP"][460] = lua["Entity"]["as_trappart"];               // ITEM_STICKYTRAP_BALL
    lua["TYPE_MAP"][461] = lua["Entity"]["as_skulldroptrap"];          // ITEM_SKULLDROPTRAP
    lua["TYPE_MAP"][462] = lua["Entity"]["as_frozenliquid"];           // ITEM_FROZEN_LIQUID
    lua["TYPE_MAP"][463] = lua["Entity"]["as_container"];              // ITEM_ALIVE_EMBEDDED_ON_ICE
    lua["TYPE_MAP"][464] = lua["Entity"]["as_movable"];                // ITEM_DEPLOYED_PARACHUTE
    lua["TYPE_MAP"][465] = lua["Entity"]["as_switch"];                 // ITEM_SLIDINGWALL_SWITCH
    lua["TYPE_MAP"][466] = lua["Entity"]["as_switch"];                 // ITEM_SLIDINGWALL_SWITCH_REWARD
    lua["TYPE_MAP"][467] = lua["Entity"]["as_flyhead"];                // ITEM_GIANTFLY_HEAD
    lua["TYPE_MAP"][468] = lua["Entity"]["as_lightemitter"];           // ITEM_PALACE_CANDLE_FLAME
    lua["TYPE_MAP"][469] = lua["Entity"]["as_snaptrap"];               // ITEM_SNAP_TRAP
    lua["TYPE_MAP"][470] = lua["Entity"]["as_empressgrave"];           // ITEM_EMPRESS_GRAVE
    lua["TYPE_MAP"][471] = lua["Entity"]["as_tentacle"];               // ITEM_TENTACLE
    lua["TYPE_MAP"][472] = lua["Entity"]["as_chain"];                  // ITEM_TENTACLE_PIECE
    lua["TYPE_MAP"][473] = lua["Entity"]["as_chain"];                  // ITEM_TENTACLE_LAST_PIECE
    lua["TYPE_MAP"][474] = lua["Entity"]["as_minigameship"];           // ITEM_MINIGAME_SHIP
    lua["TYPE_MAP"][475] = lua["Entity"]["as_movable"];                // ITEM_MINIGAME_UFO
    lua["TYPE_MAP"][476] = lua["Entity"]["as_minigameasteroid"];       // ITEM_MINIGAME_ASTEROID_BG
    lua["TYPE_MAP"][477] = lua["Entity"]["as_minigameasteroid"];       // ITEM_MINIGAME_ASTEROID
    lua["TYPE_MAP"][478] = lua["Entity"]["as_minigameasteroid"];       // ITEM_MINIGAME_BROKEN_ASTEROID
    lua["TYPE_MAP"][480] = lua["Entity"]["as_pot"];                    // ITEM_POT
    lua["TYPE_MAP"][481] = lua["Entity"]["as_cursedpot"];              // ITEM_CURSEDPOT
    lua["TYPE_MAP"][482] = lua["Entity"]["as_purchasable"];            // ITEM_SKULL
    lua["TYPE_MAP"][483] = lua["Entity"]["as_movable"];                // ITEM_BONES
    lua["TYPE_MAP"][484] = lua["Entity"]["as_cookfire"];               // ITEM_COOKFIRE
    lua["TYPE_MAP"][485] = lua["Entity"]["as_lightemitter"];           // ITEM_LAVAPOT
    lua["TYPE_MAP"][486] = lua["Entity"]["as_movable"];                // ITEM_SCRAP
    lua["TYPE_MAP"][487] = lua["Entity"]["as_movable"];                // ITEM_EGGPLANT
    lua["TYPE_MAP"][488] = lua["Entity"]["as_movable"];                // ITEM_ICESPIRE
    lua["TYPE_MAP"][489] = lua["Entity"]["as_movable"];                // ITEM_PALACE_CANDLE
    lua["TYPE_MAP"][490] = lua["Entity"]["as_movable"];                // ITEM_SKULLDROPTRAP_SKULL
    lua["TYPE_MAP"][491] = lua["Entity"]["as_orb"];                    // ITEM_FLOATING_ORB
    lua["TYPE_MAP"][492] = lua["Entity"]["as_eggsac"];                 // ITEM_EGGSAC
    lua["TYPE_MAP"][495] = lua["Entity"]["as_goldbar"];                // ITEM_GOLDBAR
    lua["TYPE_MAP"][496] = lua["Entity"]["as_goldbar"];                // ITEM_GOLDBARS
    lua["TYPE_MAP"][497] = lua["Entity"]["as_movable"];                // ITEM_DIAMOND
    lua["TYPE_MAP"][498] = lua["Entity"]["as_movable"];                // ITEM_EMERALD
    lua["TYPE_MAP"][499] = lua["Entity"]["as_movable"];                // ITEM_SAPPHIRE
    lua["TYPE_MAP"][500] = lua["Entity"]["as_movable"];                // ITEM_RUBY
    lua["TYPE_MAP"][501] = lua["Entity"]["as_movable"];                // ITEM_NUGGET
    lua["TYPE_MAP"][502] = lua["Entity"]["as_coin"];                   // ITEM_GOLDCOIN
    lua["TYPE_MAP"][503] = lua["Entity"]["as_movable"];                // ITEM_EMERALD_SMALL
    lua["TYPE_MAP"][504] = lua["Entity"]["as_movable"];                // ITEM_SAPPHIRE_SMALL
    lua["TYPE_MAP"][505] = lua["Entity"]["as_movable"];                // ITEM_RUBY_SMALL
    lua["TYPE_MAP"][506] = lua["Entity"]["as_movable"];                // ITEM_NUGGET_SMALL
    lua["TYPE_MAP"][509] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_TORNJOURNALPAGE
    lua["TYPE_MAP"][510] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_JOURNAL
    lua["TYPE_MAP"][511] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_ROPE
    lua["TYPE_MAP"][512] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_ROPEPILE
    lua["TYPE_MAP"][513] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_BOMBBAG
    lua["TYPE_MAP"][514] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_BOMBBOX
    lua["TYPE_MAP"][515] = lua["Entity"]["as_playerbag"];              // ITEM_PICKUP_12BAG
    lua["TYPE_MAP"][516] = lua["Entity"]["as_playerbag"];              // ITEM_PICKUP_24BAG
    lua["TYPE_MAP"][517] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_ROYALJELLY
    lua["TYPE_MAP"][518] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_COOKEDTURKEY
    lua["TYPE_MAP"][519] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_GIANTFOOD
    lua["TYPE_MAP"][520] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_ELIXIR
    lua["TYPE_MAP"][521] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_CLOVER
    lua["TYPE_MAP"][522] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_SEEDEDRUNSUNLOCKER
    lua["TYPE_MAP"][524] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_SPECTACLES
    lua["TYPE_MAP"][525] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_CLIMBINGGLOVES
    lua["TYPE_MAP"][526] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_PITCHERSMITT
    lua["TYPE_MAP"][527] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_SPRINGSHOES
    lua["TYPE_MAP"][528] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_SPIKESHOES
    lua["TYPE_MAP"][529] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_PASTE
    lua["TYPE_MAP"][530] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_COMPASS
    lua["TYPE_MAP"][531] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_SPECIALCOMPASS
    lua["TYPE_MAP"][532] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_PARACHUTE
    lua["TYPE_MAP"][533] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_UDJATEYE
    lua["TYPE_MAP"][534] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_KAPALA
    lua["TYPE_MAP"][535] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_HEDJET
    lua["TYPE_MAP"][536] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_CROWN
    lua["TYPE_MAP"][537] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_EGGPLANTCROWN
    lua["TYPE_MAP"][538] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_TRUECROWN
    lua["TYPE_MAP"][539] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_ANKH
    lua["TYPE_MAP"][540] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_TABLETOFDESTINY
    lua["TYPE_MAP"][541] = lua["Entity"]["as_rollingitem"];            // ITEM_PICKUP_SKELETON_KEY
    lua["TYPE_MAP"][543] = lua["Entity"]["as_playerbag"];              // ITEM_PICKUP_PLAYERBAG
    lua["TYPE_MAP"][545] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_PASTE
    lua["TYPE_MAP"][546] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_CLIMBING_GLOVES
    lua["TYPE_MAP"][547] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_SPIKE_SHOES
    lua["TYPE_MAP"][548] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_SPRING_SHOES
    lua["TYPE_MAP"][549] = lua["Entity"]["as_kapalapowerup"];          // ITEM_POWERUP_KAPALA
    lua["TYPE_MAP"][550] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_SPECTACLES
    lua["TYPE_MAP"][551] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_PITCHERSMITT
    lua["TYPE_MAP"][552] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_UDJATEYE
    lua["TYPE_MAP"][553] = lua["Entity"]["as_parachutepowerup"];       // ITEM_POWERUP_PARACHUTE
    lua["TYPE_MAP"][554] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_COMPASS
    lua["TYPE_MAP"][555] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_SPECIALCOMPASS
    lua["TYPE_MAP"][556] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_HEDJET
    lua["TYPE_MAP"][557] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_CROWN
    lua["TYPE_MAP"][558] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_EGGPLANTCROWN
    lua["TYPE_MAP"][559] = lua["Entity"]["as_truecrownpowerup"];       // ITEM_POWERUP_TRUECROWN
    lua["TYPE_MAP"][560] = lua["Entity"]["as_ankhpowerup"];            // ITEM_POWERUP_ANKH
    lua["TYPE_MAP"][561] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_TABLETOFDESTINY
    lua["TYPE_MAP"][562] = lua["Entity"]["as_powerup"];                // ITEM_POWERUP_SKELETON_KEY
    lua["TYPE_MAP"][564] = lua["Entity"]["as_yellowcape"];             // ITEM_CAPE
    lua["TYPE_MAP"][565] = lua["Entity"]["as_vladscape"];              // ITEM_VLADS_CAPE
    lua["TYPE_MAP"][566] = lua["Entity"]["as_purchasable"];            // ITEM_PURCHASABLE_CAPE
    lua["TYPE_MAP"][567] = lua["Entity"]["as_jetpack"];                // ITEM_JETPACK
    lua["TYPE_MAP"][568] = lua["Entity"]["as_jetpack"];                // ITEM_JETPACK_MECH
    lua["TYPE_MAP"][569] = lua["Entity"]["as_dummypurchasableentity"]; // ITEM_PURCHASABLE_JETPACK
    lua["TYPE_MAP"][570] = lua["Entity"]["as_teleporterbackpack"];     // ITEM_TELEPORTER_BACKPACK
    lua["TYPE_MAP"][571] = lua["Entity"]["as_dummypurchasableentity"]; // ITEM_PURCHASABLE_TELEPORTER_BACKPACK
    lua["TYPE_MAP"][572] = lua["Entity"]["as_hoverpack"];              // ITEM_HOVERPACK
    lua["TYPE_MAP"][573] = lua["Entity"]["as_dummypurchasableentity"]; // ITEM_PURCHASABLE_HOVERPACK
    lua["TYPE_MAP"][574] = lua["Entity"]["as_backpack"];               // ITEM_POWERPACK
    lua["TYPE_MAP"][575] = lua["Entity"]["as_dummypurchasableentity"]; // ITEM_PURCHASABLE_POWERPACK
    lua["TYPE_MAP"][576] = lua["Entity"]["as_gun"];                    // ITEM_WEBGUN
    lua["TYPE_MAP"][577] = lua["Entity"]["as_gun"];                    // ITEM_SHOTGUN
    lua["TYPE_MAP"][578] = lua["Entity"]["as_gun"];                    // ITEM_FREEZERAY
    lua["TYPE_MAP"][579] = lua["Entity"]["as_bow"];                    // ITEM_CROSSBOW
    lua["TYPE_MAP"][580] = lua["Entity"]["as_gun"];                    // ITEM_CAMERA
    lua["TYPE_MAP"][581] = lua["Entity"]["as_teleporter"];             // ITEM_TELEPORTER
    lua["TYPE_MAP"][582] = lua["Entity"]["as_mattock"];                // ITEM_MATTOCK
    lua["TYPE_MAP"][583] = lua["Entity"]["as_boomerang"];              // ITEM_BOOMERANG
    lua["TYPE_MAP"][584] = lua["Entity"]["as_purchasable"];            // ITEM_MACHETE
    lua["TYPE_MAP"][585] = lua["Entity"]["as_excalibur"];              // ITEM_EXCALIBUR
    lua["TYPE_MAP"][586] = lua["Entity"]["as_movable"];                // ITEM_BROKENEXCALIBUR
    lua["TYPE_MAP"][587] = lua["Entity"]["as_gun"];                    // ITEM_PLASMACANNON
    lua["TYPE_MAP"][588] = lua["Entity"]["as_scepter"];                // ITEM_SCEPTER
    lua["TYPE_MAP"][589] = lua["Entity"]["as_gun"];                    // ITEM_CLONEGUN
    lua["TYPE_MAP"][590] = lua["Entity"]["as_bow"];                    // ITEM_HOUYIBOW
    lua["TYPE_MAP"][591] = lua["Entity"]["as_shield"];                 // ITEM_WOODEN_SHIELD
    lua["TYPE_MAP"][592] = lua["Entity"]["as_shield"];                 // ITEM_METAL_SHIELD
    lua["TYPE_MAP"][596] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_EGGSHIPPLATFORM
    lua["TYPE_MAP"][597] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_EGGSHIPBLOCKER
    lua["TYPE_MAP"][598] = lua["Entity"]["as_woodenlogtrap"];          // ACTIVEFLOOR_WOODENLOG_TRAP
    lua["TYPE_MAP"][599] = lua["Entity"]["as_boulder"];                // ACTIVEFLOOR_BOULDER
    lua["TYPE_MAP"][600] = lua["Entity"]["as_pushblock"];              // ACTIVEFLOOR_PUSHBLOCK
    lua["TYPE_MAP"][601] = lua["Entity"]["as_boneblock"];              // ACTIVEFLOOR_BONEBLOCK
    lua["TYPE_MAP"][602] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_BUSHBLOCK
    lua["TYPE_MAP"][603] = lua["Entity"]["as_pushblock"];              // ACTIVEFLOOR_POWDERKEG
    lua["TYPE_MAP"][604] = lua["Entity"]["as_chainedpushblock"];       // ACTIVEFLOOR_CHAINEDPUSHBLOCK
    lua["TYPE_MAP"][605] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_METALARROWPLATFORM
    lua["TYPE_MAP"][606] = lua["Entity"]["as_lightarrowplatform"];     // ACTIVEFLOOR_LIGHTARROWPLATFORM
    lua["TYPE_MAP"][607] = lua["Entity"]["as_fallingplatform"];        // ACTIVEFLOOR_FALLING_PLATFORM
    lua["TYPE_MAP"][608] = lua["Entity"]["as_trappart"];               // ACTIVEFLOOR_CHAINED_SPIKEBALL
    lua["TYPE_MAP"][609] = lua["Entity"]["as_unchainedspikeball"];     // ACTIVEFLOOR_UNCHAINED_SPIKEBALL
    lua["TYPE_MAP"][610] = lua["Entity"]["as_drill"];                  // ACTIVEFLOOR_DRILL
    lua["TYPE_MAP"][611] = lua["Entity"]["as_crushtrap"];              // ACTIVEFLOOR_CRUSH_TRAP
    lua["TYPE_MAP"][612] = lua["Entity"]["as_crushtrap"];              // ACTIVEFLOOR_CRUSH_TRAP_LARGE
    lua["TYPE_MAP"][613] = lua["Entity"]["as_olmec"];                  // ACTIVEFLOOR_OLMEC
    lua["TYPE_MAP"][614] = lua["Entity"]["as_timedpowderkeg"];         // ACTIVEFLOOR_TIMEDPOWDERKEG
    lua["TYPE_MAP"][615] = lua["Entity"]["as_trappart"];               // ACTIVEFLOOR_SLIDINGWALL
    lua["TYPE_MAP"][616] = lua["Entity"]["as_thinice"];                // ACTIVEFLOOR_THINICE
    lua["TYPE_MAP"][617] = lua["Entity"]["as_elevator"];               // ACTIVEFLOOR_ELEVATOR
    lua["TYPE_MAP"][618] = lua["Entity"]["as_clambase"];               // ACTIVEFLOOR_GIANTCLAM_BASE
    lua["TYPE_MAP"][619] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_KINGU_PLATFORM
    lua["TYPE_MAP"][620] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_TIAMAT_PLATFORM
    lua["TYPE_MAP"][621] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_TIAMAT_SHOULDERPLATFORM
    lua["TYPE_MAP"][622] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_BUBBLE_PLATFORM
    lua["TYPE_MAP"][623] = lua["Entity"]["as_crushelevator"];          // ACTIVEFLOOR_CRUSHING_ELEVATOR
    lua["TYPE_MAP"][624] = lua["Entity"]["as_movable"];                // ACTIVEFLOOR_SHIELD
    lua["TYPE_MAP"][625] = lua["Entity"]["as_regenblock"];             // ACTIVEFLOOR_REGENERATINGBLOCK
    lua["TYPE_MAP"][628] = lua["Entity"]["as_movable"];                // FX_EGGSHIP_SHELL
    lua["TYPE_MAP"][629] = lua["Entity"]["as_movable"];                // FX_EGGSHIP_DOOR
    lua["TYPE_MAP"][630] = lua["Entity"]["as_eggshipcenterjetflame"];  // FX_EGGSHIP_CENTERJETFLAME
    lua["TYPE_MAP"][631] = lua["Entity"]["as_movable"];                // FX_EGGSHIP_JETFLAME
    lua["TYPE_MAP"][632] = lua["Entity"]["as_movable"];                // FX_EGGSHIP_SHADOW
    lua["TYPE_MAP"][633] = lua["Entity"]["as_movable"];                // FX_SHADOW
    lua["TYPE_MAP"][634] = lua["Entity"]["as_fxtornjournalpage"];      // FX_TORNJOURNALPAGE
    lua["TYPE_MAP"][635] = lua["Entity"]["as_fxmainexitdoor"];         // FX_MAIN_EXIT_DOOR
    lua["TYPE_MAP"][636] = lua["Entity"]["as_birdies"];                // FX_BIRDIES
    lua["TYPE_MAP"][637] = lua["Entity"]["as_explosion"];              // FX_EXPLOSION
    lua["TYPE_MAP"][638] = lua["Entity"]["as_explosion"];              // FX_POWEREDEXPLOSION
    lua["TYPE_MAP"][639] = lua["Entity"]["as_explosion"];              // FX_MODERNEXPLOSION
    lua["TYPE_MAP"][640] = lua["Entity"]["as_fxouroborooccluder"];     // FX_OUROBORO_OCCLUDER
    lua["TYPE_MAP"][641] = lua["Entity"]["as_fxouroborodragonpart"];   // FX_OUROBORO_HEAD
    lua["TYPE_MAP"][642] = lua["Entity"]["as_fxouroborodragonpart"];   // FX_OUROBORO_TAIL
    lua["TYPE_MAP"][643] = lua["Entity"]["as_movable"];                // FX_OUROBORO_TEXT
    lua["TYPE_MAP"][644] = lua["Entity"]["as_movable"];                // FX_OUROBORO_TRAIL
    lua["TYPE_MAP"][645] = lua["Entity"]["as_rubble"];                 // ITEM_RUBBLE
    lua["TYPE_MAP"][646] = lua["Entity"]["as_fxcompass"];              // FX_COMPASS
    lua["TYPE_MAP"][647] = lua["Entity"]["as_fxcompass"];              // FX_SPECIALCOMPASS
    lua["TYPE_MAP"][648] = lua["Entity"]["as_fxplayerindicator"];      // FX_PLAYERINDICATOR
    lua["TYPE_MAP"][649] = lua["Entity"]["as_movable"];                // FX_PLAYERINDICATORPORTRAIT
    lua["TYPE_MAP"][650] = lua["Entity"]["as_movingicon"];             // FX_SALEICON
    lua["TYPE_MAP"][651] = lua["Entity"]["as_fxsalecontainer"];        // FX_SALEDIALOG_CONTAINER
    lua["TYPE_MAP"][652] = lua["Entity"]["as_movable"];                // FX_SALEDIALOG_TITLE
    lua["TYPE_MAP"][653] = lua["Entity"]["as_movable"];                // FX_SALEDIALOG_VALUE
    lua["TYPE_MAP"][654] = lua["Entity"]["as_movable"];                // FX_SALEDIALOG_ICON
    lua["TYPE_MAP"][655] = lua["Entity"]["as_fxpickupeffect"];         // FX_PICKUPEFFECT
    lua["TYPE_MAP"][656] = lua["Entity"]["as_fxshotgunblast"];         // FX_SHOTGUNBLAST
    lua["TYPE_MAP"][657] = lua["Entity"]["as_fxjetpackflame"];         // FX_JETPACKFLAME
    lua["TYPE_MAP"][658] = lua["Entity"]["as_flame"];                  // FX_SMALLFLAME
    lua["TYPE_MAP"][659] = lua["Entity"]["as_fxspringtrapring"];       // FX_SPRINGTRAP_RING
    lua["TYPE_MAP"][660] = lua["Entity"]["as_fxwitchdoctorhint"];      // FX_WITCHDOCTOR_HINT
    lua["TYPE_MAP"][661] = lua["Entity"]["as_fxnecromancerankh"];      // FX_NECROMANCER_ANKH
    lua["TYPE_MAP"][662] = lua["Entity"]["as_lightemitter"];           // FX_TELEPORTSHADOW
    lua["TYPE_MAP"][663] = lua["Entity"]["as_movable"];                // FX_CINEMATIC_BLACKBAR
    lua["TYPE_MAP"][664] = lua["Entity"]["as_olmecfloater"];           // FX_OLMECPART_FLOATER
    lua["TYPE_MAP"][665] = lua["Entity"]["as_movable"];                // FX_OLMECPART_LARGE
    lua["TYPE_MAP"][666] = lua["Entity"]["as_movable"];                // FX_OLMECPART_MEDIUM
    lua["TYPE_MAP"][667] = lua["Entity"]["as_movable"];                // FX_OLMECPART_SMALL
    lua["TYPE_MAP"][668] = lua["Entity"]["as_movable"];                // FX_OLMECPART_SMALLEST
    lua["TYPE_MAP"][669] = lua["Entity"]["as_fxwebbedeffect"];         // FX_WEBBEDEFFECT
    lua["TYPE_MAP"][670] = lua["Entity"]["as_button"];                 // FX_BUTTON
    lua["TYPE_MAP"][671] = lua["Entity"]["as_movable"];                // FX_BUTTON_DIALOG
    lua["TYPE_MAP"][672] = lua["Entity"]["as_sleepbubble"];            // FX_SLEEP_BUBBLE
    lua["TYPE_MAP"][673] = lua["Entity"]["as_movable"];                // FX_INK_BLINDNESS
    lua["TYPE_MAP"][674] = lua["Entity"]["as_movable"];                // FX_INK_SPLAT
    lua["TYPE_MAP"][675] = lua["Entity"]["as_movable"];                // FX_LAVA_BUBBLE
    lua["TYPE_MAP"][676] = lua["Entity"]["as_liquidsurface"];          // FX_LAVA_GLOW
    lua["TYPE_MAP"][677] = lua["Entity"]["as_fxunderwaterbubble"];     // FX_UNDERWATER_BUBBLE
    lua["TYPE_MAP"][678] = lua["Entity"]["as_fxwaterdrop"];            // FX_WATER_DROP
    lua["TYPE_MAP"][679] = lua["Entity"]["as_movable"];                // FX_WATER_SPLASH
    lua["TYPE_MAP"][680] = lua["Entity"]["as_liquidsurface"];          // FX_WATER_SURFACE
    lua["TYPE_MAP"][681] = lua["Entity"]["as_movable"];                // FX_APEP_FIRE
    lua["TYPE_MAP"][682] = lua["Entity"]["as_movable"];                // FX_APEP_MOUTHPIECE
    lua["TYPE_MAP"][683] = lua["Entity"]["as_movable"];                // FX_DRILL_TURNING
    lua["TYPE_MAP"][684] = lua["Entity"]["as_movable"];                // FX_LEADER_FLAG
    lua["TYPE_MAP"][685] = lua["Entity"]["as_movable"];                // FX_KINGU_HEAD
    lua["TYPE_MAP"][686] = lua["Entity"]["as_movable"];                // FX_KINGU_SHADOW
    lua["TYPE_MAP"][687] = lua["Entity"]["as_movable"];                // FX_KINGU_PLATFORM
    lua["TYPE_MAP"][688] = lua["Entity"]["as_movable"];                // FX_KINGU_LIMB
    lua["TYPE_MAP"][689] = lua["Entity"]["as_fxkingusliding"];         // FX_KINGU_SLIDING
    lua["TYPE_MAP"][690] = lua["Entity"]["as_movable"];                // FX_ALIENQUEEN_EYEBALL
    lua["TYPE_MAP"][691] = lua["Entity"]["as_movable"];                // FX_ALIENQUEEN_EYE
    lua["TYPE_MAP"][692] = lua["Entity"]["as_fxalienblast"];           // FX_ALIENBLAST_RETICULE_INTERNAL
    lua["TYPE_MAP"][693] = lua["Entity"]["as_fxalienblast"];           // FX_ALIENBLAST_RETICULE_EXTERNAL
    lua["TYPE_MAP"][694] = lua["Entity"]["as_fxalienblast"];           // FX_ALIENBLAST
    lua["TYPE_MAP"][695] = lua["Entity"]["as_movable"];                // FX_SPARK
    lua["TYPE_MAP"][696] = lua["Entity"]["as_fxsparksmall"];           // FX_SPARK_SMALL
    lua["TYPE_MAP"][697] = lua["Entity"]["as_movable"];                // FX_TIAMAT_THRONE
    lua["TYPE_MAP"][698] = lua["Entity"]["as_movable"];                // FX_TIAMAT_WAIST
    lua["TYPE_MAP"][699] = lua["Entity"]["as_fxtiamattail"];           // FX_TIAMAT_TAIL
    lua["TYPE_MAP"][700] = lua["Entity"]["as_fxtiamattail"];           // FX_TIAMAT_TAIL_DECO1
    lua["TYPE_MAP"][701] = lua["Entity"]["as_fxtiamattail"];           // FX_TIAMAT_TAIL_DECO2
    lua["TYPE_MAP"][702] = lua["Entity"]["as_fxtiamattail"];           // FX_TIAMAT_TAIL_DECO3
    lua["TYPE_MAP"][703] = lua["Entity"]["as_fxtiamattorso"];          // FX_TIAMAT_TORSO
    lua["TYPE_MAP"][704] = lua["Entity"]["as_movable"];                // FX_TIAMAT_ARM_LEFT1
    lua["TYPE_MAP"][705] = lua["Entity"]["as_movable"];                // FX_TIAMAT_ARM_LEFT2
    lua["TYPE_MAP"][706] = lua["Entity"]["as_movable"];                // FX_TIAMAT_ARM_LEFT3
    lua["TYPE_MAP"][707] = lua["Entity"]["as_movable"];                // FX_TIAMAT_ARM_RIGHT1
    lua["TYPE_MAP"][708] = lua["Entity"]["as_movable"];                // FX_TIAMAT_ARM_RIGHT2
    lua["TYPE_MAP"][709] = lua["Entity"]["as_movable"];                // FX_TIAMAT_NECK
    lua["TYPE_MAP"][710] = lua["Entity"]["as_fxtiamathead"];           // FX_TIAMAT_HEAD
    lua["TYPE_MAP"][711] = lua["Entity"]["as_movingicon"];             // FX_DIEINDICATOR
    lua["TYPE_MAP"][712] = lua["Entity"]["as_movingicon"];             // FX_STORAGE_INDICATOR
    lua["TYPE_MAP"][713] = lua["Entity"]["as_movable"];                // FX_LASERBEAM
    lua["TYPE_MAP"][714] = lua["Entity"]["as_movable"];                // FX_HORIZONTALLASERBEAM
    lua["TYPE_MAP"][715] = lua["Entity"]["as_fxvatbubble"];            // FX_VAT_BUBBLE
    lua["TYPE_MAP"][716] = lua["Entity"]["as_movable"];                // FX_CRUSHINGELEVATOR_FILL
    lua["TYPE_MAP"][717] = lua["Entity"]["as_movable"];                // FX_CRUSHINGELEVATOR_DECO
    lua["TYPE_MAP"][718] = lua["Entity"]["as_movable"];                // FX_HUNDUN_LIMB_THIGH
    lua["TYPE_MAP"][719] = lua["Entity"]["as_movable"];                // FX_HUNDUN_LIMB_CALF
    lua["TYPE_MAP"][720] = lua["Entity"]["as_movable"];                // FX_HUNDUN_LIMB_FOOT
    lua["TYPE_MAP"][721] = lua["Entity"]["as_movable"];                // FX_HUNDUN_EGG_CRACK
    lua["TYPE_MAP"][722] = lua["Entity"]["as_fxhundunneckpiece"];      // FX_HUNDUN_NECK_PIECE
    lua["TYPE_MAP"][723] = lua["Entity"]["as_movable"];                // FX_HUNDUN_WING
    lua["TYPE_MAP"][724] = lua["Entity"]["as_movable"];                // FX_HUNDUN_EYELID
    lua["TYPE_MAP"][725] = lua["Entity"]["as_movable"];                // FX_HUNDUN_EYEBALL
    lua["TYPE_MAP"][726] = lua["Entity"]["as_movable"];                // FX_HUNDUN_EYE
    lua["TYPE_MAP"][727] = lua["Entity"]["as_movable"];                // FX_PORTAL
    lua["TYPE_MAP"][728] = lua["Entity"]["as_movable"];                // FX_MEGAJELLYFISH_CROWN
    lua["TYPE_MAP"][729] = lua["Entity"]["as_megajellyfisheye"];       // FX_MEGAJELLYFISH_EYE
    lua["TYPE_MAP"][730] = lua["Entity"]["as_fxjellyfishstar"];        // FX_MEGAJELLYFISH_STAR
    lua["TYPE_MAP"][731] = lua["Entity"]["as_movable"];                // FX_MEGAJELLYFISH_FLIPPER
    lua["TYPE_MAP"][732] = lua["Entity"]["as_movable"];                // FX_MEGAJELLYFISH_BOTTOM
    lua["TYPE_MAP"][733] = lua["Entity"]["as_movable"];                // FX_MEGAJELLYFISH_TAIL
    lua["TYPE_MAP"][734] = lua["Entity"]["as_movable"];                // FX_MEGAJELLYFISH_TAIL_BG
    lua["TYPE_MAP"][735] = lua["Entity"]["as_movable"];                // FX_ANUBIS_SPECIAL_SHOT_RETICULE
    lua["TYPE_MAP"][736] = lua["Entity"]["as_movable"];                // FX_MECH_COLLAR
    lua["TYPE_MAP"][737] = lua["Entity"]["as_fxquicksand"];            // FX_QUICKSAND_DUST
    lua["TYPE_MAP"][738] = lua["Entity"]["as_fxquicksand"];            // FX_QUICKSAND_RUBBLE
    lua["TYPE_MAP"][739] = lua["Entity"]["as_fxsorceressattack"];      // FX_SORCERESS_ATTACK
    lua["TYPE_MAP"][740] = lua["Entity"]["as_fxlamassuattack"];        // FX_LAMASSU_ATTACK
    lua["TYPE_MAP"][741] = lua["Entity"]["as_fxfireflylight"];         // FX_CRITTERFIREFLY_LIGHT
    lua["TYPE_MAP"][742] = lua["Entity"]["as_movable"];                // FX_AXOLOTL_HEAD_ENTERING_DOOR
    lua["TYPE_MAP"][743] = lua["Entity"]["as_movable"];                // FX_BASECAMP_COUCH_ARM
    lua["TYPE_MAP"][744] = lua["Entity"]["as_fxempress"];              // FX_EMPRESS
    lua["TYPE_MAP"][745] = lua["Entity"]["as_movable"];                // FX_EGGSHIP_HOOK_CHAIN
    lua["TYPE_MAP"][746] = lua["Entity"]["as_minigameshipoffset"];     // FX_MINIGAME_SHIP_DOOR
    lua["TYPE_MAP"][747] = lua["Entity"]["as_minigameshipoffset"];     // FX_MINIGAME_SHIP_CENTERJETFLAME
    lua["TYPE_MAP"][748] = lua["Entity"]["as_minigameshipoffset"];     // FX_MINIGAME_SHIP_JETFLAME
    lua["TYPE_MAP"][750] = lua["Entity"]["as_fxankhrotatingspark"];    // FX_ANKH_ROTATINGSPARK
    lua["TYPE_MAP"][751] = lua["Entity"]["as_movable"];                // FX_ANKH_FALLINGSPARK
    lua["TYPE_MAP"][752] = lua["Entity"]["as_movable"];                // FX_ANKH_BACKGLOW
    lua["TYPE_MAP"][753] = lua["Entity"]["as_movable"];                // FX_ANKH_FRONTGLOW
    lua["TYPE_MAP"][754] = lua["Entity"]["as_movable"];                // FX_ANKH_LIGHTBEAM
    lua["TYPE_MAP"][755] = lua["Entity"]["as_fxankhbrokenpiece"];      // FX_ANKH_BROKENPIECE
    // lua["TYPE_MAP"][759] = lua["Entity"]["as_entity"];  // BG_SPACE (plain entity)
    lua["TYPE_MAP"][760] = lua["Entity"]["as_bgsurfacestar"];     // BG_SURFACE_STAR
    lua["TYPE_MAP"][761] = lua["Entity"]["as_bgshootingstar"];    // BG_SURFACE_SHOOTING_STAR
    lua["TYPE_MAP"][762] = lua["Entity"]["as_bgrelativeelement"]; // BG_SURFACE_SHOOTING_STAR_TRAIL
    lua["TYPE_MAP"][763] = lua["Entity"]["as_bgrelativeelement"]; // BG_SURFACE_SHOOTING_STAR_TRAIL_PARTICLE
    lua["TYPE_MAP"][764] = lua["Entity"]["as_bgmovingstar"];      // BG_SURFACE_MOVING_STAR
    lua["TYPE_MAP"][765] = lua["Entity"]["as_bgrelativeelement"]; // BG_SURFACE_NEBULA
    lua["TYPE_MAP"][766] = lua["Entity"]["as_bgsurfacelayer"];    // BG_SURFACE_LAYER
    // lua["TYPE_MAP"][767] = lua["Entity"]["as_entity"];  // BG_SURFACE_LAYER_OCCLUDER (plain entity)
    // lua["TYPE_MAP"][768] = lua["Entity"]["as_entity"];  // BG_SURFACE_LAYER_HOLE (plain entity)
    lua["TYPE_MAP"][769] = lua["Entity"]["as_bgsurfacelayer"]; // BG_SURFACE_ENTITY
    lua["TYPE_MAP"][770] = lua["Entity"]["as_bgsurfacelayer"]; // BG_SURFACE_OLMEC_LAYER
    // lua["TYPE_MAP"][771] = lua["Entity"]["as_entity"];  // BG_SURFACE_BACKGROUNDSEAM (plain entity)
    // lua["TYPE_MAP"][772] = lua["Entity"]["as_entity"];  // BG_CONSTELLATION_FLASH (plain entity)
    lua["TYPE_MAP"][773] = lua["Entity"]["as_bgsurfacestar"]; // BG_CONSTELLATION_STAR
    // lua["TYPE_MAP"][774] = lua["Entity"]["as_entity"];  // BG_CONSTELLATION_HALO (plain entity)
    // lua["TYPE_MAP"][775] = lua["Entity"]["as_entity"];  // BG_CONSTELLATION_GLOW (plain entity)
    lua["TYPE_MAP"][776] = lua["Entity"]["as_bgsurfacestar"]; // BG_CONSTELLATION_CONNECTION
    lua["TYPE_MAP"][777] = lua["Entity"]["as_bgeggshiproom"]; // BG_EGGSHIP_ROOM
    // lua["TYPE_MAP"][778] = lua["Entity"]["as_entity"];  // BG_PARENTSHIP_LANDINGLEG (plain entity)
    // lua["TYPE_MAP"][779] = lua["Entity"]["as_entity"];  // BG_ENDINGTREASURE_HUNDUN_GOLD (plain entity)
    // lua["TYPE_MAP"][780] = lua["Entity"]["as_entity"];  // BG_LEVEL_BACKWALL (plain entity)
    // lua["TYPE_MAP"][781] = lua["Entity"]["as_entity"];  // BG_LEVEL_DECO (plain entity)
    // lua["TYPE_MAP"][782] = lua["Entity"]["as_entity"];  // BG_LEVEL_SHADOW (plain entity)
    // lua["TYPE_MAP"][783] = lua["Entity"]["as_entity"];  // BG_LEVEL_BOMB_SOOT (plain entity)
    // lua["TYPE_MAP"][784] = lua["Entity"]["as_entity"];  // BG_LEVEL_POWEREDBOMB_SOOT (plain entity)
    // lua["TYPE_MAP"][785] = lua["Entity"]["as_entity"];  // BG_DOOR_LARGE (plain entity)
    // lua["TYPE_MAP"][786] = lua["Entity"]["as_entity"];  // BG_DOOR (plain entity)
    // lua["TYPE_MAP"][787] = lua["Entity"]["as_entity"];  // BG_DOOR_FRONT_LAYER (plain entity)
    lua["TYPE_MAP"][788] = lua["Entity"]["as_bgbacklayerdoor"]; // BG_DOOR_BACK_LAYER
    // lua["TYPE_MAP"][789] = lua["Entity"]["as_entity"];  // BG_DOOR_GHIST_SHOP (plain entity)
    // lua["TYPE_MAP"][790] = lua["Entity"]["as_entity"];  // BG_DOOR_BLACK_MARKET (plain entity)
    // lua["TYPE_MAP"][791] = lua["Entity"]["as_entity"];  // BG_DOOR_COG (plain entity)
    // lua["TYPE_MAP"][792] = lua["Entity"]["as_entity"];  // BG_DOOR_OLMEC_SHIP (plain entity)
    // lua["TYPE_MAP"][793] = lua["Entity"]["as_entity"];  // BG_DOOR_EGGPLANT_WORLD (plain entity)
    lua["TYPE_MAP"][794] = lua["Entity"]["as_bgtutorialsign"]; // BG_TUTORIAL_SIGN_BACK
    lua["TYPE_MAP"][795] = lua["Entity"]["as_bgtutorialsign"]; // BG_TUTORIAL_SIGN_FRONT
    // lua["TYPE_MAP"][796] = lua["Entity"]["as_entity"];  // BG_OUROBORO (plain entity)
    // lua["TYPE_MAP"][797] = lua["Entity"]["as_entity"];  // BG_DOORGEM (plain entity)
    // lua["TYPE_MAP"][798] = lua["Entity"]["as_entity"];  // BG_BASECAMP_DRESSER (plain entity)
    // lua["TYPE_MAP"][799] = lua["Entity"]["as_entity"];  // BG_BASECAMP_BUNKBED (plain entity)
    // lua["TYPE_MAP"][800] = lua["Entity"]["as_entity"];  // BG_BASECAMP_SIDETABLE (plain entity)
    // lua["TYPE_MAP"][801] = lua["Entity"]["as_entity"];  // BG_BASECAMP_DININGTABLE_DISHES (plain entity)
    // lua["TYPE_MAP"][802] = lua["Entity"]["as_entity"];  // BG_BASECAMP_SHORTCUTSTATIONBANNER (plain entity)
    // lua["TYPE_MAP"][803] = lua["Entity"]["as_entity"];  // BG_SHOP (plain entity)
    lua["TYPE_MAP"][804] = lua["Entity"]["as_bgshopentrance"]; // BG_SHOP_ENTRANCEDOOR
    // lua["TYPE_MAP"][805] = lua["Entity"]["as_entity"];  // BG_SHOP_BACKDOOR (plain entity)
    // lua["TYPE_MAP"][806] = lua["Entity"]["as_entity"];  // BG_SHOPWANTEDPOSTER (plain entity)
    // lua["TYPE_MAP"][807] = lua["Entity"]["as_entity"];  // BG_SHOPWANTEDPORTRAIT (plain entity)
    // lua["TYPE_MAP"][808] = lua["Entity"]["as_entity"];  // BG_SHOP_DICEPOSTER (plain entity)
    // lua["TYPE_MAP"][809] = lua["Entity"]["as_entity"];  // BG_KALI_STATUE (plain entity)
    // lua["TYPE_MAP"][810] = lua["Entity"]["as_entity"];  // MIDBG (plain entity)
    // lua["TYPE_MAP"][811] = lua["Entity"]["as_entity"];  // MIDBG_STYLEDDECORATION (plain entity)
    // lua["TYPE_MAP"][812] = lua["Entity"]["as_entity"];  // MIDBG_PALACE_STYLEDDECORATION (plain entity)
    // lua["TYPE_MAP"][813] = lua["Entity"]["as_entity"];  // MIDBG_BEEHIVE (plain entity)
    // lua["TYPE_MAP"][814] = lua["Entity"]["as_entity"];  // MIDBG_PLATFORM_STRUCTURE (plain entity)
    // lua["TYPE_MAP"][815] = lua["Entity"]["as_entity"];  // BG_UDJATSOCKET_DECORATION (plain entity)
    // lua["TYPE_MAP"][816] = lua["Entity"]["as_entity"];  // BG_DRILL_INDICATOR (plain entity)
    // lua["TYPE_MAP"][817] = lua["Entity"]["as_entity"];  // BG_VLAD_WINDOW (plain entity)
    // lua["TYPE_MAP"][818] = lua["Entity"]["as_entity"];  // BG_CROWN_STATUE (plain entity)
    // lua["TYPE_MAP"][819] = lua["Entity"]["as_entity"];  // BG_ANUBIS_THRONE (plain entity)
    // lua["TYPE_MAP"][820] = lua["Entity"]["as_entity"];  // BG_OLMEC_PILLAR (plain entity)
    // lua["TYPE_MAP"][821] = lua["Entity"]["as_entity"];  // BG_ICE_CRYSTAL (plain entity)
    lua["TYPE_MAP"][822] = lua["Entity"]["as_bgsurfacelayer"]; // BG_DUAT_LAYER
    // lua["TYPE_MAP"][823] = lua["Entity"]["as_entity"];  // BG_DUAT_SIDE_DECORATION (plain entity)
    lua["TYPE_MAP"][824] = lua["Entity"]["as_bgsurfacelayer"]; // BG_DUAT_PYRAMID_LAYER
    // lua["TYPE_MAP"][825] = lua["Entity"]["as_entity"];  // BG_DUAT_BLOODMOON (plain entity)
    lua["TYPE_MAP"][826] = lua["Entity"]["as_bgfloatingdebris"]; // BG_DUAT_FLOATINGDEBRIS
    lua["TYPE_MAP"][827] = lua["Entity"]["as_bgfloatingdebris"]; // BG_DUAT_FARFLOATINGDEBRIS
    // lua["TYPE_MAP"][828] = lua["Entity"]["as_entity"];  // BG_BOULDER_STATUE (plain entity)
    // lua["TYPE_MAP"][829] = lua["Entity"]["as_entity"];  // BG_MOAI_STATUE (plain entity)
    // lua["TYPE_MAP"][830] = lua["Entity"]["as_entity"];  // BG_VAT_BACK (plain entity)
    lua["TYPE_MAP"][831] = lua["Entity"]["as_bgshopkeeperprime"]; // BG_VAT_SHOPKEEPER_PRIME
    // lua["TYPE_MAP"][832] = lua["Entity"]["as_entity"];  // BG_VAT_FRONT (plain entity)
    // lua["TYPE_MAP"][833] = lua["Entity"]["as_entity"];  // BG_PALACE_CANDLE (plain entity)
    // lua["TYPE_MAP"][834] = lua["Entity"]["as_entity"];  // BG_PALACE_DISHES (plain entity)
    // lua["TYPE_MAP"][835] = lua["Entity"]["as_entity"];  // BG_MOTHER_STATUE (plain entity)
    // lua["TYPE_MAP"][836] = lua["Entity"]["as_entity"];  // BG_WATER_FOUNTAIN (plain entity)
    // lua["TYPE_MAP"][837] = lua["Entity"]["as_entity"];  // BG_YAMA_BODY (plain entity)
    // lua["TYPE_MAP"][838] = lua["Entity"]["as_entity"];  // BG_LEVEL_COSMIC (plain entity)
    lua["TYPE_MAP"][839] = lua["Entity"]["as_bgfloatingdebris"]; // BG_COSMIC_FLOATINGDEBRIS
    lua["TYPE_MAP"][840] = lua["Entity"]["as_bgfloatingdebris"]; // BG_COSMIC_FARFLOATINGDEBRIS
    // lua["TYPE_MAP"][841] = lua["Entity"]["as_entity"];  // BG_EGGSAC_STAINS (plain entity)
    // lua["TYPE_MAP"][844] = lua["Entity"]["as_entity"];  // LOGICAL_CONSTELLATION (plain entity)
    lua["TYPE_MAP"][845] = lua["Entity"]["as_shootingstarspawner"]; // LOGICAL_SHOOTING_STARS_SPAWNER
    lua["TYPE_MAP"][846] = lua["Entity"]["as_logicaldoor"];         // LOGICAL_DOOR
    lua["TYPE_MAP"][847] = lua["Entity"]["as_logicalsound"];        // LOGICAL_DOOR_AMBIENT_SOUND
    lua["TYPE_MAP"][848] = lua["Entity"]["as_logicaldoor"];         // LOGICAL_BLACKMARKET_DOOR
    lua["TYPE_MAP"][849] = lua["Entity"]["as_logicaltraptrigger"];  // LOGICAL_ARROW_TRAP_TRIGGER
    lua["TYPE_MAP"][850] = lua["Entity"]["as_logicaltraptrigger"];  // LOGICAL_TOTEM_TRAP_TRIGGER
    lua["TYPE_MAP"][851] = lua["Entity"]["as_jungletraptrigger"];   // LOGICAL_JUNGLESPEAR_TRAP_TRIGGER
    lua["TYPE_MAP"][852] = lua["Entity"]["as_logicaltraptrigger"];  // LOGICAL_SPIKEBALL_TRIGGER
    // lua["TYPE_MAP"][853] = lua["Entity"]["as_entity"];  // LOGICAL_CRUSH_TRAP_TRIGGER (plain entity)
    lua["TYPE_MAP"][854] = lua["Entity"]["as_logicaltraptrigger"]; // LOGICAL_TENTACLE_TRIGGER
    lua["TYPE_MAP"][855] = lua["Entity"]["as_weteffect"];          // LOGICAL_WET_EFFECT
    lua["TYPE_MAP"][856] = lua["Entity"]["as_onfireeffect"];       // LOGICAL_ONFIRE_EFFECT
    lua["TYPE_MAP"][857] = lua["Entity"]["as_poisonedeffect"];     // LOGICAL_POISONED_EFFECT
    lua["TYPE_MAP"][858] = lua["Entity"]["as_cursedeffect"];       // LOGICAL_CURSED_EFFECT
    // lua["TYPE_MAP"][859] = lua["Entity"]["as_entity"];  // LOGICAL_CAMERA_ANCHOR (plain entity)
    lua["TYPE_MAP"][860] = lua["Entity"]["as_ouroborocameraanchor"];     // LOGICAL_OUROBORO_CAMERA_ANCHOR
    lua["TYPE_MAP"][861] = lua["Entity"]["as_ouroborocamerazoomin"];     // LOGICAL_OUROBORO_CAMERA_ANCHOR_ZOOMIN
    lua["TYPE_MAP"][862] = lua["Entity"]["as_cinematicanchor"];          // LOGICAL_CINEMATIC_ANCHOR
    lua["TYPE_MAP"][863] = lua["Entity"]["as_burningropeeffect"];        // LOGICAL_BURNING_ROPE_EFFECT
    lua["TYPE_MAP"][864] = lua["Entity"]["as_dustwallapep"];             // LOGICAL_DUSTWALL_APEP
    lua["TYPE_MAP"][865] = lua["Entity"]["as_cameraflash"];              // LOGICAL_CAMERA_FLASH
    lua["TYPE_MAP"][866] = lua["Entity"]["as_roomlight"];                // LOGICAL_ROOM_LIGHT
    lua["TYPE_MAP"][867] = lua["Entity"]["as_limbanchor"];               // LOGICAL_LIMB_ANCHOR
    lua["TYPE_MAP"][868] = lua["Entity"]["as_portal"];                   // LOGICAL_PORTAL
    lua["TYPE_MAP"][869] = lua["Entity"]["as_logicalstaticsound"];       // LOGICAL_STATICLAVA_SOUND_SOURCE
    lua["TYPE_MAP"][870] = lua["Entity"]["as_logicalliquidstreamsound"]; // LOGICAL_STREAMLAVA_SOUND_SOURCE
    lua["TYPE_MAP"][871] = lua["Entity"]["as_logicalliquidstreamsound"]; // LOGICAL_STREAMWATER_SOUND_SOURCE
    lua["TYPE_MAP"][872] = lua["Entity"]["as_logicalconveyorbeltsound"]; // LOGICAL_CONVEYORBELT_SOUND_SOURCE
    lua["TYPE_MAP"][873] = lua["Entity"]["as_logicalanchovyflock"];      // LOGICAL_ANCHOVY_FLOCK
    lua["TYPE_MAP"][874] = lua["Entity"]["as_mummyfliessound"];          // LOGICAL_MUMMYFLIES_SOUND_SOURCE
    lua["TYPE_MAP"][875] = lua["Entity"]["as_logicalstaticsound"];       // LOGICAL_QUICKSAND_AMBIENT_SOUND_SOURCE
    lua["TYPE_MAP"][876] = lua["Entity"]["as_quicksandsound"];           // LOGICAL_QUICKSAND_SOUND_SOURCE
    lua["TYPE_MAP"][877] = lua["Entity"]["as_logicalsound"];             // LOGICAL_DUSTWALL_SOUND_SOURCE
    lua["TYPE_MAP"][878] = lua["Entity"]["as_iceslidingsound"];          // LOGICAL_ICESLIDING_SOUND_SOURCE
    lua["TYPE_MAP"][879] = lua["Entity"]["as_pipetravelersound"];        // LOGICAL_PIPE_TRAVELER_SOUND_SOURCE
    lua["TYPE_MAP"][880] = lua["Entity"]["as_boulderspawner"];           // LOGICAL_BOULDERSPAWNER
    lua["TYPE_MAP"][881] = lua["Entity"]["as_logicaldrain"];             // LOGICAL_WATER_DRAIN
    lua["TYPE_MAP"][882] = lua["Entity"]["as_logicaldrain"];             // LOGICAL_LAVA_DRAIN
    lua["TYPE_MAP"][883] = lua["Entity"]["as_logicalregeneratingblock"]; // LOGICAL_REGENERATING_BLOCK
    lua["TYPE_MAP"][884] = lua["Entity"]["as_logicaltraptrigger"];       // LOGICAL_BIGSPEAR_TRAP_TRIGGER
    // lua["TYPE_MAP"][885] = lua["Entity"]["as_entity"];  // LOGICAL_PLATFORM_SPAWNER (plain entity)
    // lua["TYPE_MAP"][886] = lua["Entity"]["as_entity"];  // LOGICAL_DM_SPAWN_POINT (plain entity)
    // lua["TYPE_MAP"][887] = lua["Entity"]["as_entity"];  // LOGICAL_DM_CAMERA_ANCHOR (plain entity)
    // lua["TYPE_MAP"][888] = lua["Entity"]["as_entity"];  // LOGICAL_DM_DEATH_MIST (plain entity)
    lua["TYPE_MAP"][889] = lua["Entity"]["as_dmalienblast"];          // LOGICAL_DM_ALIEN_BLAST
    lua["TYPE_MAP"][890] = lua["Entity"]["as_dmspawning"];            // LOGICAL_DM_CRATE_SPAWNING
    lua["TYPE_MAP"][891] = lua["Entity"]["as_dmspawning"];            // LOGICAL_DM_IDOL_SPAWNING
    lua["TYPE_MAP"][892] = lua["Entity"]["as_splashbubblegenerator"]; // LOGICAL_SPLASH_BUBBLE_GENERATOR
    lua["TYPE_MAP"][893] = lua["Entity"]["as_frostbreatheffect"];     // LOGICAL_FROST_BREATH
    lua["TYPE_MAP"][894] = lua["Entity"]["as_eggplantthrower"];       // LOGICAL_EGGPLANT_THROWER
    lua["TYPE_MAP"][895] = lua["Entity"]["as_logicalminigame"];       // LOGICAL_MINIGAME
    lua["TYPE_MAP"][899] = lua["Entity"]["as_mount"];                 // MOUNT_TURKEY
    lua["TYPE_MAP"][900] = lua["Entity"]["as_rockdog"];               // MOUNT_ROCKDOG
    lua["TYPE_MAP"][901] = lua["Entity"]["as_axolotl"];               // MOUNT_AXOLOTL
    lua["TYPE_MAP"][902] = lua["Entity"]["as_mech"];                  // MOUNT_MECH
    lua["TYPE_MAP"][903] = lua["Entity"]["as_qilin"];                 // MOUNT_QILIN
    lua["TYPE_MAP"][905] = lua["Entity"]["as_mount"];                 // MOUNT_BASECAMP_CHAIR
    lua["TYPE_MAP"][906] = lua["Entity"]["as_mount"];                 // MOUNT_BASECAMP_COUCH
    lua["TYPE_MAP"][909] = lua["Entity"]["as_liquid"];                // LIQUID_WATER
    lua["TYPE_MAP"][910] = lua["Entity"]["as_liquid"];                // LIQUID_COARSE_WATER
    // lua["TYPE_MAP"][911] = lua["Entity"]["as_entity"];  // LIQUID_IMPOSTOR_LAKE (plain entity)
    lua["TYPE_MAP"][912] = lua["Entity"]["as_lava"]; // LIQUID_LAVA
    lua["TYPE_MAP"][913] = lua["Entity"]["as_lava"]; // LIQUID_STAGNANT_LAVA
    // lua["TYPE_MAP"][914] = lua["Entity"]["as_entity"];  // LIQUID_IMPOSTOR_LAVA (plain entity)
    lua["TYPE_MAP"][915] = lua["Entity"]["as_lava"]; // LIQUID_COARSE_LAVA
}
} // namespace NEntityCasting
