#include "screen_lua.hpp"

#include <algorithm>   // for max
#include <array>       // for operator==
#include <new>         // for operator new
#include <sol/sol.hpp> // for proxy_key_t, state, data_t, table_proxy
#include <string>      // for operator==, allocator, u16string
#include <string_view> // for u16string_view
#include <tuple>       // for get
#include <type_traits> // for move, declval
#include <utility>     // for min, max

#include "aliases.hpp"       // for JournalPageType, JournalPageType::Bestiary
#include "entity.hpp"        // IWYU pragma: keep
#include "particles.hpp"     // IWYU pragma: keep
#include "screen.hpp"        // for ScreenCharacterSelect, ScreenOnlineLobby
#include "screen_arena.hpp"  // for ScreenArenaStagesSelect, ScreenArenaIntro
#include "sound_manager.hpp" //

namespace NScreen
{
void register_usertypes(sol::state& lua)
{
    lua.new_usertype<Screen>(
        "Screen",
        "render_timer",
        &Screen::render_timer);

    lua["Screen"]["as_screen_logo"] = &Screen::as<ScreenLogo>;
    lua["Screen"]["as_screen_intro"] = &Screen::as<ScreenIntro>;
    lua["Screen"]["as_screen_prologue"] = &Screen::as<ScreenPrologue>;
    lua["Screen"]["as_screen_title"] = &Screen::as<ScreenTitle>;
    lua["Screen"]["as_screen_menu"] = &Screen::as<ScreenMenu>;
    lua["Screen"]["as_screen_options"] = &Screen::as<ScreenOptions>;
    lua["Screen"]["as_screen_player_profile"] = &Screen::as<ScreenPlayerProfile>;
    lua["Screen"]["as_screen_leaderboards"] = &Screen::as<ScreenLeaderboards>;
    lua["Screen"]["as_screen_seed_input"] = &Screen::as<ScreenSeedInput>;
    lua["Screen"]["as_screen_character_select"] = &Screen::as<ScreenCharacterSelect>;
    lua["Screen"]["as_screen_team_select"] = &Screen::as<ScreenTeamSelect>;
    lua["Screen"]["as_screen_camp"] = &Screen::as<ScreenCamp>;
    lua["Screen"]["as_screen_level"] = &Screen::as<ScreenLevel>;
    lua["Screen"]["as_screen_transition"] = &Screen::as<ScreenTransition>;
    lua["Screen"]["as_screen_death"] = &Screen::as<ScreenDeath>;
    lua["Screen"]["as_screen_win"] = &Screen::as<ScreenWin>;
    lua["Screen"]["as_screen_credits"] = &Screen::as<ScreenCredits>;
    lua["Screen"]["as_screen_scores"] = &Screen::as<ScreenScores>;
    lua["Screen"]["as_screen_constellation"] = &Screen::as<ScreenConstellation>;
    lua["Screen"]["as_screen_recap"] = &Screen::as<ScreenRecap>;
    lua["Screen"]["as_screen_arena_menu"] = &Screen::as<ScreenArenaMenu>;
    lua["Screen"]["as_screen_arena_stages"] = &Screen::as<ScreenArenaStagesSelect>;
    lua["Screen"]["as_screen_arena_items"] = &Screen::as<ScreenArenaItems>;
    lua["Screen"]["as_screen_arena_select"] = &Screen::as<ScreenArenaStagesSelect>;
    lua["Screen"]["as_screen_arena_intro"] = &Screen::as<ScreenArenaIntro>;
    lua["Screen"]["as_screen_arena_level"] = &Screen::as<ScreenArenaLevel>;
    lua["Screen"]["as_screen_arena_score"] = &Screen::as<ScreenArenaScore>;
    lua["Screen"]["as_screen_online_loading"] = &Screen::as<ScreenOnlineLoading>;
    lua["Screen"]["as_screen_online_lobby"] = &Screen::as<ScreenOnlineLobby>;

    lua.new_usertype<ScreenLogo>(
        "ScreenLogo",
        "logo_mossmouth",
        &ScreenLogo::logo_mossmouth,
        "logo_blitworks",
        &ScreenLogo::logo_blitworks,
        "logo_fmod",
        &ScreenLogo::logo_fmod,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenIntro>(
        "ScreenIntro",
        "unknown4",
        &ScreenIntro::unknown4,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenPrologue>(
        "ScreenPrologue",
        "line1",
        &ScreenPrologue::line1,
        "line2",
        &ScreenPrologue::line2,
        "line3",
        &ScreenPrologue::line3,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenTitle>(
        "ScreenTitle",
        "logo_spelunky2",
        &ScreenTitle::logo_spelunky2,
        "ana",
        &ScreenTitle::ana,
        "ana_right_eyeball_torch_reflection",
        &ScreenTitle::ana_right_eyeball_torch_reflection,
        "ana_left_eyeball_torch_reflection",
        &ScreenTitle::ana_left_eyeball_torch_reflection,
        "particle_torchflame_smoke",
        &ScreenTitle::particle_torchflame_smoke,
        "particle_torchflame_backflames",
        &ScreenTitle::particle_torchflame_backflames,
        "particle_torchflame_flames",
        &ScreenTitle::particle_torchflame_flames,
        "particle_torchflame_backflames_animated",
        &ScreenTitle::particle_torchflame_backflames_animated,
        "particle_torchflame_flames_animated",
        &ScreenTitle::particle_torchflame_flames_animated,
        "particle_torchflame_ash",
        &ScreenTitle::particle_torchflame_ash,
        "background_music",
        &ScreenTitle::background_music,
        "torch_sound",
        &ScreenTitle::torch_sound,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenMenu>(
        "ScreenMenu",
        "tunnel_background",
        &ScreenMenu::tunnel_background,
        "cthulhu_disc",
        &ScreenMenu::cthulhu_disc,
        "tunnel_ring_darkbrown",
        &ScreenMenu::tunnel_ring_darkbrown,
        "cthulhu_body",
        &ScreenMenu::cthulhu_body,
        "tunnel_ring_lightbrown",
        &ScreenMenu::tunnel_ring_lightbrown,
        "vine_left",
        &ScreenMenu::vine_left,
        "vine_right",
        &ScreenMenu::vine_right,
        "skull_left",
        &ScreenMenu::skull_left,
        "salamander_right",
        &ScreenMenu::salamander_right,
        "left_spear",
        &ScreenMenu::left_spear,
        "right_spear",
        &ScreenMenu::right_spear,
        "spear_dangler_related",
        &ScreenMenu::spear_dangler_related,
        "play_scroll",
        &ScreenMenu::play_scroll,
        "info_toast",
        &ScreenMenu::info_toast,
        "cthulhu_disc_ring_angle",
        &ScreenMenu::cthulhu_disc_ring_angle,
        "cthulhu_disc_split_progress",
        &ScreenMenu::cthulhu_disc_split_progress,
        "cthulhu_disc_y",
        &ScreenMenu::cthulhu_disc_y,
        "cthulhu_timer",
        &ScreenMenu::cthulhu_timer,
        "selected_menu_index",
        &ScreenMenu::selected_menu_index,
        "menu_text_opacity",
        &ScreenMenu::menu_text_opacity,
        "menu_text_opacity",
        &ScreenMenu::menu_text_opacity,
        "spear_position",
        &ScreenMenu::spear_position,
        "spear_dangler",
        &ScreenMenu::spear_dangler,
        "play_scroll_descend_timer",
        &ScreenMenu::play_scroll_descend_timer,
        "scroll_text",
        &ScreenMenu::scroll_text,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenOptions>(
        "ScreenOptions",
        "selected_menu_index",
        &ScreenOptions::selected_menu_index,
        "brick_border",
        &ScreenOptions::brick_border,
        "top_bottom_woodpanels_velocity",
        &ScreenOptions::top_bottom_woodpanels_velocity,
        "top_bottom_woodpanels_progress",
        &ScreenOptions::top_bottom_woodpanels_progress,
        "scroll_unfurl_progress",
        &ScreenOptions::scroll_unfurl_progress,
        "bottom_woodpanel_y",
        &ScreenOptions::bottom_woodpanel_y,
        "top_bottom_woodpanels_slide_in_related",
        &ScreenOptions::top_bottom_woodpanels_slide_in_related,
        "bottom_woodpanel",
        &ScreenOptions::bottom_woodpanel,
        "top_woodpanel",
        &ScreenOptions::top_woodpanel,
        "top_woodpanel_left_scrollhandle",
        &ScreenOptions::top_woodpanel_left_scrollhandle,
        "top_woodpanel_right_scrollhandle",
        &ScreenOptions::top_woodpanel_right_scrollhandle,
        "button_right_caption",
        &ScreenOptions::button_right_caption,
        "button_middle_caption",
        &ScreenOptions::button_middle_caption,
        "top_woodpanel_visible",
        &ScreenOptions::top_woodpanel_visible,
        "bottom_woodpanel_visible",
        &ScreenOptions::bottom_woodpanel_visible,
        "toggle_woodpanel_slidein_animation",
        &ScreenOptions::toggle_woodpanel_slidein_animation,
        "capitalize_top_woodpanel",
        &ScreenOptions::capitalize_top_woodpanel,
        "current_menu_1",
        &ScreenOptions::current_menu_1,
        "current_menu_2",
        &ScreenOptions::current_menu_2,
        "topleft_woodpanel_esc",
        &ScreenOptions::topleft_woodpanel_esc,
        "brick_background",
        &ScreenOptions::brick_background,
        "brick_middlelayer",
        &ScreenOptions::brick_middlelayer,
        "brick_foreground",
        &ScreenOptions::brick_foreground,
        "selected_item_rounded_rect",
        &ScreenOptions::selected_item_rounded_rect,
        "selected_item_scarab",
        &ScreenOptions::selected_item_scarab,
        "item_option_arrow_left",
        &ScreenOptions::item_option_arrow_left,
        "item_option_arrow_right",
        &ScreenOptions::item_option_arrow_right,
        "tooltip_background",
        &ScreenOptions::tooltip_background,
        "progressbar_background",
        &ScreenOptions::progressbar_background,
        "progressbar_foreground",
        &ScreenOptions::progressbar_foreground,
        "progressbar_position_indicator",
        &ScreenOptions::progressbar_position_indicator,
        "sectionheader_background",
        &ScreenOptions::sectionheader_background,
        "topleft_woodpanel_esc_slidein_timer",
        &ScreenOptions::topleft_woodpanel_esc_slidein_timer,
        "text_fadein_timer",
        &ScreenOptions::text_fadein_timer,
        "vertical_scroll_effect_timer",
        &ScreenOptions::vertical_scroll_effect_timer,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenPlayerProfile>(
        "ScreenPlayerProfile",
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenLeaderboards>(
        "ScreenLeaderboards",
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenSeedInput>(
        "ScreenSeedInput",
        "bottom_woodpanel_slideup_timer",
        &ScreenSeedInput::bottom_woodpanel_slideup_timer,
        "bottom_woodpanel_y",
        &ScreenSeedInput::bottom_woodpanel_y,
        "bottom_woodpanel",
        &ScreenSeedInput::bottom_woodpanel,
        "buttons_text_id",
        &ScreenSeedInput::buttons_text_id,
        "topleft_woodpanel_esc_slidein_timer",
        &ScreenSeedInput::topleft_woodpanel_esc_slidein_timer,
        "scroll_text_id",
        &ScreenSeedInput::scroll_text_id,
        "start_text_id",
        &ScreenSeedInput::start_text_id,
        "main_woodpanel_left_border",
        &ScreenSeedInput::main_woodpanel_left_border,
        "main_woodpanel_center",
        &ScreenSeedInput::main_woodpanel_center,
        "main_woodpanel_right_border",
        &ScreenSeedInput::main_woodpanel_right_border,
        "seed_letter_cutouts",
        &ScreenSeedInput::seed_letter_cutouts,
        "topleft_woodpanel_esc",
        &ScreenSeedInput::topleft_woodpanel_esc,
        "start_sidepanel",
        &ScreenSeedInput::start_sidepanel,
        "start_sidepanel_slidein_timer",
        &ScreenSeedInput::start_sidepanel_slidein_timer,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenCharacterSelect>(
        "ScreenCharacterSelect",
        "main_background_zoom_target",
        &ScreenCharacterSelect::main_background_zoom_target,
        "blurred_border_zoom_target",
        &ScreenCharacterSelect::blurred_border_zoom_target,
        "top_bottom_woodpanel_slidein_timer",
        &ScreenCharacterSelect::top_bottom_woodpanel_slidein_timer,
        "top_scroll_unfurl_timer",
        &ScreenCharacterSelect::top_scroll_unfurl_timer,
        "bottom_woodpanel",
        &ScreenCharacterSelect::bottom_woodpanel,
        "top_woodpanel",
        &ScreenCharacterSelect::top_woodpanel,
        "left_scroll_handle",
        &ScreenCharacterSelect::left_scroll_handle,
        "right_scroll_handle",
        &ScreenCharacterSelect::right_scroll_handle,
        "left_button_text_id",
        &ScreenCharacterSelect::left_button_text_id,
        "right_button_text_id",
        &ScreenCharacterSelect::right_button_text_id,
        "middle_button_text_id",
        &ScreenCharacterSelect::middle_button_text_id,
        "top_woodpanel_visible",
        &ScreenCharacterSelect::top_woodpanel_visible,
        "bottom_woodpanel_visible",
        &ScreenCharacterSelect::bottom_woodpanel_visible,
        "toggle_woodpanel_slidein_animation",
        &ScreenCharacterSelect::toggle_woodpanel_slidein_animation,
        "mine_entrance_background",
        &ScreenCharacterSelect::mine_entrance_background,
        "character",
        &ScreenCharacterSelect::character,
        "character_shadow",
        &ScreenCharacterSelect::character_shadow,
        "character_flag",
        &ScreenCharacterSelect::character_flag,
        "character_left_arrow",
        &ScreenCharacterSelect::character_left_arrow,
        "character_right_arrow",
        &ScreenCharacterSelect::character_right_arrow,
        "mine_entrance_border",
        &ScreenCharacterSelect::mine_entrance_border,
        "mine_entrance_shutter",
        &ScreenCharacterSelect::mine_entrance_shutter,
        "background",
        &ScreenCharacterSelect::background,
        "blurred_border",
        &ScreenCharacterSelect::blurred_border,
        "blurred_border2",
        &ScreenCharacterSelect::blurred_border2,
        "topleft_woodpanel_esc",
        &ScreenCharacterSelect::topleft_woodpanel_esc,
        "start_sidepanel",
        &ScreenCharacterSelect::start_sidepanel,
        "quick_select_panel",
        &ScreenCharacterSelect::quick_select_panel,
        "quick_select_selected_char_background",
        &ScreenCharacterSelect::quick_select_selected_char_background,
        "quick_select_panel_related",
        &ScreenCharacterSelect::quick_select_panel_related,
        "player_shutter_timer",
        &ScreenCharacterSelect::player_shutter_timer,
        "player_x",
        &ScreenCharacterSelect::player_x,
        "player_y",
        &ScreenCharacterSelect::player_y,
        "player_arrow_slidein_timer",
        &ScreenCharacterSelect::player_arrow_slidein_timer,
        "player_facing_left",
        &ScreenCharacterSelect::player_facing_left,
        "player_quickselect_shown",
        &ScreenCharacterSelect::player_quickselect_shown,
        "player_quickselect_fadein_timer",
        &ScreenCharacterSelect::player_quickselect_fadein_timer,
        "player_quickselect_coords",
        &ScreenCharacterSelect::player_quickselect_coords,
        "player_quickselect_wiggle_angle",
        &ScreenCharacterSelect::player_quickselect_wiggle_angle,
        "topleft_woodpanel_esc_slidein_timer",
        &ScreenCharacterSelect::topleft_woodpanel_esc_slidein_timer,
        "start_panel_slidein_timer",
        &ScreenCharacterSelect::start_panel_slidein_timer,
        "action_buttons_keycap_size",
        &ScreenCharacterSelect::action_buttons_keycap_size,
        "not_ready_to_start_yet",
        &ScreenCharacterSelect::not_ready_to_start_yet,
        "available_mine_entrances",
        &ScreenCharacterSelect::available_mine_entrances,
        "amount_of_mine_entrances_activated",
        &ScreenCharacterSelect::amount_of_mine_entrances_activated,
        "buttons",
        &ScreenCharacterSelect::buttons,
        "opacity",
        &ScreenCharacterSelect::opacity,
        "start_pressed",
        &ScreenCharacterSelect::start_pressed,
        "transition_to_game_started",
        &ScreenCharacterSelect::transition_to_game_started,
        "flying_things",
        &ScreenCharacterSelect::flying_things,
        "flying_thing_countdown",
        &ScreenCharacterSelect::flying_thing_countdown,
        "particle_ceilingdust_smoke",
        &ScreenCharacterSelect::particle_ceilingdust_smoke,
        "particle_ceilingdust_rubble",
        &ScreenCharacterSelect::particle_ceilingdust_rubble,
        "particle_mist",
        &ScreenCharacterSelect::particle_mist,
        "particle_torchflame_smoke1",
        &ScreenCharacterSelect::particle_torchflame_smoke1,
        "particle_torchflame_flames1",
        &ScreenCharacterSelect::particle_torchflame_flames1,
        "particle_torchflame_smoke2",
        &ScreenCharacterSelect::particle_torchflame_smoke2,
        "particle_torchflame_flames2",
        &ScreenCharacterSelect::particle_torchflame_flames2,
        "particle_torchflame_smoke3",
        &ScreenCharacterSelect::particle_torchflame_smoke3,
        "particle_torchflame_flames3",
        &ScreenCharacterSelect::particle_torchflame_flames3,
        "particle_torchflame_smoke4",
        &ScreenCharacterSelect::particle_torchflame_smoke4,
        "particle_torchflame_flames4",
        &ScreenCharacterSelect::particle_torchflame_flames4,
        "sound",
        &ScreenCharacterSelect::sound,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<FlyingThing>(
        "FlyingThing",
        "texture_info",
        &FlyingThing::texture_info,
        "entity_type",
        &FlyingThing::entity_type,
        "spritesheet_column",
        &FlyingThing::spritesheet_column,
        "spritesheet_row",
        &FlyingThing::spritesheet_row,
        "spritesheet_animation_length",
        &FlyingThing::spritesheet_animation_length,
        "velocity_x",
        &FlyingThing::velocity_x,
        "amplitude",
        &FlyingThing::amplitude,
        "frequency",
        &FlyingThing::frequency,
        "sinewave_angle",
        &FlyingThing::sinewave_angle);

    lua.new_usertype<ScreenTeamSelect>(
        "ScreenTeamSelect",
        "ana_carrying_torch",
        &ScreenTeamSelect::ana_carrying_torch,
        "scroll_bottom_left",
        &ScreenTeamSelect::scroll_bottom_left,
        "scrollend_bottom_left",
        &ScreenTeamSelect::scrollend_bottom_left,
        "four_ropes",
        &ScreenTeamSelect::four_ropes,
        "unknown4",
        &ScreenTeamSelect::unknown4,
        "four_characters",
        &ScreenTeamSelect::four_characters,
        "left_arrow",
        &ScreenTeamSelect::left_arrow,
        "right_arrow",
        &ScreenTeamSelect::right_arrow,
        "start_panel",
        &ScreenTeamSelect::start_panel,
        "start_panel_slide_timer",
        &ScreenTeamSelect::start_panel_slide_timer,
        "pulsating_arrows_timer",
        &ScreenTeamSelect::pulsating_arrows_timer,
        "selected_player",
        &ScreenTeamSelect::selected_player,
        "buttons",
        &ScreenTeamSelect::buttons,
        "ready",
        &ScreenTeamSelect::ready,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenCamp>(
        "ScreenCamp",
        "buttons",
        &ScreenCamp::buttons,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenLevel>(
        "ScreenLevel",
        "buttons",
        &ScreenLevel::buttons,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenTransition>(
        "ScreenTransition",
        "woodpanel_pos",
        &ScreenTransition::woodpanel_pos,
        "stats_scroll_horizontal_posaa",
        &ScreenTransition::stats_scroll_horizontal_pos,
        "stats_scroll_vertical_pos",
        &ScreenTransition::stats_scroll_vertical_pos,
        "level_completed_pos",
        &ScreenTransition::level_completed_pos,
        "stats_scroll_unfurl_targetvalue",
        &ScreenTransition::stats_scroll_unfurl_targetvalue,
        "woodpanel1",
        &ScreenTransition::woodpanel1,
        "woodpanel2",
        &ScreenTransition::woodpanel2,
        "woodpanel3",
        &ScreenTransition::woodpanel3,
        "woodpanel_cutout1",
        &ScreenTransition::woodpanel_cutout1,
        "woodpanel_cutout2",
        &ScreenTransition::woodpanel_cutout2,
        "woodpanel_cutout3",
        &ScreenTransition::woodpanel_cutout3,
        "woodplank",
        &ScreenTransition::woodplank,
        "woodpanel_bottomcutout1",
        &ScreenTransition::woodpanel_bottomcutout1,
        "woodpanel_bottomcutout2",
        &ScreenTransition::woodpanel_bottomcutout2,
        "woodpanel_bottomcutout3",
        &ScreenTransition::woodpanel_bottomcutout3,
        "unknown_all_forced",
        &ScreenTransition::unknown_all_forced,
        "stats_scroll_top_bottom",
        &ScreenTransition::stats_scroll_top_bottom,
        "killcount_rounded_rect",
        &ScreenTransition::killcount_rounded_rect,
        "level_completed_panel",
        &ScreenTransition::level_completed_panel,
        "stats_scroll_state_1",
        &ScreenTransition::stats_scroll_state_1,
        "stats_scroll_state_2",
        &ScreenTransition::stats_scroll_state_2,
        "hide_press_to_go_next_level",
        &ScreenTransition::hide_press_to_go_next_level,
        "mama_tunnel",
        &ScreenTransition::mama_tunnel,
        "speechbubble",
        &ScreenTransition::speechbubble,
        "speechbubble_arrow",
        &ScreenTransition::speechbubble_arrow,
        "mama_tunnel_fade_targetvalue",
        &ScreenTransition::mama_tunnel_fade_targetvalue,
        "mama_tunnel_text_id",
        &ScreenTransition::mama_tunnel_text_id,
        "mama_tunnel_choice_visible",
        &ScreenTransition::mama_tunnel_choice_visible,
        "mama_tunnel_agree_with_gift",
        &ScreenTransition::mama_tunnel_agree_with_gift,
        "mama_tunnel_face_invisible",
        &ScreenTransition::mama_tunnel_face_invisible,
        "mama_tunnel_face_transparency",
        &ScreenTransition::mama_tunnel_face_transparency,
        "mama_tunnel_agree_panel",
        &ScreenTransition::mama_tunnel_agree_panel,
        "mama_tunnel_agree_panel_indicator",
        &ScreenTransition::mama_tunnel_agree_panel_indicator,
        "woodpanel_cutout_big_money1",
        &ScreenTransition::woodpanel_cutout_big_money1,
        "woodpanel_cutout_big_money2",
        &ScreenTransition::woodpanel_cutout_big_money2,
        "woodpanel_cutout_big_money3",
        &ScreenTransition::woodpanel_cutout_big_money3,
        "big_dollar_sign",
        &ScreenTransition::big_dollar_sign,
        "unknown26",
        &ScreenTransition::unknown26,
        "player_stats_scroll_numeric_value",
        &ScreenTransition::player_stats_scroll_numeric_value,
        "player_secondary_icon",
        &ScreenTransition::player_secondary_icon,
        "player_icon",
        &ScreenTransition::player_icon,
        "player_secondary_icon_type",
        &ScreenTransition::player_secondary_icon_type,
        "player_icon_index",
        &ScreenTransition::player_icon_index,
        "hourglasses",
        &ScreenTransition::hourglasses,
        "small_dollar_signs",
        &ScreenTransition::small_dollar_signs,
        "this_level_money_color",
        &ScreenTransition::this_level_money_color,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenDeath>(
        "ScreenDeath",
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenWin>(
        "ScreenWin",
        "sequence_timer",
        &ScreenWin::sequence_timer,
        "frame_timer",
        &ScreenWin::frame_timer,
        "animation_state",
        &ScreenWin::animation_state,
        "rescuing_ship_entity",
        &ScreenWin::rescuing_ship_entity,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenCredits>(
        "ScreenCredits",
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenScores>(
        "ScreenScores",
        "animation_state",
        &ScreenScores::animation_state,
        "woodpanel1",
        &ScreenScores::woodpanel1,
        "woodpanel2",
        &ScreenScores::woodpanel2,
        "woodpanel3",
        &ScreenScores::woodpanel3,
        "woodpanel_cutout",
        &ScreenScores::woodpanel_cutout,
        "dollarsign",
        &ScreenScores::dollarsign,
        "hourglass",
        &ScreenScores::hourglass,
        "animation_timer",
        &ScreenScores::animation_timer,
        "woodpanel_slidedown_timer",
        &ScreenScores::woodpanel_slidedown_timer,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenConstellation>(
        "ScreenConstellation",
        "sequence_state",
        &ScreenConstellation::sequence_state,
        "animation_timer",
        &ScreenConstellation::animation_timer,
        "constellation_text_opacity",
        &ScreenConstellation::constellation_text_opacity,
        "constellation_text",
        sol::property([](ScreenConstellation& s) -> std::u16string_view
                      {
                          std::u16string_view str(s.constellation_text);
                          return str; },
                      [](ScreenConstellation& s, std::u16string new_str)
                      {
                          const char16_t* src = new_str.c_str();
                          char16_t* temp = s.constellation_text;
                          unsigned int n = 0;
                          while ((*temp++ = *src++) != 0)
                              if (n++ >= 30)
                                  break;
                      }),
        "explosion_and_loop",
        &ScreenConstellation::explosion_and_loop,
        "bg_music",
        &ScreenConstellation::bg_music,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenRecap>(
        "ScreenRecap",
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenOnlineLoading>(
        "ScreenOnlineLoading",
        "ouroboros",
        &ScreenOnlineLoading::ouroboros,
        "ouroboros_angle",
        &ScreenOnlineLoading::ouroboros_angle,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<ScreenOnlineLobby>(
        "ScreenOnlineLobby",
        "woodpanels_slidein_timer",
        &ScreenOnlineLobby::woodpanels_slidein_timer,
        "scroll_unfurl_timer",
        &ScreenOnlineLobby::scroll_unfurl_timer,
        "woodpanel_bottom",
        &ScreenOnlineLobby::woodpanel_bottom,
        "woodpanel_top",
        &ScreenOnlineLobby::woodpanel_top,
        "left_scroll_handle",
        &ScreenOnlineLobby::left_scroll_handle,
        "right_scroll_handle",
        &ScreenOnlineLobby::right_scroll_handle,
        "scroll_text_id",
        &ScreenOnlineLobby::scroll_text_id,
        "btn_left_text_id",
        &ScreenOnlineLobby::btn_left_text_id,
        "btn_right_text_id",
        &ScreenOnlineLobby::btn_right_text_id,
        "btn_center_text_id",
        &ScreenOnlineLobby::btn_center_text_id,
        "woodpanel_top_visible",
        &ScreenOnlineLobby::woodpanel_top_visible,
        "woodpanel_bottom_visible",
        &ScreenOnlineLobby::woodpanel_bottom_visible,
        "toggle_panels_slidein",
        &ScreenOnlineLobby::toggle_panels_slidein,
        "players",
        &ScreenOnlineLobby::players,
        "background_image",
        &ScreenOnlineLobby::background_image,
        "topleft_woodpanel_esc",
        &ScreenOnlineLobby::topleft_woodpanel_esc,
        "topleft_woodpanel_esc_slidein_timer",
        &ScreenOnlineLobby::topleft_woodpanel_esc_slidein_timer,
        "character_walk_offset",
        &ScreenOnlineLobby::character_walk_offset,
        "character_facing_left",
        &ScreenOnlineLobby::character_facing_left,
        "move_direction",
        &ScreenOnlineLobby::move_direction,
        "character",
        &ScreenOnlineLobby::character,
        "player_ready_icon",
        &ScreenOnlineLobby::player_ready_icon,
        "arrow_left",
        &ScreenOnlineLobby::arrow_left,
        "arrow_right",
        &ScreenOnlineLobby::arrow_right,
        "arrow_left_hor_offset",
        &ScreenOnlineLobby::arrow_left_hor_offset,
        "arrow_right_hor_offset",
        &ScreenOnlineLobby::arrow_right_hor_offset,
        "platform_icon",
        &ScreenOnlineLobby::platform_icon,
        "player_count",
        &ScreenOnlineLobby::player_count,
        "searching_for_players",
        &ScreenOnlineLobby::searching_for_players,
        "show_code_panel",
        &ScreenOnlineLobby::show_code_panel,
        "enter_code_woodpanel_bottom_slidein_pos",
        &ScreenOnlineLobby::enter_code_woodpanel_bottom_slidein_pos,
        "enter_code_woodpanel_bottom",
        &ScreenOnlineLobby::enter_code_woodpanel_bottom,
        "enter_code_btn_right_text_id",
        &ScreenOnlineLobby::enter_code_btn_right_text_id,
        "enter_code_woodpanel_top_visible",
        &ScreenOnlineLobby::enter_code_woodpanel_top_visible,
        "enter_code_woodpanel_bottom_visible",
        &ScreenOnlineLobby::enter_code_woodpanel_bottom_visible,
        "enter_code_toggle_panels_slidein",
        &ScreenOnlineLobby::enter_code_toggle_panels_slidein,
        "selected_character",
        &ScreenOnlineLobby::selected_character,
        "characters_entered_count",
        &ScreenOnlineLobby::characters_entered_count,
        "enter_code_topleft_woodpanel_esc_slidein_timer",
        &ScreenOnlineLobby::enter_code_topleft_woodpanel_esc_slidein_timer,
        "enter_code_banner_text_id",
        &ScreenOnlineLobby::enter_code_banner_text_id,
        "enter_code_OK_text_id",
        &ScreenOnlineLobby::enter_code_OK_text_id,
        "enter_code_main_woodpanel_left",
        &ScreenOnlineLobby::enter_code_main_woodpanel_left,
        "enter_code_main_woodpanel_center",
        &ScreenOnlineLobby::enter_code_main_woodpanel_center,
        "enter_code_main_woodpanel_right",
        &ScreenOnlineLobby::enter_code_main_woodpanel_right,
        "enter_code_banner",
        &ScreenOnlineLobby::enter_code_banner,
        "enter_code_char_cutouts",
        &ScreenOnlineLobby::enter_code_char_cutouts,
        "enter_code_pointing_hand",
        &ScreenOnlineLobby::enter_code_pointing_hand,
        "enter_code_buttons",
        &ScreenOnlineLobby::enter_code_buttons,
        "enter_code_OK_panel",
        &ScreenOnlineLobby::enter_code_OK_panel,
        "enter_code_OK_panel_slidein_timer",
        &ScreenOnlineLobby::enter_code_OK_panel_slidein_timer,
        "enter_code_your_code_scroll",
        &ScreenOnlineLobby::enter_code_your_code_scroll,
        "enter_code_your_code_scroll_left_handle",
        &ScreenOnlineLobby::enter_code_your_code_scroll_left_handle,
        "enter_code_your_code_scroll_right_handle",
        &ScreenOnlineLobby::enter_code_your_code_scroll_right_handle,
        "set_code",
        &ScreenOnlineLobby::set_code,
        sol::base_classes,
        sol::bases<Screen>());

    lua.new_usertype<PauseUI>(
        "PauseUI",
        "menu_slidein_progress",
        &PauseUI::menu_slidein_progress,
        "blurred_background",
        &PauseUI::blurred_background,
        "woodpanel_left",
        &PauseUI::woodpanel_left,
        "woodpanel_middle",
        &PauseUI::woodpanel_middle,
        "woodpanel_right",
        &PauseUI::woodpanel_right,
        "woodpanel_top",
        &PauseUI::woodpanel_top,
        "scroll",
        &PauseUI::scroll,
        "confirmation_panel",
        &PauseUI::confirmation_panel,
        "previously_selected_menu_index",
        &PauseUI::previously_selected_menu_index,
        "visibility",
        &PauseUI::visibility);

    lua.new_usertype<JournalUI>(
        "JournalUI",
        "state",
        &JournalUI::state,
        "chapter_shown",
        &JournalUI::chapter_shown,
        "current_page",
        &JournalUI::current_page,
        "flipping_to_page",
        &JournalUI::flipping_to_page,
        "max_page_count",
        &JournalUI::max_page_count,
        "book_background",
        &JournalUI::book_background,
        "arrow_left",
        &JournalUI::arrow_left,
        "arrow_right",
        &JournalUI::arrow_right,
        "unknown23",
        &JournalUI::unknown23,
        "entire_book",
        &JournalUI::entire_book,
        "page_timer",
        &JournalUI::page_timer);

    lua.new_usertype<JournalPage>(
        "JournalPage",
        "background",
        &JournalPage::background,
        "page_number",
        &JournalPage::page_number);

    lua["JournalPage"]["as_journal_page_progress"] = &JournalPage::as<JournalPageProgress>;
    lua["JournalPage"]["as_journal_page_journalmenu"] = &JournalPage::as<JournalPageJournalMenu>;
    lua["JournalPage"]["as_journal_page_places"] = &JournalPage::as<JournalPagePlaces>;
    lua["JournalPage"]["as_journal_page_people"] = &JournalPage::as<JournalPagePeople>;
    lua["JournalPage"]["as_journal_page_bestiary"] = &JournalPage::as<JournalPageBestiary>;
    lua["JournalPage"]["as_journal_page_items"] = &JournalPage::as<JournalPageItems>;
    lua["JournalPage"]["as_journal_page_traps"] = &JournalPage::as<JournalPageTraps>;
    lua["JournalPage"]["as_journal_page_story"] = &JournalPage::as<JournalPageStory>;
    lua["JournalPage"]["as_journal_page_feats"] = &JournalPage::as<JournalPageFeats>;
    lua["JournalPage"]["as_journal_page_deathcause"] = &JournalPage::as<JournalPageDeathCause>;
    lua["JournalPage"]["as_journal_page_deathmenu"] = &JournalPage::as<JournalPageDeathMenu>;
    lua["JournalPage"]["as_journal_page_recap"] = &JournalPage::as<JournalPageRecap>;
    lua["JournalPage"]["as_journal_page_playerprofile"] = &JournalPage::as<JournalPagePlayerProfile>;
    lua["JournalPage"]["as_journal_page_lastgameplayed"] = &JournalPage::as<JournalPageLastGamePlayed>;

    lua.new_usertype<JournalPageProgress>(
        "JournalPageProgress",
        "coffeestain_top",
        &JournalPageProgress::coffeestain_top,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPageJournalMenu>(
        "JournalPageJournalMenu",
        "selected_menu_index",
        &JournalPageJournalMenu::selected_menu_index,
        "journal_text_info",
        &JournalPageJournalMenu::journal_text_info,
        "completion_badge",
        &JournalPageJournalMenu::completion_badge,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPageDiscoverable>(
        "JournalPageDiscoverable",
        "show_main_image",
        &JournalPageDiscoverable::show_main_image,
        "title_text_info",
        &JournalPageDiscoverable::title_text_info,
        "entry_text_info",
        &JournalPageDiscoverable::entry_text_info,
        "chapter_title_text_info",
        &JournalPageDiscoverable::chapter_title_text_info,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPagePlaces>(
        "JournalPagePlaces",
        "main_image",
        &JournalPagePlaces::main_image,
        sol::base_classes,
        sol::bases<JournalPage, JournalPageDiscoverable>());

    lua.new_usertype<JournalPagePeople>(
        "JournalPagePeople",
        "character_background",
        &JournalPagePeople::character_background,
        "character_icon",
        &JournalPagePeople::character_icon,
        "character_drawing",
        &JournalPagePeople::character_drawing,
        sol::base_classes,
        sol::bases<JournalPage, JournalPageDiscoverable>());

    lua.new_usertype<JournalPageBestiary>(
        "JournalPageBestiary",
        "monster_background",
        &JournalPageBestiary::monster_background,
        "monster_icon",
        &JournalPageBestiary::monster_icon,
        "defeated_killedby_black_bars",
        &JournalPageBestiary::defeated_killedby_black_bars,
        "defeated_text_info",
        &JournalPageBestiary::defeated_text_info,
        "defeated_value_text_info",
        &JournalPageBestiary::defeated_value_text_info,
        "killedby_text_info",
        &JournalPageBestiary::killedby_text_info,
        "killedby_value_text_info",
        &JournalPageBestiary::killedby_value_text_info,
        sol::base_classes,
        sol::bases<JournalPage, JournalPageDiscoverable>());

    lua.new_usertype<JournalPageItems>(
        "JournalPageItems",
        "item_icon",
        &JournalPageItems::item_icon,
        "item_background",
        &JournalPageItems::item_background,
        sol::base_classes,
        sol::bases<JournalPage, JournalPageDiscoverable>());

    lua.new_usertype<JournalPageTraps>(
        "JournalPageTraps",
        "trap_icon",
        &JournalPageTraps::trap_icon,
        "trap_background",
        &JournalPageTraps::trap_background,
        sol::base_classes,
        sol::bases<JournalPage, JournalPageDiscoverable>());

    lua.new_usertype<JournalPageStory>(
        "JournalPageStory",
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPageFeats>(
        "JournalPageFeats",
        "chapter_title_text_info",
        &JournalPageFeats::chapter_title_text_info,
        "feat_icons",
        &JournalPageFeats::feat_icons,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPageDeathCause>(
        "JournalPageDeathCause",
        "death_cause_text_info",
        &JournalPageDeathCause::death_cause_text_info,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPageDeathMenu>(
        "JournalPageDeathMenu",
        "selected_menu_index",
        &JournalPageDeathMenu::selected_menu_index,
        "game_over_text_info",
        &JournalPageDeathMenu::game_over_text_info,
        "level_text_info",
        &JournalPageDeathMenu::level_text_info,
        "level_value_text_info",
        &JournalPageDeathMenu::level_value_text_info,
        "money_text_info",
        &JournalPageDeathMenu::money_text_info,
        "money_value_text_info",
        &JournalPageDeathMenu::money_value_text_info,
        "time_text_info",
        &JournalPageDeathMenu::time_text_info,
        "time_value_text_info",
        &JournalPageDeathMenu::time_value_text_info,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPageRecap>(
        "JournalPageRecap",
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPagePlayerProfile>(
        "JournalPagePlayerProfile",
        "player_icon",
        &JournalPagePlayerProfile::player_icon,
        "player_icon_id",
        &JournalPagePlayerProfile::player_icon_id,
        "player_profile_text_info",
        &JournalPagePlayerProfile::player_profile_text_info,
        "plays_text_info",
        &JournalPagePlayerProfile::plays_text_info,
        "plays_value_text_info",
        &JournalPagePlayerProfile::plays_value_text_info,
        "wins_text_info",
        &JournalPagePlayerProfile::wins_text_info,
        "wins_value_text_info",
        &JournalPagePlayerProfile::wins_value_text_info,
        "deaths_text_info",
        &JournalPagePlayerProfile::deaths_text_info,
        "deaths_value_text_info",
        &JournalPagePlayerProfile::deaths_value_text_info,
        "win_pct_text_info",
        &JournalPagePlayerProfile::win_pct_text_info,
        "win_pct_value_text_info",
        &JournalPagePlayerProfile::win_pct_value_text_info,
        "average_score_text_info",
        &JournalPagePlayerProfile::average_score_text_info,
        "average_score_value_text_info",
        &JournalPagePlayerProfile::average_score_value_text_info,
        "top_score_text_info",
        &JournalPagePlayerProfile::top_score_text_info,
        "top_score_value_text_info",
        &JournalPagePlayerProfile::top_score_value_text_info,
        "deepest_level_text_info",
        &JournalPagePlayerProfile::deepest_level_text_info,
        "deepest_level_value_text_info",
        &JournalPagePlayerProfile::deepest_level_value_text_info,
        "deadliest_level_text_info",
        &JournalPagePlayerProfile::deadliest_level_text_info,
        "deadliest_level_value_text_info",
        &JournalPagePlayerProfile::deadliest_level_value_text_info,
        "average_time_text_info",
        &JournalPagePlayerProfile::average_time_text_info,
        "average_time_value_text_info",
        &JournalPagePlayerProfile::average_time_value_text_info,
        "best_time_text_info",
        &JournalPagePlayerProfile::best_time_text_info,
        "best_time_value_text_info",
        &JournalPagePlayerProfile::best_time_value_text_info,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.new_usertype<JournalPageLastGamePlayed>(
        "JournalPageLastGamePlayed",
        "main_image",
        &JournalPageLastGamePlayed::main_image,
        "last_game_played_text_info",
        &JournalPageLastGamePlayed::last_game_played_text_info,
        "level_text_info",
        &JournalPageLastGamePlayed::level_text_info,
        "level_value_text_info",
        &JournalPageLastGamePlayed::level_value_text_info,
        "money_text_info",
        &JournalPageLastGamePlayed::money_text_info,
        "money_value_text_info",
        &JournalPageLastGamePlayed::money_value_text_info,
        "time_text_info",
        &JournalPageLastGamePlayed::time_text_info,
        "time_value_text_info",
        &JournalPageLastGamePlayed::time_value_text_info,
        "sticker_count",
        &JournalPageLastGamePlayed::sticker_count,
        "stickers",
        &JournalPageLastGamePlayed::stickers,
        sol::base_classes,
        sol::bases<JournalPage>());

    lua.create_named_table(
        "SCREEN",
        "LOGO",
        0,
        "INTRO",
        1,
        "PROLOGUE",
        2,
        "TITLE",
        3,
        "MENU",
        4,
        "OPTIONS",
        5,
        "PLAYER_PROFILE",
        6,
        "LEADERBOARD",
        7,
        "SEED_INPUT",
        8,
        "CHARACTER_SELECT",
        9,
        "TEAM_SELECT",
        10,
        "CAMP",
        11,
        "LEVEL",
        12,
        "TRANSITION",
        13,
        "DEATH",
        14,
        "SPACESHIP",
        15,
        "WIN",
        16,
        "CREDITS",
        17,
        "SCORES",
        18,
        "CONSTELLATION",
        19,
        "RECAP",
        20,
        "ARENA_MENU",
        21,
        "ARENA_STAGES",
        22,
        "ARENA_ITEMS",
        23,
        "ARENA_SELECT",
        24,
        "ARENA_INTRO",
        25,
        "ARENA_LEVEL",
        26,
        "ARENA_SCORE",
        27,
        "ONLINE_LOADING",
        28,
        "ONLINE_LOBBY",
        29);

    lua.create_named_table(
        "PAUSEUI_VISIBILITY",
        "INVISIBLE",
        0,
        "SLIDING_DOWN",
        1,
        "VISIBLE",
        2,
        "SLIDING_UP",
        3);

    lua.create_named_table(
        "JOURNALUI_STATE",
        "INVISIBLE",
        0,
        "FADING_IN",
        1,
        "STABLE",
        2,
        "FLIPPING_LEFT",
        3,
        "FLIPPING_RIGHT",
        4,
        "FADING_OUT",
        5);

    lua.create_named_table(
        "JOURNALUI_PAGE_SHOWN",
        "PLAYER_PROFILE",
        1,
        "JOURNAL",
        2,
        "PLACES",
        3,
        "PEOPLE",
        4,
        "BESTIARY",
        5,
        "ITEMS",
        6,
        "TRAPS",
        7,
        "STORY",
        8,
        "RECAP",
        9,
        "DEATH",
        10);

    lua.create_named_table(
        "JOURNAL_PAGE_TYPE",
        "PROGRESS",
        JournalPageType::Progress,
        "JOURNAL_MENU",
        JournalPageType::JournalMenu,
        "PLACES",
        JournalPageType::Places,
        "PEOPLE",
        JournalPageType::People,
        "BESTIARY",
        JournalPageType::Bestiary,
        "ITEMS",
        JournalPageType::Items,
        "TRAPS",
        JournalPageType::Traps,
        "STORY",
        JournalPageType::Story,
        "FEATS",
        JournalPageType::Feats,
        "DEATH_CAUSE",
        JournalPageType::DeathCause,
        "DEATH_MENU",
        JournalPageType::DeathMenu,
        "RECAP",
        JournalPageType::Recap,
        "PLAYER_PROFILE",
        JournalPageType::PlayerProfile,
        "LAST_GAME_PLAYED",
        JournalPageType::LastGamePlayed);
}
} // namespace NScreen
